### ISSUE TITLE
[Bug] Unifi widget returns 'HTTP Error 403' 'Invalid CSRF Token'

### ISSUE THREAD

**Issue by rramchar** [benphelps/homepage#1006]
### Description

The Unifi widget returns the following error.

    API Error: HTTP Error 403
    URL: https://192.168.1.1/proxy/network/api/stat/sites
    Response Data:
    {"message":"Invalid CSRF Token"}

UDMP Version: 1.11.0
Network Version: 7.2.97

My configuration is below
    - UDMP:
        icon: ubiquiti
        href: https://192.168.1.1
        description: UDM Pro
        ping: https://192.168.1.1
        widget:
            type: unifi
            url: https://192.168.1.1
            username: monitor
            password: *********

### Steps to reproduce

Create the following in the services.yaml

- Network:
    - UDMP:
        icon: ubiquiti
        href: https://192.168.1.1
        description: UDM Pro
        ping: https://192.168.1.1
        widget:
            type: unifi
            url: https://192.168.1.1
            username: monitor
            password: ********

create a readonly user called monitor on the UDM Pro.
refresh the homepage 

### homepage version

v0.6.7 (f8a0c69, Feb 7, 2023)

### Installation method

Docker

### Configuration

```yaml
Create the following in the services.yaml

- Network:
    - UDMP:
        icon: ubiquiti
        href: https://192.168.1.1
        description: UDM Pro
        ping: https://192.168.1.1
        widget:
            type: unifi
            url: https://192.168.1.1
            username: monitor
            password: ********
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
