### ISSUE TITLE
[Bug] Use of PGID is broken in v0.6.0

### ISSUE THREAD

**Issue by hyim28** [benphelps/homepage#1064]
### Description

Starting in v0.6.0, PGID is not being use, instead of group root is being use to perfrom chmod during initialization.

### Steps to reproduce

1. config directory is set to the same PUID/PGID before starting docker-compose.
2. Start running docker-compose.
3. config directory is now in PUID/root.

xxxx@docker-px02 ~/homepage$ ls -l
total 12
drwxr-xr-x 4 plex   root 4096 Feb 26 07:40 config

### homepage version

v0.6.0

### Installation method

Docker

### Configuration

```yaml
version: "3.3"
services:
  homepage:
##    image: ghcr.io/benphelps/homepage:latest
    image: ghcr.io/benphelps/homepage:v0.6.0
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/xxxx/homepage/config:/app/config # Make sure your local config directory exists
      - /home/xxxx/homepage/config/icons:/app/public/icons # Make sure your local config directory exists
    environment:
      PUID: 972
      GUID: 31
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
