### ISSUE TITLE
[Bug] error: <httpProxy> Error calling http://HOST_IP_HOMEPAGE_IS_LISTENING_ON/...

### ISSUE THREAD

**Issue by spyhuntergenral** [benphelps/homepage#1074]
### Description

This feels like a Bug: 
As i keep getting the homepage log file flooded with the below error message, 
although everything on the front end appears to be working fine. 
it only seems to happen when i load up or refresh the homepage front end.
Also I have only noticed it when enabling Qbittorent 4.4.3.1--4.7.0, all other containers i have do not produce the error.
Note the service/widget actually works correctly there is just a error posted in the log.

compose service:
```
  homepage:
    image: ghcr.io/benphelps/homepage
    container_name: "homepage"
    hostname: "homepage"
    restart: unless-stopped
    ports:
      - "${HOST_IP}:4000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./homepage:/app/config
      - /data:/data:ro
    environment:
      LOG_LEVEL: debug
```

Using the labeling feature so on qbittorrent container:
```
....
    labels:
      - homepage.group=Downloaders
      - homepage.name=qbittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://${HOST_IP}:9666/
      - homepage.description=Download Management
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://${HOST_IP}:9666
```

### Steps to reproduce

1) enable qbittorrent service
2) Load the Homepage URL
3) Check log file

### homepage version

v0.6.10 (af2566c, Mar 1, 2023)

### Installation method

Docker

### Container Logs

```
[2023-03-01T22:56:06.573Z] error: <httpProxy> Error calling http://192.168.99.50/...
[2023-03-01T22:56:06.582Z] error: <httpProxy> [
  500,
  Error: Parse Error: Expected HTTP/
      at Socket.socketOnData (node:_http_client:542:22)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    bytesParsed: 478,
    code: 'HPE_INVALID_CONSTANT',
    reason: 'Expected HTTP/',
    rawPacket: <Buffer 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 63 61 63 68 65 2d 63 6f 6e 74 72 6f 6c 3a 20 6e 6f 2d 73 74 6f 72 65 0d 0a 63 6f 6e 6e 65 63 74 69 ... 20610 more bytes>
  }
]
```

### Browser Logs

N/A - happens with both Firefox and brave.

### Other

Docker Version: 23.0.1

Setting  LOG_LEVEL to debug yields no further information 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
