### ISSUE TITLE
[Feature Request] Codex Widget

### ISSUE THREAD

**Issue by ajslater** [benphelps/homepage#1075]
### Description

[Codex](https://github.com/ajslater/codex) is a webserver comic book reader. Support for codex is often conducted on the [Mylar](https://github.com/mylar3/mylar3) discord.

A widget for Codex would accept an API Key and display the number of Publishers, Series and Issues that Codex is serving.

### Other

I have a fully working and linted PR for this widget ready to submit at a moment's notice, but protocol seems not to be to submit PRs first.
Docs for usage will be extremely similar to other simple widgets, e.g.:
```
        widget:
          type: codex
          url: https://codex.host.or.ip:port
          key: yourCodexAPIKey
```

I have a PR submitted with Codex's icons to [Dashboard Icons](https://github.com/walkxcode/dashboard-icons/pull/299)
So with any luck that should work out of the box. If not, I'll write docs showing users which url they can get Codex's icon from on their own server.
