### ISSUE TITLE
[Bug] settings.yaml ignored after recreate

### ISSUE THREAD

**Issue by thefeli73** [benphelps/homepage#1076]
### Description

When i write to the settings file while homepage is running it live updates and everything is fine. But when i do a compose recreate: 
```yaml
#!/bin/bash

cd /root
docker compose pull
docker compose up --detach --force-recreate
docker image prune -f
```
then settings are ignored. i can then append a space somewhere and homepage will realise the settings are updated and reload with them.
Nothing interesting in the logs (even in debug mode). 

### Steps to reproduce

1. install container.
2. force recreate
3. > settings ignored

### homepage version

v0.6.10 (af2566c, Feb 28, 2023)

### Installation method

Docker

### Configuration

XXXX=private information

settings.yaml:
```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
 
title: XXXX
theme: dark # or light
color: emerald # slate, gray, zinc, neutral, stone, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
headerStyle: boxed
base: XXXX
quicklaunch:
  searchDescriptions: true
hideVersion: true
layout:
  Media Collectors:
    style: row
    columns: 3
  Misc:
    style: row
    columns: 4
  Network:
  Statistics:
  Media Management:
```

docker-compose.yaml:
```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    restart: always
    network_mode: host
```

services.yml:
```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Misc:
    - Open Media Vault:
        description: File Server
        icon: openmediavault
        href: XXXX
        ping: XXXX
    - Home Assistant:
        description: Smart Home Management
        icon: home-assistant
        href: XXXX
        ping: XXXX
    - Application Management Panel:
        description: Game Servers
        icon: amp
        href: XXXX
        ping: XXXX
    - Vaultwarden:
        description: Password Manager
        icon: vaultwarden
        href: XXXX
        ping: XXXX

- Network:
    - Proxmox:
        description: Server Hypervisor
        icon: proxmox
        href: XXXX
        ping: XXXX
        widget:
          type: proxmox
          url: XXXX
          username: XXXX
          password: XXXX
    - Nginx Proxy Manager:
        description: Reverse Proxy
        icon: nginxproxymanager
        href: XXXX
        ping: XXXX
        widget:
          type: npm
          url: XXXX
          username: XXXX
          password: XXXX
    - PiHole:
        description: DNS & DHCP 
        icon: pihole
        href: XXXX
        ping: XXXX
        widget:
          type: pihole
          url: XXXX
          key: XXXX
    - Cloudflare:
        description: DDoS & IP Protection
        icon: cloudflare
        href: https://dash.cloudflare.com/
- Statistics:
    - Uptime Kuma:
        description: Uptime Statistics
        icon: uptime-kuma
        href: XXXX
        ping: XXXX
        widget:
          type: uptimekuma
          url: XXXX
          slug: default
    - Tautulli:
        description: Plex Statistics
        icon: tautulli
        href: XXXX
        ping: XXXX
        widget:
          type: tautulli
          url: XXXX
          key: XXXX
    - Prometheus:
        description: Monitoring Metrics 
        icon: prometheus
        href: XXXX
        ping: XXXX
        widget:
          type: prometheus
          url: XXXX
    - Grafana:
        description: Monitoring Dashboards
        icon: grafana
        href: XXXX
        ping: XXXX
- Media Collectors:
    - SABnzbd:
        description: Usenet Downloader
        icon: sabnzbd-text
        href: XXXX
        ping: XXXX
        widget:
          type: sabnzbd
          url: XXXX
          key: XXXX
    - Transmission:
        description: Bittorrent Client
        icon: transmission
        href: XXXX
        ping: XXXX
        widget:
          type: transmission
          url: XXXX
          key: XXXX
    - Prowlarr:
        description: Indexer Management
        icon: prowlarr
        href: XXXX
        ping: XXXX
        widget:
          type: prowlarr
          url: XXXX
          key: XXXX
- Media Management:
    - Plex:
        description: Streaming
        icon: plex
        href: XXXX
        ping: XXXX
        widget:
          type: plex
          url: XXXX
          key: XXXX
    - Sonarr:
        description: Series Management
        icon: sonarr
        href: XXXX
        ping: XXXX
        widget:
          type: sonarr
          url: XXXX
          key: XXXX
    - Radarr:
        description: Movie Management
        icon: radarr
        href: XXXX
        ping: XXXX
        widget:
          type: radarr
          url: XXXX
          key: XXXX
    - Lidarr:
        description: Music Management
        icon: lidarr
        href: XXXX
        ping: XXXX
#        widget:
#          type: lidarr
#          url: XXXX
#          key: XXXX
    - Bazarr:
        description: Subtitle Management
        icon: bazarr
        href: XXXX
        ping: XXXX
#        widget:
#          type: bazarr
#          url: XXXX
#          key: XXXX
    - Readarr:
        description: Book Management
        icon: readarr
        href: XXXX
        ping: XXXX
#        widget:
#          type: readarr
#          url: XXXX
#          key: XXXX
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
