### ISSUE TITLE
[Bug] API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by casudo** [benphelps/homepage#1098]
### Description

Every widget on every service shows me this error. 
"API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

This happens for ALL widgets. 

![image](https://user-images.githubusercontent.com/55252063/224549296-5eb77d89-1781-4823-b37b-76892727ba18.png)

### Steps to reproduce

1. Add a service
2. Add the service widgets (e.g. for Grafana the Grafana widget).
3. Fill out the service widget information
4. ??

### homepage version

v0.6.10

### Installation method

Docker

### Configuration

```yaml
- Grafana:
        icon: grafana
        description: Grafana Dashboard
        server: my-docker
        container: grafana
        widget:
            type: grafana
            url: http://iphere:3001
            username: uerhere
            password: passwordhere

  - Prometheus:
        icon: prometheus
        description: Prometheus
        server: my-docker
        container: prometheus
        widget:
            type: prometheus
            url: http://iphere:9090
```

### Container Logs

Listening on port 3000

### Other

Homepage is deployed via nginx reverse proxy

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
