### ISSUE TITLE
[Bug] Settings layout accent error...

### ISSUE THREAD

**Issue by juanmanuelbc** [benphelps/homepage#1104]
### Description

When using accents for setting "Category Icons" under the `layout` setting, neither the icon is displayed nor the order is not respected...
![imatge](https://user-images.githubusercontent.com/13131391/224724429-cb3625a3-6ddb-478c-a571-0266373984cc.png)

### Steps to reproduce

`settings.yaml`
```yaml
layout:
    Virtualización:
        icon: mdi-vpn
    Seguridad:
        icon: mdi-security
    Herramientas:
        icon: mdi-tools
```

`services.yaml`
```yaml
- Virtualización:
    - ...
- Seguridad:
    - ...
- Herramientas:
    - ...
```

### homepage version

v0.6.10 (af2566c, 28 feb 2023)

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Can't reproduce this, I assume you have an issue in your configs somewhere.

<img width="339" alt="Screenshot 2023-03-13 at 2 57 59 PM" src="https://user-images.githubusercontent.com/4887959/224841354-b341ecc8-bb01-4d21-b9ef-e5cc42f1d607.png">

services.yaml
```yaml
- Virtualización:
     - VPN:
        icon: wireguard.png
        description: Just an example VPN
```

settings.yaml
```yaml
layout:
  ...
  Virtualización:
    icon: mdi-vpn
    style: row
    columns: 3
```

Let us know if you figure it out / have more info...
