### ISSUE TITLE
[Bug] no status light

### ISSUE THREAD

**Issue by luweijun1992** [benphelps/homepage#1157]
### Description

no status light

### Steps to reproduce

no status light

### homepage version

v0.6.10

### Installation method

Docker

### Configuration

```yaml
- Portainer:
        icon: portainer.png
        href: https://192.168.248.10:9443
        description: The analytics platform for all your metrics
        server: my-docker
        container: portainer
        widget:
            type: portainer
            url: https://192.168.248.10:9443
            env: 2
            key: password

---

my-docker:
    socket: /var/run/docker.sock
```

### Other

I have been unable to see the status light.
![image](https://user-images.githubusercontent.com/58923704/228484690-563e5f6e-0a8f-42c3-9cd3-2d943f95cd11.png)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
