### ISSUE TITLE
[Feature Request] containerd API

### ISSUE THREAD

**Issue by doc-jay** [benphelps/homepage#117]
Hello,

   I'm running Rocky Linus 8.6 and containerd for docker.  It creates a .sock file at /run/containerd/containerd.sock

containerd uses a grpc API, which it's different than docker's remote API

https://github.com/containerd/containerd/blob/master/RELEASES.md#grpc-api

Might be a big ask, but are there any plans on integrating the containerd API?

Thank you

**Comment by benphelps** [comment]
I'm not familiar with containerd, but I don't see why we couldn't have some kind of integration / support.

It might be possible if we define the options as something like this:

```yaml
- Emby:
    icon: emby.png
    href: http://emby.media.home/
    description: Media server
    serverd: my-containerd
    containerd: emby
```

That way we have a way to differentiate between the two.

I would have to check the API more closely to see if it can mirror the Docker support or not.
