### ISSUE TITLE
[Bug] v0.6.11: Glances cputemp widget option not working

### ISSUE THREAD

**Issue by alexdelprete** [benphelps/homepage#1171]
### Description

The new cputemp option for 0.6.11 is not working for me (Glances v3.3.1.1 with PsUtil v5.9.0) on any of the 4 servers I configured it (note: uptime is working fine). In the below screenshot, I only enabled it on the first server.

![image](https://user-images.githubusercontent.com/7027842/229665826-74a8f6a5-71ef-4213-9a56-25c1277f7eac.png)

From what I understood from the code, the sensors API is called to get data. So here's the output when I call the endpoint manually:

```json
[
    {
        "label": "acpitz 1",
        "unit": "C",
        "value": 27,
        "warning": 119,
        "critical": 119,
        "type": "temperature_core",
        "key": "label"
    },
    {
        "label": "acpitz 2",
        "unit": "C",
        "value": 29,
        "warning": 119,
        "critical": 119,
        "type": "temperature_core",
        "key": "label"
    },
    {
        "label": "Composite",
        "unit": "C",
        "value": 45,
        "warning": 74,
        "critical": 79,
        "type": "temperature_core",
        "key": "label"
    },
    {
        "label": "Package id 0",
        "unit": "C",
        "value": 72,
        "warning": 84,
        "critical": 100,
        "type": "temperature_core",
        "key": "label"
    },
    {
        "label": "Core 0",
        "unit": "C",
        "value": 72,
        "warning": 84,
        "critical": 100,
        "type": "temperature_core",
        "key": "label"
    },
    {
        "label": "Core 1",
        "unit": "C",
        "value": 63,
        "warning": 84,
        "critical": 100,
        "type": "temperature_core",
        "key": "label"
    },
    {
        "label": "Core 2",
        "unit": "C",
        "value": 62,
        "warning": 84,
        "critical": 100,
        "type": "temperature_core",
        "key": "label"
    },
    {
        "label": "Core 3",
        "unit": "C",
        "value": 62,
        "warning": 84,
        "critical": 100,
        "type": "temperature_core",
        "key": "label"
    }
]
```

### Steps to reproduce

install Glances v3.3.1.1 with PsUtil v5.9.0
configure homepage widgets

### homepage version

v0.6.11

### Installation method

Docker

### Configuration

```yaml
- glances:
    url: http://pve1.axel.dom:61208
    label: PVE 1
    cputemp: true
    uptime: true

- glances:
    url: http://pve2.axel.dom:61208
    label: PVE 2
    cputemp: false
    uptime: true

- glances:
    url: http://docker.axel.dom:61208
    label: Docker 1
    cputemp: false
    uptime: true

- glances:
    url: http://docker2.axel.dom:61208
    label: Docker 2
    cputemp: false
    uptime: true

- glances:
    url: http://pbs.axel.dom:61208
    label: PBS
    cputemp: false
    uptime: true
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
