### ISSUE TITLE
[Bug] Services loading very slowly

### ISSUE THREAD

**Issue by JordyEGNL** [benphelps/homepage#1176]
### Description

Homepage doesnt show services on first launch, it takes around 60-120 seconds to load. The services are also not using the configuration from settings.yaml
![image](https://user-images.githubusercontent.com/65036298/229731285-c5564f3a-34f7-4492-a657-7f8a8dbf37be.png)

When it happens:
- Most of the time

How I load the site:
- Over Tailscale VPN
- To Traefik container
- To Homepage container

All the services are loading via labels
```yaml
    labels:
      # Homepage config
      homepage.group: Applications
      homepage.name: Jellyfin
      homepage.icon: jellyfin.png
      homepage.href: https://jellyfin.domain.tld/
```

settings.yaml
```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: [REDACTED]
  weatherapi: weatherapiapikey

title: Dashboard
background: /images/wallpaper.png
base: https://home.domain.tld
backgroundOpacity: 0.15
color: zinc
target: _self
headerStyle: boxed
quicklaunch:
    searchDescriptions: true

layout: 
  Management:
    style: row
    columns: 5
    icon: mdi-server
  Applications:
    style: row
    columns: 4
    icon: mdi-server
  Monitoring:
    style: column
  Networking:
    style: column
```

services.yml
```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services 

- Management:
    - Proxmox:
        href: [REDACTED]
        description: Hypervisor
        icon: proxmox.png
        ping: [REDACTED]
        widget:
          type: proxmox
          url: [REDACTED]
          username: [REDACTED]
          password: [REDACTED]
etc...
```

![image](https://user-images.githubusercontent.com/65036298/229731475-62deadff-dd4f-41cd-ac38-9c5fd3470a62.png)

After 2 minutes I got this as result, but it is not organised as it should be, as seen in the settings.yaml. It sometimes works perfectly fine but most of the time it does this.
![image](https://user-images.githubusercontent.com/65036298/229733019-230dd0dd-ef4a-4778-9645-8ce4f48c3eed.png)

### Steps to reproduce

As described in the description. If you need more tell me :)

### homepage version

v0.6.12 (88089a8)

### Installation method

Docker

### Container Logs

Logs are set to debug but only "listening on port 3000"

### Browser Logs

![image](https://user-images.githubusercontent.com/65036298/229733527-8ffb4f6d-df9b-441b-acd7-ca8f3e3558cb.png)
This could be relevant

### Other

What I have tried:
- Incognito mode
- Chrome, Edge and Firefox
- Cleared cookies
- Restarting container
- Changed PUID and PGID to 1000 (owner of files)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
