### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MeJIuFaRo** [benphelps/homepage#1183]
### Description

widget mikrotik is not work
i have ros 7.8:stable in mikrotik hap ac3
and "homepage" out API Error: Invalid data

![image](https://user-images.githubusercontent.com/92914144/229947902-8e5f3bde-26ba-4d03-8245-0b166e59c678.png)

### Steps to reproduce

on mikrotik:
ros 7.8:stable

in terminal
```
/ip service
set www-ssl certificate=certificate_name disabled=no
```

on homepage docker server:

add widget mikrotik

### homepage version

v0.6.13 (4818060)

### Installation method

Docker

### Configuration

```yaml
file: services.yaml

- Services:
   - Mikrotik:
        icon: mikrotik.png
        href: https://192.168.88.1
        widget:
          type: mikrotik
          url: https://192.168.88.1
          username: read-only-user
          password: pass123
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
