### ISSUE TITLE
[Bug] error with qBittorrent api

### ISSUE THREAD

**Issue by PedroBuffon** [benphelps/homepage#1188]
### Description

I have ssl on my qBittorrent and the widget on homepage keep giving me these errors

[2023-04-05T11:40:34.180Z] error: <httpProxy> Error calling https://10.0.0.2/api/v2/torrents/info...
[2023-04-05T11:40:34.181Z] error: <httpProxy> [
  500,
  Error: Client network socket disconnected before secure TLS connection was established
      at connResetException (node:internal/errors:717:14)
      at TLSSocket.onConnectEnd (node:_tls_wrap:1595:19)
      at TLSSocket.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET',
    path: null,
    host: '10.0.0.2',
    port: 2081,
    localAddress: undefined
  }
]
[2023-04-05T11:40:34.183Z] error: <qbittorrentProxyHandler> HTTP 500 getting data from qBittorrent.  Data: { error: [Object] }
[2023-04-05T11:40:35.194Z] error: undefined

### Steps to reproduce

idk now how to reproduce, i just configure the widget correctly and it gives me the error

### homepage version

v0.6.14

### Installation method

Docker

### Configuration

```yaml
- qBittorrent:
        icon: qbittorrent.png
        href: https://hostname via cloudflare tunnel
        description: Torrents Downloader
        server: my-docker
        container: qbittorrent
        widget:
          type: qbittorrent
          url: https://10.0.0.2:2081
          username: admin
          password: c@n3ct@pc
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
