### ISSUE TITLE
[Bug?] A couple of issues

### ISSUE THREAD

**Issue by LilTrublMakr** [benphelps/homepage#124]
I am trying this dashboard out and wanted to see if I am doing something wrong, these are a bug, or if these are intended.

1. I am not able to use icons. I have `/app/public/icons` mounted in docker and have tried using both `/images/example.png` and `example.png` and neither one are working as they say they should in the [wiki](https://github.com/benphelps/homepage/wiki/Services#icons)
2. The Services are not clickable. 

Here is my configuration:
```markdown
- // Media:
  - Sonarr:
    - icon: /icons/sonarr.png
      href: http://sonarr.sudo/
      description: TV Series Management
  - Radarr:
    - icon: radarr.png
      href: http://radarr.sudo/
      description: Movie Management
- // Home Management:
  - Cisco Mobility Express:
    - icon: cisco-logo.png
      href: http://192.168.35.10
      description: AP Management
- // Tools:
  - Bitwarden:
    - href: https://[redacted]
- // Downloaders:
  - Deluge:
    - href: http://tower.sudo:8112/
```

I am running build 0.3.18.

Otherwise, I think this is a dashboard I will actually stick with! I have a request but I will put that in a different topic.

**Comment by benphelps** [comment]
> I am not able to use icons. I have /app/public/icons mounted in docker and have tried using both /images/example.png and example.png and neither one are working as they say they should in the [wiki](https://github.com/benphelps/homepage/wiki/Services#icons)

For newly added images to load, you have to restart the container (this is a limitation of Next.js).

>The Services are not clickable.

You've got some problems in your config, the service level is not an array, and should be an object, like this:

```yaml
- // Media:
  - Sonarr:
    icon: /icons/sonarr.png
    href: http://sonarr.sudo/
    description: TV Series Management
```

**Comment by LilTrublMakr** [comment]
> For newly added images to load, you have to restart the container (this is a limitation of Next.js).

Container has been restarted and images are still not loading. I have also tried clearing browser cache. Is there an internal command I can try running to get them to show up?

> the service level is not an array, and should be an object, like this:

Changed and unfortunately still not clickable. Here are my services.yaml currently (bookmarks is in OP):

Services:
```yaml
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Media:
  - Sonarr:
    icon: /icons/sonarr.png
    href: http://sonarr.sudo/
    description: TV Series Management
  - Radarr:
    icon: /icons/radarr.png
    href: http://radarr.sudo/
    description: Movie Management
```
