### ISSUE TITLE
[Bug] Glances and CPUTemp on Ryzen HW

### ISSUE THREAD

**Issue by thehijacker** [benphelps/homepage#1375]
### Description

CPU temperature is currently not displayed using Glances with cputemp set to true. HW is Ryzen 5. Glances under sensors detects:

![image](https://user-images.githubusercontent.com/13857043/232776461-0f4e9fdb-b029-4ff6-b180-9241fafcce22.png)

Api call /api/3/sensors shows it the same as on GUI:

```
[
   {
      "critical": 84,
      "key": "label",
      "label": "Composite",
      "type": "temperature_core",
      "unit": "C",
      "value": 53,
      "warning": 82
   },
   {
      "critical": null,
      "key": "label",
      "label": "Tctl",
      "type": "temperature_core",
      "unit": "C",
      "value": 68,
      "warning": null
   },
   {
      "critical": null,
      "key": "label",
      "label": "edge",
      "type": "temperature_core",
      "unit": "C",
      "value": 58,
      "warning": null
   }
]
```

Can you also support this?

Thank you.

### Steps to reproduce

```
- glances:
    url: http://192.168.28.70:61208
    cputemp: true
    uptime: true
```

### homepage version

v0.6.16 (0ae13d8, Apr 8, 2023)

### Installation method

Docker

### Configuration

```yaml
- glances:
    url: http://192.168.28.70:61208
    cputemp: true
    uptime: true
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
