### ISSUE TITLE
[Bug] Icons that are taller than 32px are not forced into a 32x32 area

### ISSUE THREAD

**Issue by ervwalter** [benphelps/homepage#1404]
### Description

Currently, if you reference an icon from dashboard icons that is not square and is taller than 32px, it will be rendered as taller than other icons on the dashboard.  I gather from the implementation of how SVG icons are presented that the intention is for them to fit within a 32x32 area.

This code uses the next/image component to do the rendering of the icon and although fixed height and width props of 32px are passed to the component, it does not internally force the icon to fit within a 32x32 square (at least not in the version of Next.js that is currently in use; I believe the next/image component changes significantly in 13.0+.

The fix, I believe is some additional CSS to indicate that the maximum size of the icon should be 32x32 with object-fit to ensure it is contained in that area and not stretched.  PR incoming...

For example:
![example image](https://i.imgur.com/2ItkB5m.png)

### Steps to reproduce

This config below will demonstrate the issue (with the icons in dashboardicons as of 4/23/23).

### homepage version

v0.6.16

### Installation method

Docker

### Configuration

```yaml
- My First Group:
    - Service with square icon:
        href: http://localhost/
        icon: nextcloud
        description: The nextcloud icon is square
    - Service with non-square icon:
        href: http://localhost/
        icon: minio
        description: The minio icon is taller than 32px
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
