### ISSUE TITLE
[Bug] Ping Should Accept HTTP 204 (No Content)

### ISSUE THREAD

**Issue by arazilsongweaver** [benphelps/homepage#1411]
### Description

Authentik's internal health monitoring uses HTTP status code 204 (no content) to report normal system operations. Homepage's "service ping" function does not accept HTTP 204 as a valid response. This is similar to the issue resolved by commit [6d1db78](https://github.com/benphelps/homepage/commit/6d1db787093e8f6fd2abd45c80246cdac6ccd803).

### Steps to reproduce

1. Add Authentik to services.yml using the cofiguration below.
2. Ping status will state "204" in red while Authentik is in normal operations mode.

### homepage version

v0.6.16 (0ae13d8, Apr 8, 2023)

### Installation method

Docker

### Configuration

```yaml
- Example.net SSO:
      href: https://sso.example.net/
      ping: https://sso.example.net/-/health/ready/
      icon: authentik.png
      description: Single sign on services
      container: authentik-server-1
      widget:
        type: authentik
        url: https://sso.example.net
        key: secret
```

### Container Logs

N/A

### Browser Logs

N/A

### Other

- Authentik Documentation: https://goauthentik.io/docs/installation/monitoring
- HTTP 204 Documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
