### ISSUE TITLE
[Bug] kubernetes-widget HTTP request failed

### ISSUE THREAD

**Issue by roiterorh** [benphelps/homepage#1415]
### Description

kubernetes-widget fails
![shot](https://user-images.githubusercontent.com/44670241/234618707-4a228081-da1b-4b8f-9e0c-81231de19c54.png)

### Steps to reproduce

1- minikube start
2-  helm upgrade --install homepage jameswynn/homepage -f values/homepage.yaml  -n homepage  --create-namespace
3-  kubectl port-forward -n homepage services/homepage 3000

### homepage version

0.6.16

### Installation method

Other (please describe above)

### Configuration

```yaml
#values/homepage.yaml
enableRbac: true
serviceAccount:
  create: true
image:
  repository: ghcr.io/benphelps/homepage
  tag: v0.6.16
config:
  settings:
    title: My Awesome Homepage
    backgroundOpacity: 0.5
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    color: slate
    theme: dark 
    hideVersion: true

  bookmarks: []
  services: []
  widgets:
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
    - openmeteo:
        units: metric 
        cache: 5 
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    mode: cluster
```

### Container Logs

/app/config/logs/homepage.log

[2023-04-26T15:00:14.958Z] error: <kubernetes-widget> exception HttpError: HTTP request failed
    at Request._callback (/app/node_modules/.pnpm/@kubernetes+client-node@0.17.1/node_modules/@kubernetes/client-node/dist/metrics.js:48:32)
    at self.callback (/app/node_modules/.pnpm/request@2.88.2/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/app/node_modules/.pnpm/request@2.88.2/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/app/node_modules/.pnpm/request@2.88.2/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  response: [IncomingMessage],
  body: '404 page not found\n',
  statusCode: 404
}

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
