### ISSUE TITLE
[Bug] the portainer widged seems not working

### ISSUE THREAD

**Issue by pippo73** [benphelps/homepage#1427]
### Description

when an image is better the 1000 words ;-)
![image](https://user-images.githubusercontent.com/757121/234989576-f093b23d-1ca8-4c1f-8438-ef442b341f1f.png)

### Steps to reproduce

running homepage from a portainer docker
Here is the stack:
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/user/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID
      PGID: $PGID
```

### homepage version

 v0.6.16

### Installation method

Docker

### Configuration

```yaml
and here is the the part of the **services.yaml**


    - Portainer:
        href: http://192.168.1.91:9000/
        description: Portainer
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
        widget:
            type: portainer
            url: http://192.168.1.91:9000
            env: 1
            key: ptr_myaccesskey
```
```


### Container Logs

```
[2023-04-27T20:50:55.606Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.1.91:9000/api/endpoints/2/docker/containers/json?all=1
[2023-04-27T20:51:18.791Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.1.91:9000/api/endpoints/2/docker/containers/json?all=1
[2023-04-27T20:51:34.168Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.1.91:9000/api/endpoints/1/docker/containers/json?all=1
[2023-04-27T20:52:00.241Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.1.91:9000/api/endpoints/1/docker/containers/json?all=1
[2023-04-27T21:10:27.418Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.1.91:9000/api/endpoints/1/docker/containers/json?all=1
```

### Browser Logs

```
Something went wrong.
TypeError: c.filter is not a function

    at l (http://192.168.1.241:3000/_next/static/chunks/7528.c60b924a2aff4b5c.js:1:1104)
    at h (http://192.168.1.241:3000/_next/static/chunks/4121-c10f39ad3208a3b4.js:1:12201)
    at n (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:10214)
    at G (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:20429)
    at div
    at li
    at R (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:23475)
    at ul
    at O (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:27082)
    at div
    at D (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:27369)
    at div
    at div
    at re (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:41093)
    at n (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:10214)
    at http://192.168.1.241:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88962
    at te (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:39147)
    at div
    at div
    at ie (http://192.168.1.241:3000/_next/static/chunks/pages/index-e84753d2b515ddb8.js:1:44963)
    at a (http://192.168.1.241:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15091)
    at s (http://192.168.1.241:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15649)
    at u (http://192.168.1.241:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:14524)
    at http://192.168.1.241:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88962
    at http://192.168.1.241:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:13805
    at l (http://192.168.1.241:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:1462)
    at n (http://192.168.1.241:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:6033)
    at r (http://192.168.1.241:3000/_next/static/chunks/main-28f0bf55ce641aab.js:1:6946)
    at Y (http://192.168.1.241:3000/_next/static/chunks/main-28f0bf55ce641aab.js:1:9186)
    at ie (http://192.168.1.241:3000/_next/static/chunks/main-28f0bf55ce641aab.js:1:11826)
```

http://192.168.1.241 this is the ip of the homepage server


### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
