### ISSUE TITLE
[Bug] Gotify widget - missing

### ISSUE THREAD

**Issue by philhagger** [benphelps/homepage#143]
![gotify-missing](https://user-images.githubusercontent.com/739206/189875981-f89d2de3-7a70-4fd9-93ad-acb9faf4f5b1.png)

I have added the Gotify widget according to the Wiki and it shows as missing type

**Comment by xicopitz** [comment]
Hi,

Did you add a key to the widget configuration? It should be something like:

```
widget:
  type: gotify
  url: http://gotify.host.or.ip
  key: clienttoken
```
where the key is token from an existing or new client that you can find in your gotify admin page.

#121

**Comment by benphelps** [comment]
There hasn't been a `latest` tag release since the merge happened.  I'll do that now.

**Comment by Nonoss117** [comment]
Hi,

I confirm, after reading your post : [ https://github.com/benphelps/homepage/pull/121]( https://github.com/benphelps/homepage/pull/121)

Everything works fine:
![image](https://user-images.githubusercontent.com/79055577/189888660-bf39a9cd-4dc9-458a-b1ad-9d3923797d7b.png)

**Comment by xicopitz** [comment]
Happy to help.
Feedback is welcome too :)

@benphelps wiki is outdated. It should be something like:

```yaml
## Gotify

Get a Gotify client token from an existing client or create a new one on your Gotify admin page

widget:
  type: gotify
  url: http://gotify.host.or.ip
  key: clientoken
```
