### ISSUE TITLE
[Bug] Duplicate Service (jellyfin)

### ISSUE THREAD

**Issue by travisboss** [benphelps/homepage#1439]
### Description

See duplicates of Jellyfin service, I am checking the health of the container using the dockerproxy suggested in the wiki and once I have started this I now see a duplicate, once is the url through my reverse proxy with the widget info (the one I setup), and the second is the local IP:Port with no widget info (I did not set up).

https://imgur.com/a/LzmXrop

### Steps to reproduce

1. Created dockerproxy container
2. Add server and container info to services.yaml
3. See duplicate on homepage

### homepage version

unsure but is latest

### Installation method

Docker

### Configuration

```yaml
- Jellyfin:
        icon: jellyfin.png
        href: [redacted]
        server: nas-server
        container: jellyfin
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: [redacted]
            fields: ["movies", "series", "episodes"]
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: false # optional, defaults to true
```

### Container Logs

There were no logs pertaining to this that I can see.

### Browser Logs

No browser logs

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
