### ISSUE TITLE
[Bug] Settings file not being respected?

### ISSUE THREAD

**Issue by KyleTryon** [benphelps/homepage#1446]
### Description

It appears as though the `settings.yaml` file in my scenario may not be respected, though it is loaded. The setting.yaml file exists within the config folder but it's settings are not reflected, while those of widges.yaml and others _are_.

### Steps to reproduce

 I am running a custom helm chart.

Here is the relevant part of the generated template:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    
    title: "Homepage | ${DOMAIN_NAME}"
    
  bookmarks.yaml: |
    
    - Social:
        - HackerNews:
            - icon: mdi-alpha-y-box
              href: https://news.ycombinator.com/
```

In this example, the bookmarks section as shown in this example _does_ correctly display on the page, but seemingly nothing from the `settings.yaml` is being respected as far as I can tell, it may have to do with the syntax but I believe it is correct based on what I see in the docs and the fact that bookmarks is working.

If I exec into the pod and check the settings config I see this:

```sh
/app # cat /app/config/settings.yaml 

title: "Homepage | x.com"
```

However, in the application we can see the title is unchanged: 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/33272306/235574017-2c4c1ca8-2bbb-4c0f-9d74-ca7bd43d0c50.png">

This is true of any setting change I make to the `settings.yaml` file currently, including layout.

### homepage version

a798c02153df67633b2ac023f5173b1761ac8e3e0cd562eb1e6d62ee4ecf73df

### Installation method

Other (please describe above)

### Container Logs

No errors

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
