### ISSUE TITLE
[Bug] Search widget always defaults to DuckDuckGo

### ISSUE THREAD

**Issue by KyleTryon** [benphelps/homepage#1447]
### Description

Even while configuring 'google' as my search provider, the search bar widget would show the _DuckDuckGo icon_ and search via the DDG provider. However, if I instead start typing immediately without focusing on the search widget, a floating search bar would appear and properly work with Google.

<img width="51" alt="image" src="https://user-images.githubusercontent.com/33272306/235574874-d85051e9-063f-4f4a-a42a-2ddc01e1f2b9.png">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/33272306/235574753-b1a523ad-4938-4f85-a741-0b02fe9414bb.png">

This is configured via custom helmchart

### Steps to reproduce

1. Configure a provider such as google. The result will be the described above.

```yaml
    - search:
        provider: google
        set_focus: true
        target: _blank
```

**Workaround!**

By passing multiple providers, including DuckDuckGo, there was now a dropdown on the homepage that allowed me to select Google and this selection persists.

```yaml
    - search:
        provider: [google, duckduckgo]
        set_focus: true
        target: _blank
```
<img width="106" alt="image" src="https://user-images.githubusercontent.com/33272306/235575105-b89a9cbe-b9ab-48f2-b44e-190f533eed21.png">

### homepage version

a798c02153df67633b2ac023f5173b1761ac8e3e0cd562eb1e6d62ee4ecf73df

### Installation method

Other (please describe above)

### Configuration

```yaml
This is the rendered helm template widget section.


  widgets.yaml: |
    
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        set_focus: true
        target: _blank
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
