### ISSUE TITLE
[Bug] Swarm mode & Automatic Service Discovery - No containers were found with homepage labels

### ISSUE THREAD

**Issue by sebgeekinside** [benphelps/homepage#1494]
### Description

Hompepage does not display Services based using the Automatic Service Discovery configuration (i.e. configuration of "homepage" docker labels into docker-compose service definition) combined to Swarm mode.
As logged, "no containers were found with homepage labels" whereas "homepage" docker labels are defined into docker-compose service definition.

Several issues/discussions already deal with the problem but unfortunately, most of them are tagged "cant reproduce" without any usefull explanation to solve it.

As mention into the "Configuration" section, I have tested several configurations in order to try to find the correct one that work but I did not to succeed in.

Please don't bypass the issue with just a tag "cant reproduce" and saying that "it is a configuration of the personal setup".
If the root causse can be an mistake of the personal setup, please give us more explanation.
How do you explain all the issues/discussions that are stuck due to this problem ?

### Steps to reproduce

See the "Configuration" section.

### homepage version

v0.6.17 (f692e71, May 1, 2023)

### Installation method

Docker

### Configuration

```yaml
Tests with the 2 following Docker environnements (Linux):
Swarm mode - Docker version 23.0.3, build 3e7cbfd
Swarm mode - Docker version 20.10.14, build a224086

Here an example of my configuration of "homepage" docker labels into docker-compose service definition:
...
deploy:
  mode: replicated
  replicas: 1
  placement:
    constraints:
    - node.role == manager
  labels: 
  - homepage.group=My First Group
  - homepage.name=Portainer
  - homepage.icon=portainer.png
  - homepage.href=https://portainer.mydomain.com/
...


Here the several configurations I have tested using the 2 Docker environnements mentioned:

- homepage service with no PUID and PGID defined and using the Docker socket (i.e. binding volume /var/run/docker.sock and docker.yaml configuration defining socket: /var/run/docker.sock and swarm: true parameters),

- homepage service with no PUID and PGID defined and using the Docker Socket Proxy (i.e. binding volume /var/run/docker.sock and defining SWARM=1 environnement parameter for Docker Socket Proxy and docker.yaml configuration defining host, port and swarm: true parameters),

- homepage service defining a specific PUID and PGID and using the Docker socket (i.e. binding volume /var/run/docker.sock and docker.yaml configuration defining socket: /var/run/docker.sock and swarm: true parameters),

- homepage service defining a specific PUID and PGID and using the Docker Socket Proxy (i.e. binding volume /var/run/docker.sock and defining SWARM=1 environnement for Docker Socket Proxy and docker.yaml configuration defining host, port and swarm: true parameters).


I have also try older versions of the image ghcr.io/benphelps/homepage.
```

### Container Logs

- No error into the Docker Socket Proxy log: dockerfrontend dockerbackend/dockersocket 0/0/0/37/39 200 50992 - - ---- 1/1/0/0/0 0/0 "GET /containers/json?all=true HTTP/1.1"

- Message into the homepage service log: debug: No containers were found with homepage labels.

### Troubleshooting

N.A.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
