### ISSUE TITLE
Octoprint Widget error when printer offline

### ISSUE THREAD

**Issue by Tiepolino** [benphelps/homepage#1500]
### Description

When the printer is offline the Octoprint Widget shows an error:
API error: HTTP Error
When I connect to the API directly with my browser I get this in return: {"error":"Printer is not operational"}
It would be nice to show something like 'Printer is offline' in stead of an error message.
As soon as I turn on the printer the correct data is shown in the Widget.

### Steps to reproduce

Setup the Widget, but keep the printer turned off. An error is shown in the Widget
Turn on the priner and the correct info will be shown.

### homepage version

f692e71

### Installation method

Docker

### Configuration

```yaml
- OctoPrint:
        href: https://octoprint.brugakker.lan
        icon: octoprint
        ping: https://octoprint.brugakker.lan
        widget:
            type: octoprint
            url: https://octoprint.brugakker.lan:443
            key: A93B441064614D4D93D181BAE2DB****
```

### Troubleshooting

Not a real bug, but my printer is off most of the time. This shows the annoying error all the time.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
