### ISSUE TITLE
[Bug] OctoPrint widget returns and error if the printer is offline

### ISSUE THREAD

**Issue by Ulrar** [benphelps/homepage#1504]
### Description

The widget displays an API error if the printer is disconnected, even though the API does work fine.
It does not log the error, it's only shown in the UI in red.

### Steps to reproduce

1. Install Octoprint, but not a printer (or disconnect it)
2. Use the widget

### homepage version

v0.6.17 (f692e71, May 1, 2023)

### Installation method

Docker

### Configuration

```yaml
- OctoPrint:
        icon: octoprint
        server: ...
        container: OctoPrint
        widget:
          type: octoprint
          url: http://...:5000
          key: ...
```
```


### Container Logs

No logs

### Browser Logs

409 conflict

### Troubleshooting

The API returns : `{"error":"Printer is not operational"}`

### Other

IMHO that special case could be handled and the widget could simply not appear, or just say printer offline or something more relevant.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
