### ISSUE TITLE
[Bug] background blur isn’t full height

### ISSUE THREAD

**Issue by Hiccup90** [benphelps/homepage#1524]
### Description

![homepage](https://github.com/benphelps/homepage/assets/24733459/a0af2521-d54c-4f4a-a2d4-ea5a3e6d297f)

As shown in the image, the bottom section is not blurred. However, this may be due to having fewer components in my setup.

### Steps to reproduce

No need to reproduce, it has been consistently present.

### homepage version

v0.6.20

### Installation method

Unraid

### Configuration

```yaml
background: 
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: md # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  #opacity: 50 # 0-100
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
