### ISSUE TITLE
Dynamically discovered services do not support HOMEPAGE_FILE_XXX

### ISSUE THREAD

**Issue by mscreations** [benphelps/homepage#1553]
### Description

As far as I can tell, when you have dynamically discovered services that have HOMEPAGE_FILE_XXX in one of the variables, this does not get expanded or used properly. As an example, my docker compose has these services:

```
---
version: "3.9"

secrets:
  sonarrapikey:
    file: ./secrets/sonarrapikey

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.href=https://sonarr.example.com
      - homepage.icon=sonarr.png
      - homepage.ping=http://sonarr:8989
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key={{HOMEPAGE_FILE_SONARR_API_KEY}}
    volumes:
      - /config/sonarr:/config
    ports:
      - 8989:8989

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - /config/homepage:/app/config
    environment:
      HOMEPAGE_FILE_SONARR_API_KEY: /run/secrets/sonarrapikey
    secrets:
      - sonarrapikey

```

When sonarr starts up, I see homepage trying to make api calls with an api key of {{HOMEPAGE_FILE_SONARR_API_KEY}}. Attaching to the homepage container, I verified there is an environment variable called HOMEPAGE_FILE_SONARR_API_KEY that has /run/secrets/sonarrapikey. If I `cat` that file, I get my api key as expected. If I instead move the dynamic configuration for homepage to the services.yaml like:

```
- Media:
    - Sonarr:
        href: https://sonarr.example.com
        icon: sonarr.png
        ping: http://sonarr:8989
        widget:
            type: sonarr
            url: http://sonarr:8989
            key: {{HOMEPAGE_FILE_SONARR_API_KEY}}
```

Everything works as expected.

### Steps to reproduce

Set up docker secret file for api key. 
Make sure secret is loaded into homepage docker container
Set up dynamic discovery for another service and include the secret name. Won't work without it being in services.yaml.

### homepage version

0.6.20

### Installation method

Docker

### Configuration

```yaml
Provided above
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
