### ISSUE TITLE
[Bug] Can't connect to Portainer

### ISSUE THREAD

**Issue by mariopaolo** [benphelps/homepage#1558]
### Description

I am trying to connect my Homepage instance to Portainer CE and I am hitting the following error in the UI.
![Homepage error for Portainer in the UI](https://i.imgur.com/STuISpA.png)
```
Something went wrong.
TypeError: c.filter is not a function

s@https://home.mydomain.com/_next/static/chunks/7528.8c620933c86595a9.js:1:1102
9571/g/h<@https://home.mydomain.com/_next/static/chunks/4121-c10f39ad3208a3b4.js:1:12201
n@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:11014
G@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:22318
div
li
R@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:25313
ul
I@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:28920
div
O@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:29283
div
div
re@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:43143
n@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:11014
6747/Y<@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88960
te@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:41197
div
div
div
ie@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:47091
a@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15089
s@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15647
u@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:14522
6747/Y<@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88960
4384/t.default<@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:13803
l@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:1460
n@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:6031
r@https://home.mydomain.com/_next/static/chunks/main-28f0bf55ce641aab.js:1:6947
Y@https://home.mydomain.com/_next/static/chunks/main-28f0bf55ce641aab.js:1:9184
ie@https://home.mydomain.com/_next/static/chunks/main-28f0bf55ce641aab.js:1:11824
```
Before opening the issue I made sure to have a correct API token and that my environment is correct (`1` in my case).
I already read [this issue](https://github.com/benphelps/homepage/issues/1427) but I could not find a solution for my problem.

I also tried running the command found in [Troubleshooting](https://gethomepage.dev/en/more/troubleshooting/):
```
curl -L -k -H 'X-Api-Key:MYAPIKEY' 'https://portainer.ix-portainer.svc.cluster.local:10400/api/endpoints/1/docker/containers/json'
```
but I always get
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:ix-portainer:portainer\" cannot get path \"/containers/json\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

After some digging, I found that when I try to hit `/api/endpoints/1`
```
curl -L -k -H 'X-Api-Key:MYAPIKEY' 'https://portainer.ix-portainer.svc.cluster.local:10400/api/endpoints/1'
```
the response this time is
```
{
    "Id": 1,
    "Name": "local",
    "Type": 5,
    "URL": "https://kubernetes.default.svc",
    "GroupId": 2,
    "PublicURL": "",
    "Gpus": [],
    "TLSConfig": {
        "TLS": true,
        "TLSSkipVerify": true
    },
    "AzureCredentials": {
        "ApplicationID": "",
        "TenantID": "",
        "AuthenticationKey": ""
    },
    "TagIds": [],
    "Status": 1,
    "Snapshots": [],
    "UserAccessPolicies": {},
    "TeamAccessPolicies": {},
    "EdgeKey": "",
    "EdgeCheckinInterval": 0,
    "Kubernetes": {
        "Snapshots": [
            {
                "Time": 1685687961,
                "KubernetesVersion": "v1.25.3+k3s-9afcd6b9-dirty",
                "NodeCount": 1,
                "TotalCPU": 20,
                "TotalMemory": 134817910784
            }
        ],
        "Configuration": {
            "UseLoadBalancer": false,
            "UseServerMetrics": false,
            "EnableResourceOverCommit": false,
            "ResourceOverCommitPercentage": 0,
            "StorageClasses": [
                {
                    "Name": "openebs-zfspv-default",
                    "AccessModes": [
                        "RWO"
                    ],
                    "Provisioner": "zfs.csi.openebs.io",
                    "AllowVolumeExpansion": true
                }
            ],
            "IngressClasses": null,
            "RestrictDefaultNamespace": false,
            "IngressAvailabilityPerNamespace": false,
            "AllowNoneIngressClass": false
        },
        "Flags": {
            "IsServerMetricsDetected": true,
            "IsServerIngressClassDetected": true,
            "IsServerStorageDetected": true
        }
    },
    "ComposeSyntaxMaxVersion": "3.9",
    "SecuritySettings": {
        "allowBindMountsForRegularUsers": true,
        "allowPrivilegedModeForRegularUsers": true,
        "allowVolumeBrowserForRegularUsers": false,
        "allowHostNamespaceForRegularUsers": true,
        "allowDeviceMappingForRegularUsers": true,
        "allowStackManagementForRegularUsers": true,
        "allowContainerCapabilitiesForRegularUsers": true,
        "allowSysctlSettingForRegularUsers": true,
        "enableHostManagementFeatures": false
    },
    "LastCheckInDate": 0,
    "QueryDate": 0,
    "Heartbeat": false,
    "IsEdgeDevice": false,
    "UserTrusted": false,
    "PostInitMigrations": {
        "MigrateIngresses": false,
        "MigrateGPUs": false
    },
    "Edge": {
        "AsyncMode": false,
        "PingInterval": 0,
        "SnapshotInterval": 0,
        "CommandInterval": 0
    },
    "Agent": {
        "Version": ""
    },
    "EnableGPUManagement": false,
    "AuthorizedUsers": null,
    "AuthorizedTeams": null,
    "Tags": null
}
```
I also made sure this endpoint doesn't return when omitting the ApiKey, so in theory my user is able to retrieve information from the API, just not from that endpoint.

You can find my setup information in the `Other` box.

### Steps to reproduce

1. create API key inside Portainer (for the `admin` user)
2. find environment ID
3. add widget section to `services.yml` with correct values
```
        widget:
            type: portainer
            url: https://portainer.ix-portainer.svc.cluster.local:10400
            env: 1
            key: MYAPIKEY
```
4. save `services.yml`
5. refresh Homepage and see error in widget
![Homepage error for Portainer in the UI](https://i.imgur.com/STuISpA.png)

### homepage version

v0.6.20 (6046f79)

### Installation method

Other (please describe above)

### Configuration

```yaml
HOMEPAGE

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "26"
    meta.helm.sh/release-name: homepage
    meta.helm.sh/release-namespace: ix-homepage
  creationTimestamp: 2023-04-15T19:54:29Z
  generation: 26
  labels:
    app: homepage-3.0.19
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.6.20
    helm-revision: "23"
    helm.sh/chart: homepage-3.0.19
    release: homepage
  name: homepage
  namespace: ix-homepage
  uid: bcb7a387-41c7-40e5-901a-81a873dbf3f6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: homepage
      app.kubernetes.io/name: homepage
      pod.name: main
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: 2023-04-15T22:19:12+02:00
        rollme: PJw5m
      creationTimestamp: null
      labels:
        app: homepage-3.0.19
        app.kubernetes.io/instance: homepage
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: homepage
        app.kubernetes.io/version: 0.6.20
        helm-revision: "23"
        helm.sh/chart: homepage-3.0.19
        pod.name: main
        release: homepage
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - --auth
            - none
            - --port
            - "36107"
            - /
          env:
            - name: TZ
              value: Europe/Rome
            - name: UMASK
              value: "0022"
            - name: UMASK_SET
              value: "0022"
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: PUID
              value: "568"
            - name: USER_ID
              value: "568"
            - name: UID
              value: "568"
            - name: PGID
              value: "568"
            - name: GROUP_ID
              value: "568"
            - name: GID
              value: "568"
          image: tccr.io/truecharts/code-server:v4.13.0@sha256:3eae79348586a725993cc26bc71b5ba20736f93e78f735e8c51fa63e75f5fcae
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 36107
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: homepage-codeserver
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 36107
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - SETUID
                - SETGID
                - FOWNER
                - DAC_OVERRIDE
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /
              port: 36107
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/config
              name: config
            - mountPath: /dev/shm
              name: devshm
            - mountPath: /shared
              name: shared
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/logs
              name: varlogs
            - mountPath: /var/run
              name: varrun
        - env:
            - name: TZ
              value: Europe/Rome
            - name: UMASK
              value: "0022"
            - name: UMASK_SET
              value: "0022"
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: S6_READ_ONLY_ROOT
              value: "1"
          image: tccr.io/truecharts/homepage:v0.6.20@sha256:b833a7079cd29406b54b1f63f981564a61ea5d28dad14a61a7008142289d63a0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: homepage
          ports:
            - containerPort: 36107
              name: codeserver
              protocol: TCP
            - containerPort: 3000
              name: main
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/config
              name: config
            - mountPath: /dev/shm
              name: devshm
            - mountPath: /shared
              name: shared
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/logs
              name: varlogs
            - mountPath: /var/run
              name: varrun
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 568
      serviceAccount: homepage
      serviceAccountName: homepage
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-config
        - emptyDir:
            medium: Memory
          name: devshm
        - emptyDir: {}
          name: shared
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: varlogs
        - emptyDir:
            medium: Memory
          name: varrun
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: 2023-04-15T19:54:29Z
      lastUpdateTime: 2023-05-29T05:23:39Z
      message: ReplicaSet "homepage-75866fc76f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: 2023-05-31T01:48:25Z
      lastUpdateTime: 2023-05-31T01:48:25Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 26
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: homepage
    meta.helm.sh/release-namespace: ix-homepage
    metallb.universe.tf/allow-shared-ip: homepage
  creationTimestamp: 2023-04-24T00:24:10Z
  labels:
    app: homepage-3.0.19
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homepage
    app.kubernetes.io/version: 0.6.20
    helm-revision: "23"
    helm.sh/chart: homepage-3.0.19
    release: homepage
    service.name: codeserver
  name: homepage-codeserver
  namespace: ix-homepage
  uid: 7ddd46c9-c3ef-4ee0-a43a-1efa7ed190cf
spec:
  allocateLoadBalancerNodePorts: false
  clusterIP: 172.17.154.227
  clusterIPs:
    - 172.17.154.227
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.1.11
  ports:
    - name: codeserver
      port: 36107
      protocol: TCP
      targetPort: 36107
  selector:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/name: homepage
    pod.name: main
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.1.11


PORTAINER
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: portainer
    meta.helm.sh/release-namespace: ix-portainer
  creationTimestamp: 2023-06-02T06:22:16Z
  generation: 2
  labels:
    app: portainer-4.0.12
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 2.18.3
    helm-revision: "2"
    helm.sh/chart: portainer-4.0.12
    release: portainer
  name: portainer
  namespace: ix-portainer
  uid: 3fa8aed2-9dda-4878-b61d-9ad48d68ac14
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: portainer
      app.kubernetes.io/name: portainer
      pod.name: main
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        rollme: ZCI3I
      creationTimestamp: null
      labels:
        app: portainer-4.0.12
        app.kubernetes.io/instance: portainer
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: portainer
        app.kubernetes.io/version: 2.18.3
        helm-revision: "2"
        helm.sh/chart: portainer-4.0.12
        pod.name: main
        release: portainer
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --tunnel-port=10401
            - --http-disabled
            - --snapshot-interval=5m
          env:
            - name: TZ
              value: Europe/Rome
            - name: UMASK
              value: "0022"
            - name: UMASK_SET
              value: "0022"
            - name: NVIDIA_VISIBLE_DEVICES
              value: void
            - name: S6_READ_ONLY_ROOT
              value: "1"
          image: tccr.io/truecharts/portainer-ce:v2.18.3@sha256:95edb02e81af2d3178367f4a24dde66ef45be786a1dcb8fbb169062c4bf70889
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: portainer
          ports:
            - containerPort: 10401
              name: edge
              protocol: TCP
            - containerPort: 9443
              name: main
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /.cache
              name: cache
            - mountPath: /data
              name: data
            - mountPath: /dev/shm
              name: devshm
            - mountPath: /shared
              name: shared
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/logs
              name: varlogs
            - mountPath: /var/run
              name: varrun
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 568
      serviceAccount: portainer
      serviceAccountName: portainer
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 60
      volumes:
        - emptyDir: {}
          name: cache
        - name: data
          persistentVolumeClaim:
            claimName: portainer-data
        - emptyDir:
            medium: Memory
          name: devshm
        - emptyDir: {}
          name: shared
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: varlogs
        - emptyDir:
            medium: Memory
          name: varrun
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: 2023-06-02T06:24:39Z
      lastUpdateTime: 2023-06-02T06:24:39Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2023-06-02T06:22:16Z
      lastUpdateTime: 2023-06-02T06:24:39Z
      message: ReplicaSet "portainer-554f966659" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: portainer
    meta.helm.sh/release-namespace: ix-portainer
  creationTimestamp: 2023-06-02T06:22:16Z
  labels:
    app: portainer-4.0.12
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: portainer
    app.kubernetes.io/version: 2.18.3
    helm-revision: "2"
    helm.sh/chart: portainer-4.0.12
    release: portainer
    service.name: edge
  name: portainer-edge
  namespace: ix-portainer
  uid: 1d2bfde5-fd10-4356-aab6-9585e1c45c8f
spec:
  clusterIP: 172.17.95.60
  clusterIPs:
    - 172.17.95.60
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: edge
      port: 10401
      protocol: TCP
      targetPort: 10401
  selector:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
    pod.name: main
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

### Container Logs

**HOMEPAGE**
```
[2023-06-02T06:54:01.032Z] error: <credentialedProxyHandler> HTTP Error 403 calling https://portainer.ix-portainer.svc.cluster.local:10400/api/endpoints/1/docker/containers/json?all=1
```

**PORTAINER**
```
2023/06/02 06:24AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:494 > encryption key file not present | filename=portainer
2023/06/02 06:24AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:517 > proceeding without encryption key |
2023/06/02 06:24AM INF github.com/portainer/portainer/api/database/boltdb/db.go:124 > loading PortainerDB | filename=portainer.db
2023/06/02 06:24:20 server: Reverse tunnelling enabled
2023/06/02 06:24:20 server: Fingerprint cc:2c:32:1b:0b:50:c6:6a:31:fb:56:48:29:e8:9f:d3
2023/06/02 06:24:20 server: Listening on 0.0.0.0:10401...
2023/06/02 06:24AM INF github.com/portainer/portainer/api/cmd/portainer/main.go:765 > starting Portainer | build_number=30948 go_version=1.19.4 image_tag=linux-amd64-2.18.3 nodejs_version=18.16.0 version=2.18.3 webpack_version=5.68.0 yarn_version=1.22.19
2023/06/02 06:24AM INF github.com/portainer/portainer/api/http/server.go:342 > starting HTTPS server | bind_address=:9443
2023/06/02 06:25AM INF github.com/portainer/portainer/api/internal/endpointutils/endpointutils.go:186 > attempting to detect storage classes in the cluster |
{"time":1685687240,"message":"http: TLS handshake error from 172.16.13.31:47988: EOF"}
```

### Browser Logs

```GET
https://home.mydomain.com/api/services/proxy?type=portainer&group=Network+Control&service=Portainer&endpoint=docker/containers/json&query={"all":1}
[HTTP/2 403 Forbidden 211ms]

kind | "Status"
apiVersion | "v1"
metadata | Object {  }
status | "Failure"
message | 'forbidden: User "system:serviceaccount:ix-portainer:portainer" cannot get path "/containers/json"'
reason | "Forbidden"
details | Object {  }
code | 403
```

```
TypeError: c.filter is not a function
    NextJS 30
        s
        Eo
        Pu
        xi
        bs
        gs
        vs
        as
        ls
        S
        T
        5568
        f
        2962
        f
        3746
        f
        422
        f
        7851
        f
        2735
        f
        5257
        f
        <anonymous>
        O
        <anonymous>
        a
        <anonymous>
```
```
TypeError: c.filter is not a function
    NextJS 30
 
Object { componentStack: "\ns@https://home.mydomain.com/_next/static/chunks/7528.8c620933c86595a9.js:1:1102\n9571/g/h<@https://home.mydomain.com/_next/static/chunks/4121-c10f39ad3208a3b4.js:1:12201\nn@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:11014\nG@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:22318\ndiv\nli\nR@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:25313\nul\nI@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:28920\ndiv\nO@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:29283\ndiv\ndiv\nre@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:43143\nn@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:11014\n6747/Y<@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88960\nte@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:41197\ndiv\ndiv\ndiv\nie@https://home.mydomain.com/_next/static/chunks/pages/index-e9478753f1558dcd.js:1:47091\na@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15089\ns@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15647\nu@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:14522\n6747/Y<@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88960\n4384/t.default<@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:13803\nl@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:1460\nn@https://home.mydomain.com/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:6031\nr@https://home.mydomain.com/_next/static/chunks/main-28f0bf55ce641aab.js:1:6947\nY@https://home.mydomain.com/_next/static/chunks/main-28f0bf55ce641aab.js:1:9184\nie@https://home.mydomain.com/_next/static/chunks/main-28f0bf55ce641aab.js:1:11824" }
index-e9478753f1558dcd.js:1:11185
    NextJS 30
        value
        callback
        Ua
        ki
        bi
        yi
        ws
        ws
        ls
        S
        T
        (Async: EventHandlerNonNull)
    5568
        f
        2962
        f
        3746
        f
        422
        f
        7851
        f
        2735
        f
        5257
        f
        <anonymous>
        O
        <anonymous>
        a
        <anonymous>
```

### Troubleshooting

this doesn't work
```
curl -L -k -H 'X-Api-Key:MYAPIKEY' 'https://portainer.ix-portainer.svc.cluster.local:10400/api/endpoints/1/docker/containers/json'
```
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:ix-portainer:portainer\" cannot get path \"/containers/json\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

this works
```
curl -L -k -H 'X-Api-Key:MYAPIKEY' 'https://portainer.ix-portainer.svc.cluster.local:10400/api/endpoints/1'
```
```
{
    "Id": 1,
    "Name": "local",
    "Type": 5,
    "URL": "https://kubernetes.default.svc",
    "GroupId": 2,
    "PublicURL": "",
    "Gpus": [],
    "TLSConfig": {
        "TLS": true,
        "TLSSkipVerify": true
    },
    "AzureCredentials": {
        "ApplicationID": "",
        "TenantID": "",
        "AuthenticationKey": ""
    },
    "TagIds": [],
    "Status": 1,
    "Snapshots": [],
    "UserAccessPolicies": {},
    "TeamAccessPolicies": {},
    "EdgeKey": "",
    "EdgeCheckinInterval": 0,
    "Kubernetes": {
        "Snapshots": [
            {
                "Time": 1685687961,
                "KubernetesVersion": "v1.25.3+k3s-9afcd6b9-dirty",
                "NodeCount": 1,
                "TotalCPU": 20,
                "TotalMemory": 134817910784
            }
        ],
        "Configuration": {
            "UseLoadBalancer": false,
            "UseServerMetrics": false,
            "EnableResourceOverCommit": false,
            "ResourceOverCommitPercentage": 0,
            "StorageClasses": [
                {
                    "Name": "openebs-zfspv-default",
                    "AccessModes": [
                        "RWO"
                    ],
                    "Provisioner": "zfs.csi.openebs.io",
                    "AllowVolumeExpansion": true
                }
            ],
            "IngressClasses": null,
            "RestrictDefaultNamespace": false,
            "IngressAvailabilityPerNamespace": false,
            "AllowNoneIngressClass": false
        },
        "Flags": {
            "IsServerMetricsDetected": true,
            "IsServerIngressClassDetected": true,
            "IsServerStorageDetected": true
        }
    },
    "ComposeSyntaxMaxVersion": "3.9",
    "SecuritySettings": {
        "allowBindMountsForRegularUsers": true,
        "allowPrivilegedModeForRegularUsers": true,
        "allowVolumeBrowserForRegularUsers": false,
        "allowHostNamespaceForRegularUsers": true,
        "allowDeviceMappingForRegularUsers": true,
        "allowStackManagementForRegularUsers": true,
        "allowContainerCapabilitiesForRegularUsers": true,
        "allowSysctlSettingForRegularUsers": true,
        "enableHostManagementFeatures": false
    },
    "LastCheckInDate": 0,
    "QueryDate": 0,
    "Heartbeat": false,
    "IsEdgeDevice": false,
    "UserTrusted": false,
    "PostInitMigrations": {
        "MigrateIngresses": false,
        "MigrateGPUs": false
    },
    "Edge": {
        "AsyncMode": false,
        "PingInterval": 0,
        "SnapshotInterval": 0,
        "CommandInterval": 0
    },
    "Agent": {
        "Version": ""
    },
    "EnableGPUManagement": false,
    "AuthorizedUsers": null,
    "AuthorizedTeams": null,
    "Tags": null
}
```

### Other

I am running a k3s cluster on [TrueNAS SCALE](https://www.truenas.com/truenas-scale/) (TrueNAS-SCALE-22.12.2) using the [TrueCharts](https://github.com/truecharts/charts) repository. Both apps have been installed from their catalogue and work without a problem.

In my `homepage` instance I have roughly 60 apps configured and 20 bookmarks, I am using 26 widgets of those available, and everything has been working fine ever since. Currently, my only widget failing is Portainer.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
