### ISSUE TITLE
How to setup the Coinmarket widget?

### ISSUE THREAD

**Issue by JDsnyke** [benphelps/homepage#158]
I've noticed that the coinmarketcap widget has been introduced, but there is no clear documentation on how to set it up? Could the wiki be updated please?

**Comment by Nonoss117** [comment]
Hi,

may be this can help you :
[https://github.com/benphelps/homepage/pull/118#issue-1369353651](https://github.com/benphelps/homepage/pull/118#issue-1369353651)

**Comment by benphelps** [comment]
A full example would be:

Inside of your `services.yaml`, under an existing group,

```yaml
- Coin Market Cap:
    icon: https://combinatronics.com/benphelps/homepage/main/images/icons/coinmarketcap.png
    description: Cryptocurrency Tracker
    widget:
      type: coinmarketcap
      currency: USD
      symbols: [BTC, LTC, ETH]
      key: yourapikeyhereyourapikeyhere
```
