### ISSUE TITLE
[Bug] Widget in docker version cannot display the correct storage capacity of the mounted hard drive

### ISSUE THREAD

**Issue by cugfzx** [benphelps/homepage#1581]
### Description

I mounted a  a large capacity hard drive on /app and set the storage capacity of the /app folder in the configuration file, but still displayed the storage usage of the root directory.
![image](https://github.com/benphelps/homepage/assets/52901066/fcf2ed32-9d26-4f61-9dbb-8e41080fa2f3)
![image](https://github.com/benphelps/homepage/assets/52901066/04c846ad-ce1a-482f-8814-20adbf7d5ecd)

### Steps to reproduce

1.Mount a hard drive on /app
2.Set widgets. yaml to the following content:
- resources:
    cpu: true
    memory: true
    disk: /app
3.Open the homepage webpage and you will find that the widget in the upper left corner still displays the capacity usage of the root directory

### homepage version

v0.6.20

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /app

	
- search:
    provider: duckduckgo
    target: _blank
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
