### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Adams-Scott** [benphelps/homepage#1592]
### Description

Stats for widgets come up as what looks like data types + variable name, for example `common.number resources.cpu` for the cpu stat or `common.ms` for ping stats. A new container works fine, but I have this problem as soon as I make a configuration change. I'm running in unraid. I thought maybe it was a Docker permission issue, but ping stats are also broken. The usage bars for the cpu/ram/storage stats work just fine, too. I've followed the file recommended file permission changes in the documentation. 

![homepage_stats](https://github.com/benphelps/homepage/assets/45578071/a4e5003a-2637-4a1d-9f08-fa54bdb3f7cd)

### Steps to reproduce

1. Create a new container that doesn't point to any existing config (The CPU and RAM stats work fine)
2. Change config (broken)
3. Delete modified yaml so Homepage has to recreate the default file (broken).

### homepage version

6.20

### Installation method

Unraid

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/


- Entertainment2:
    - YouTube2:
        - abbr: YT2
          href: https://youtube.com/
```

### Container Logs

[2023-06-10T16:52:20.647Z] info: docker.yaml was copied to the config folder
[2023-06-10T16:52:20.648Z] info: bookmarks.yaml was copied to the config folder
[2023-06-10T16:52:20.649Z] info: widgets.yaml was copied to the config folder
[2023-06-10T16:52:20.655Z] info: kubernetes.yaml was copied to the config folder
[2023-06-10T16:52:20.656Z] info: services.yaml was copied to the config folder
[2023-06-10T17:14:30.261Z] debug: No containers were found with homepage labels.
[2023-06-10T17:14:30.532Z] debug: No containers were found with homepage labels.
[2023-06-10T17:14:31.061Z] debug: No containers were found with homepage labels.

### Browser Logs

android-chrome-192x192.png:1     GET http://192.168.0.20:3000/android-chrome-192x192.png?v=2 404 (Not Found)
192.168.0.20/:1 Error while trying to use the following icon from the Manifest: http://192.168.0.20:3000/android-chrome-192x192.png?v=2 (Download error or resource isn't a valid image)

### Troubleshooting

I've tried quite a bit to figure it out. I'm pretty sure it's not my config because returning the config back to default doesn't work. I'm happy to try any suggestions.

I've tried using v0.6.19 and v0.6.18.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
