### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ozdeadmeat** [benphelps/homepage#1644]
### Description

Background Blur effect is not effecting the boxes but the entire background based on the images shown on the link provided

https://tailwindcss.com/docs/backdrop-blur

How do you blur the image just where the boxes are?

### Steps to reproduce

setup a 'sm' blur effect in the settings.yaml

### homepage version

v0.6.21

### Installation method

Docker

### Configuration

```yaml
title: home.pwn.net
headerStyle: clean
favicon: /images/favicon.ico
#background: /images/A10c-1.png
background: 
  image: /images/A10c-1.png
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 100 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100


#backgroundOpacity: 0.35

theme: dark # or light
color: gray
language: en-AU
layout:
  Infrastructure:
    style: row
    columns: 3
  Media Managers:
    style: row
    columns: 3
  Streaming Server:
    style: row
    columns: 2
```

### Troubleshooting

tried a bunch of settings from https://tailwindcss.com/docs/backdrop-blur

all returned the same result

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
