### ISSUE TITLE
[Bug] Ping & API Timeouts on Synology DSM 7.2

### ISSUE THREAD

**Issue by PriorityPete** [benphelps/homepage#1660]
### Description

After updating my synology dsm to 7.2 I'm having issues with pinging my services and using the widgets. This an example error I get for every service:

05.07.2023 18:23:57
[2023-07-05T16:23:57.315Z] error: <httpProxy> Error calling http://192.168.178.114:XXXX/...
05.07.2023 18:23:57
[2023-07-05T16:23:57.316Z] error: <httpProxy> [
05.07.2023 18:23:57
  500,
05.07.2023 18:23:57
  Error: connect ETIMEDOUT 192.168.178.114:XXXX
05.07.2023 18:23:57
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
05.07.2023 18:23:57
    errno: -110,
05.07.2023 18:23:57
    address: '192.168.178.114',
05.07.2023 18:23:57
    port: XXXX
05.07.2023 18:23:57
  }
05.07.2023 18:23:57
]

Some people using homebridge are having similar problems since updating to 7.2 and node.js may be reason for that.

### Steps to reproduce

Just run the dashboard on a 7.2 dsm. The dashboard itself works. Pinging and using the apis (weater too) doesn't work. Interesting enough the ping to my dsm login is the only one that works.

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
Heres an example config that worked before:
- Media:
    - Plex:
        icon: plex.png
        href: http://192.168.178.114:XXXXX
        ping: http://192.168.178.114:XXXXX/web/index.html#!/
        description: Mediaserver
        widget:
            type: plex
            url: http://192.168.178.114:XXXXX
            key: XXXXXXX
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
