### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by renouji** [benphelps/homepage#1666]
### Description

I am trying to use the service widget type of docker so that I can display rx & tx but not cpu & mem. It doesn't appear to be working as expected as when I use fields [rx,tx] to display those fields they will flash while the widget loads and then disappear, cpu & mem will appear when I put them in the [field].
![bugreport 1](https://github.com/benphelps/homepage/assets/13457806/3650f5f5-6466-494b-aaae-2f754576188c)

### Steps to reproduce

1. add this to your service in service.yaml:
widget:
        type: docker
        server: my-docker
        container: mycontainer
        fields: [cpu,rx,tx]
![bugreport2](https://github.com/benphelps/homepage/assets/13457806/7ab2acff-9514-40bd-8e9b-7fea8ebf6dfe)
![bugreport3](https://github.com/benphelps/homepage/assets/13457806/d17640e1-6c71-46d2-9363-b5248877c933)

### homepage version

nightly (8f953c0, Jul 6, 2023)

### Installation method

Unraid

### Configuration

```yaml
- Media Management:
    - Sonarr - Anime:
        icon: sonarr.svg
        description: Anime media manager.
        widget:
            type: docker
            server: my-docker
            container: sonarr-anime
            fields: [cpu,rx,tx]
```

### Container Logs

The only thing I see in the container log is:

Listening on port 3000

### Troubleshooting

I tried different words such as receive, transmit, RX, TX etc. I tried searching through the source and even used developer mode of my browser. as far as I can tell it should be displaying those values. I even tried the :latest and :main branches

### Other

I have it installed on unraid in a docker pulling ghcr.io/benphelps/homepage:main

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
