### ISSUE TITLE
[Bug] Disk space incorrect on container start, accurate after container restart

### ISSUE THREAD

**Issue by Kline-** [benphelps/homepage#1667]
### Description

On first boot of my homepage container the disk space reported in widgets only seems to report the space of the first volume. After restarting the homepage container the widgets report correctly.

First boot
![Screenshot 2023-07-08 12 38 37 PM](https://github.com/benphelps/homepage/assets/1126350/4197baa6-6f3d-415c-ac17-f7deb82315d0)

After restart
![Screenshot 2023-07-08 12 39 13 PM](https://github.com/benphelps/homepage/assets/1126350/c6ee1338-acc3-432c-a958-50f3678d2441)

### Steps to reproduce

1. Start the homepage container, observe incorrect widget reporting for disk space
2. Restart the homepage container, observe correct widget reporting for disk space

### homepage version

v0.6.21 (3e01fc1, Jun 12, 2023)

### Installation method

Docker

### Configuration

Compose file
```yaml
  homepage:
    container_name: "homepage"
    image: "ghcr.io/benphelps/homepage:latest"
    environment:
      - "TZ=America/Chicago"
      - "LOG_LEVEL=debug"
    networks:
      - "bridge"
    restart: "unless-stopped"
    volumes:
      - "/home/docker/homepage:/app/config"
      - "/home/docker/homepage/icons:/app/public/icons"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root:/mnt/root:ro"
      - "/home:/mnt/home:ro"
```

Widgets file
```yaml
- resources:
    cpu: true
    expanded: true
    memory: true

- resources:
    disk: /mnt/root
    expanded: true
    label: root

- resources:
    disk: /mnt/home
    expanded: true
    label: home
```

### Browser Logs

Nginx reverse proxy logs, before and after container restart (no change)
```
10.0.2.39 - - [08/Jul/2023:12:38:33 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/root HTTP/1.1" 200
10.0.2.39 - - [08/Jul/2023:12:38:33 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/home HTTP/1.1" 200
10.0.2.39 - - [08/Jul/2023:12:38:36 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/root HTTP/1.1" 304
10.0.2.39 - - [08/Jul/2023:12:38:36 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/home HTTP/1.1" 304
10.0.2.39 - - [08/Jul/2023:12:38:39 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/root HTTP/1.1" 304
10.0.2.39 - - [08/Jul/2023:12:38:39 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/home HTTP/1.1" 304
2023/07/08 12:38:54 [error] 29#29: *485 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.39
2023/07/08 12:38:54 [error] 29#29: *486 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.39
10.0.2.39 - - [08/Jul/2023:12:38:42 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/root HTTP/1.1" 200
10.0.2.39 - - [08/Jul/2023:12:38:42 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/home HTTP/1.1" 200
10.0.2.39 - - [08/Jul/2023:12:38:45 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/home HTTP/1.1" 304
10.0.2.39 - - [08/Jul/2023:12:38:45 -0500] "GET /api/widgets/resources?type=disk&target=/mnt/root HTTP/1.1" 304
```

### Troubleshooting

n/a

### Other

Docker version 20.10.24+dfsg1
Host OS Debian 12 (stable/bookworm)

```
df -h / /home
Filesystem      Size  Used Avail Use% Mounted on
/dev/md2         63G  9.4G   51G  16% /
/dev/sda6        15T  6.7T  7.5T  47% /home
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
