### ISSUE TITLE
[Bug] Homepage wakes array even when disabling widgets that query disk

### ISSUE THREAD

**Issue by Jinra** [benphelps/homepage#1669]
### Description

I noticed that whenever I start my PC my Unraid array wakes up with nothing showing up in file activity. I tracked this issue down to the homepage docker container, as right when I start it manually, it will wake my array. This also happens if the container is already on and first boot up my computer. Oddly enough, this doesn't happen when I spin down the disks and restart my computer. However, it will wake randomly throughout the day. 

I thought this might have been due to widgets I used to query disk space from widgets.yaml, as well as on service widgets like nextcloud. However, after disabling both of these, I still run into the wake issue. I noticed it's not a simple read of my array disk though, as the parity drives also wake with it.

### Steps to reproduce

1. Spin down unraid disks
2. Install homepage on Unraid (mine is 6.12.2)
3. Start homepage container
4. Array wakes 

### homepage version

v0.6.21 (3e01fc1, Jun 12, 2023)

### Installation method

Unraid

### Configuration

```yaml
widgets.yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    cputemp: true
    uptime: true
    memory: true

# - resources:
#     disk: /mnt/storage

# - resources:
#     disk: /mnt/user0

- openmeteo:
    label: redacted
    latitude: redacted
    longitude: redacted
    timezone: America/Los_Angeles
    units: imperial
    cache: 5

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short

- search:
    provider: google
    focus: true
    target: _blank
```
```


### Container Logs

n/a

### Browser Logs

_No response_

### Troubleshooting

I disabled any widgets that might query the array, but still run into the issue. I have appdata where homepage app data lives set to cache only.

![image](https://github.com/benphelps/homepage/assets/36873193/6e16d6d1-ae70-4675-a286-0c7b40da41bb)


### Other

Unraid 6.12.2
Homepage v0.6.21
Array (all 16tb, 2x parity, 4x disk storage)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
