### ISSUE TITLE
Pi-hole Widget CORS

### ISSUE THREAD

**Issue by chrisg991** [benphelps/homepage#17]
I have added the Pi-hole widget to each of my Pi-hole entries on Homepage and both are saying "PiHole API Error". The message below is given in Chrome's console.

`homepage.lan/:1 Access to fetch at 'http://192.168.3.4:8181/admin/api.php' from origin 'http://homepage.lan' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by benphelps** [comment]
I've added the option to proxy the API requests,

```yaml
widget:
  type: pihole
  url: http://pi.hole
  proxy: true # this will enable the CORS proxy
```
