### ISSUE TITLE
[Bug] 0.6.23 - Glances shows NaN for sensors (temp)

### ISSUE THREAD

**Issue by upD8R** [benphelps/homepage#1703]
### Description

After the update to 0.6.23 the Glances widget shows NaN instead of the bar, actual temperature and unit are shown. Valid for all 3/different Glances sources in my case.

![image](https://github.com/benphelps/homepage/assets/39015615/0690ad24-b258-4eae-b134-86bc76ac450c)
The first widget is not Glances but "resource", so here temp is correct.

### Steps to reproduce

Use Glances running on Raspberry Pi and enable sensor usage.

### homepage version

0.6.23

### Installation method

Docker

### Configuration

```yaml
- glances:
    url: http://fhem.fritz.box:61208
    username: user # optional if auth enabled in Glances
    password: pass # optional if auth enabled in Glances
    cputemp: true # disabled by default
    uptime: false # disabled by default
    disk: / # disabled by default, use mount point of disk(s) in glances. Can also be a list (see below)
    expanded: false # show the expanded view
    label: fhem.fritz.box # optional
```

### Troubleshooting

Output of curl:
```
pi@pihole ~> docker exec homepage curl -l -k http://fhem.fritz.box:61208/api/3/sensors
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0    151      0 --:--:-- --:--:-- --:--:--   151
[{"label": "cpu_thermal 1", "value": 43, "unit": "C", "type": "temperature_core", "key": "label"}]⏎ 
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
