### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Rejfin** [benphelps/homepage#172]
Hi,
When installing homepage with docker compose it displays an error in consol and i am unable to overcome this:
`homepage     | Listening on port 3000`
`homepage     | (node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time`
`homepage     | (Use 'node --trace-warnings ...' to show where the warning was created)`

But i am not sure how to use `node --trace-warnings` with compose config file

My compose config for homepage:

```
homepage:
     image: ghcr.io/benphelps/homepage:latest
     container_name: homepage
     volumes:
       - ./homepage/config:/app/config 
       - /var/run/docker.sock:/var/run/docker.sock
     labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host('dashboard.my.domain')
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls.certresolver=letsencrypt
      - traefik.http.services.frontend.loadbalancer.server.port=3000
    networks:
      - proxy
```

I found somewhere that I can add the `node --trace-warnings` command by adding a command block in compose file:

```
command:
   - node
   - "--trace-warnings"
   -  "."
```
But that return me something like this(which is probably because I'm not doing it correctly):

```
 node:internal/modules/cjs/loader:958
homepage     |   throw err;
homepage     |   ^
homepage     |
homepage     | Error: Cannot find module '/app'
homepage     |     at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
homepage     |     at Module._load (node:internal/modules/cjs/loader:803:27)
homepage     |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
homepage     |     at node:internal/main/run_main_module:18:47 {
homepage     |   code: 'MODULE_NOT_FOUND',
homepage     |   requireStack: []
homepage     | }
homepage     |
homepage     | Node.js v18.9.0

```
