### ISSUE TITLE
[Bug] Logo and resources separation disappeared...

### ISSUE THREAD

**Issue by juanmanuelbc** [benphelps/homepage#1720]
### Description

The logo and resources separation has disappeared with last update...

![imatge](https://github.com/benphelps/homepage/assets/13131391/eb281675-038e-4e85-bb69-ff633579f08a)

### Steps to reproduce

See error in description capture...

### homepage version

v0.6.23

### Installation method

Docker

### Troubleshooting

Maybe some `ml-` (margin-left) can help...

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
This is actually not something I can reproduce at the moment, please post more specifics of your widget config and a screenshot that shows the full width

<img width="151" alt="Screenshot 2023-07-24 at 8 35 28 AM" src="https://github.com/benphelps/homepage/assets/4887959/37abc73e-04a4-4dc9-bf11-1bb2cebb7adb">
<img width="246" alt="Screenshot 2023-07-24 at 8 35 46 AM" src="https://github.com/benphelps/homepage/assets/4887959/626936c1-69c0-4cc9-8fa2-6cb5e88ad511">

Presumably #1603

**Comment by juanmanuelbc** [comment]
Full width screenshot:
![imatge](https://github.com/benphelps/homepage/assets/13131391/0a51caaa-dcce-4d20-bf26-ad9d6b8a469e)
Widgets config:
```yaml
- logo:
    icon: /icons/ADBSYSTEMS.png
- resources:
    label: Synology
    cpu: true
    memory: true
    disk: /
    cputemp: true
- search:
    provider: google
    target: _blank
- datetime:
    text_size: sm
    format:
        dateStyle: full
        timeStyle: medium
        hour12: false
- openmeteo:
    label: xxx
    latitude: xxx
    longitude: xxx
    timezone: Europe/Madrid
    units: metric
    cache: 5
- openmeteo:
    label: yyy
    latitude: yyy
    longitude: yyy
    timezone: Europe/Madrid
    units: metric
    cache: 5
```
Settings config:
```yaml
headerStyle: boxed
```
