### ISSUE TITLE
[Bug] v0.6.24 breaks refresh of information widgets

### ISSUE THREAD

**Issue by wioo** [benphelps/homepage#1741]
### Description

Information widgets wont refresh unless “refresh” is set in settings.

### Steps to reproduce

1. Install [v0.6.24](https://github.com/benphelps/homepage/releases/tag/v0.6.24)
2. Information widgets wont change its value
3. If refresh is set to 1500 it works again

### homepage version

v0.6.24

### Installation method

Docker

### Configuration

```yaml
Without

- resources:
    cpu: true
    cputemp: true
    memory: true
    disk: /app/public/images

With

- resources:
    cpu: true
    refresh: 1500
    cputemp: true
    memory: true
    disk: /app/public/images
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
