### ISSUE TITLE
[Bug] Disk widget showing 0

### ISSUE THREAD

**Issue by saschabrockel** [benphelps/homepage#1745]
### Description

It appeared after some update and didn't go away since then. I have no clue why a 0 is shown. 
The 3 disks are mounted Docker volumes where `/` is the location where the app is installed. The other ones are a ZFS pool and another hard drive. It works for the hard drive named `array-disk1`

![image](https://github.com/benphelps/homepage/assets/33376463/debeec1e-38c6-4222-bcdc-600ec5362e6c)

### Steps to reproduce

Just open your dashboard.

### homepage version

v0.6.24 (62e294a, Jul 30, 2023)

### Installation method

Docker

### Configuration

```yaml
- resources:
    icon: mdi-system
    label: System
    cpu: true
    cputemp: true
    memory: true
    uptime: true
- resources:
    label: Storage
    disk: 
      - /
      - /array-disk1
      - /safety-zfs
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
