### ISSUE TITLE
Octoprint display fails after refresh during print

### ISSUE THREAD

**Issue by Thormus** [benphelps/homepage#1747]
### Description

![image](https://github.com/benphelps/homepage/assets/85920967/063725dd-413d-46da-a708-443a380a03fa)

Octoprint shows the status of my printer fine before a print and after a print starts but when I refresh the homepage page it does this.

### Steps to reproduce

1. Start Print
2. Refresh page

### homepage version

v0.6.25

### Installation method

Unraid

### Configuration

```yaml
- Prusa Mk3s+:
        icon: octoprint
        href: http://192.168.1.195
        ping: http://192.168.1.195
        description: 3D Printer Interface
        widget:
          type: octoprint
          url: http://192.168.1.195
          key: 2025062B06F34672AA9DCC6C151XXXXX
```

### Container Logs

[2023-07-31T16:47:04.154Z] error: <httpProxy> Error calling http://192.168.1.195/...
[2023-07-31T16:47:04.156Z] error: <httpProxy> [
  500,
  Error: Parse Error: Invalid header value char
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    bytesParsed: 56,
    code: 'HPE_INVALID_HEADER_TOKEN',
    reason: 'Invalid header value char',
    rawPacket: <Buffer 48 54 54 50 2f 31 2e 30 20 35 30 33 20 53 65 72 76 69 63 65 20 55 6e 61 76 61 69 6c 61 62 6c 65 0a 43 61 63 68 65 2d 43 6f 6e 74 72 6f 6c 3a 20 6e 6f ... 3605 more bytes>
  }
]

### Troubleshooting

restarted container

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
