### ISSUE TITLE
[Bug]  Activating any API throws 500 Errors

### ISSUE THREAD

**Issue by IrealiTY** [benphelps/homepage#175]
**Describe the bug**
Not a single API works

**Screenshots**
![image](https://user-images.githubusercontent.com/1223686/190486302-332225e5-def6-41ee-91b0-9c766589ba16.png)
![image](https://user-images.githubusercontent.com/1223686/190486698-b848d265-c17c-4d52-ab82-34c887aa4f1f.png)

**Configuration**
If applicable,
```yaml
- Media:
    - Overseerr:
        icon: overseerr.png
        href: https://shows.xxxxx.xxxxx/
        description: Looking for shows
        server: my-local-docker # The docker server that was configured
        container: overseerr
        widget:
            type: overseerr
            url: https://shows.xxxx.xxxxx
            key: xxxx
```

**Additional context**

Had the same issue with and without reverse proxy
