### ISSUE TITLE
[Bug] Error in weather providers

### ISSUE THREAD

**Issue by AmadeusGraves** [benphelps/homepage#176]
**Describe the bug**
The query showing the time in the application fails. It has been tested with both services and the data has been entered completely from widgets.yml, no provider has been used from settings.xml.

**Expected behavior**
The time should be displayed when the page is reloaded from the bottom button at the bottom of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/18572939/190494469-d1487812-6ca5-4863-8c74-b51afd7546da.png)

![image](https://user-images.githubusercontent.com/18572939/190495099-1c42b5d7-2d1d-4abb-b8df-1461f7aedfe5.png)

**Configuration**
If applicable,
```yaml
- weatherapi:
    label: My live place #optional
    latitude: 37.938237
    longitude: 45.760077
    units: metric # or imperial
    provider: APIKEY
    cache: 5 # Time in minutes to cache API responses, to stay within limits
```
