### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Xaositek** [benphelps/homepage#1768]
### Description

Widgets section shows multiple "Please Wait" placeholders that remain after disk usage is populated. See screenshot.

<img width="1002" alt="Screenshot 2023-08-03 at 9 06 55 AM" src="https://github.com/benphelps/homepage/assets/85509/efaee464-f5e6-496f-9c47-896abaf7a0a2">

### Steps to reproduce

I have attached my widgets.yaml, I did notice I mark /mnt/disk2 and /mnt/disk3 as comments and just have a single disk, this issue is not present.

This exact confirmation was working until my Docker updated after I was out of PTO for 10 days, unsure which version introduced this regression.

### homepage version

v0.6.27 (2faaaf5, Aug 2, 2023)

### Installation method

Docker

### Configuration

```yaml
Here is my YAML file.

# "system" label with hardware statistics
- logo:
    icon: https://cdn4.iconfinder.com/data/icons/device-59/136/computer-pc-device-hardware-512.png

#- resources:
#    label: System
    # expanded: true
#    cpu: true
#    cputemp: true
#    memory: true
#    units: imperial

- glances:
    url: http://192.168.50.24:61208/
#    username: user # optional if auth enabled in Glances
#    password: pass # optional if auth enabled in Glances
    cputemp: true # disabled by default
    uptime: false # disabled by default
    disk:
      - /mnt/disk1
      - /mnt/disk2
      - /mnt/disk3
    expanded: true # show the expanded view
    label: Snowball # optional
    units: imperial


- logo:
    icon: https://cdn4.iconfinder.com/data/icons/device-59/136/computer-pc-device-hardware-512.png

- glances:
    url: http://192.168.50.25:61208/
#    username: user # optional if auth enabled in Glances
#    password: pass # optional if auth enabled in Glances
    cputemp: true # disabled by default
    uptime: false # disabled by default
    disk:
      - /mnt/disk1
      - /mnt/disk2
    expanded: true # show the expanded view
    label: Nyx # optional
    units: imperial

- search:
    provider: google
    target: _blank

# blank icon to put some space between unifi controller and array portion. looks cleaner this way
- logo:
    icon: https://upload.wikimedia.org/wikipedia/commons/4/48/BLANK_ICON.png
```

### Troubleshooting

I did notice I mark /mnt/disk2 and /mnt/disk3 as comments and just have a single disk (/mnt/disk1), this issue is not present.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
