### ISSUE TITLE
[Bug] Memory stats for glances chart displays incorrect values

### ISSUE THREAD

**Issue by MountainGod2** [benphelps/homepage#1774]
### Description

When I look at the chart in Homepage for my glances memory statistics, I'm receiving different values than what's reported in the glances UI for both the `Free` and `Total` fields. Currently, Homepage is reporting 135GB total, with 126GB free, and 9GB in use. However, the system only has 128GB installed. 

Glances UI:
![image](https://github.com/benphelps/homepage/assets/88257202/b8abf6a7-f636-45ba-9185-5ed334df5241)
Homepage chart:
![image](https://github.com/benphelps/homepage/assets/88257202/b1ebc81d-9543-4ac5-9970-c9b42686f4f4)

### Steps to reproduce

1.) Enable glances memory widget

2.) Compare values vs those reported on the host/glances UI
```
:~# free -g
               total        used        free      shared  buff/cache   available
Mem:             125           6          16           0         103         117
```

### homepage version

v0.6.27 (2faaaf5, Aug 2, 2023)

### Installation method

Docker

### Configuration

```yaml
- Glances:
    - Memory Usage:
        widget:
          type: glances
          url: http://glances:61208
          metric: memory
```

### Troubleshooting

N/A

### Other

Unraid 6.12.3.
Homepage and Glances are both on the same custom user-defined bridge docker network.
Everything else related to charts appears fine.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by MountainGod2** [comment]
Should also note that the Glances information widget reports the expected value

![image](https://github.com/benphelps/homepage/assets/88257202/ce1be509-cbe8-46cb-856d-46e7f318b0cd)

```yaml
- resources:
    memory: true
    expanded: true

- glances:
    url: http://glances:61208
```
