### ISSUE TITLE
[Bug] Widget displaying information from different service

### ISSUE THREAD

**Issue by fredericosar** [benphelps/homepage#1785]
### Description

My setup has  a primary and a backup PiHole running for redundancy.  I have both into my dashboard and the links work correctly  asI can go to their distinct pages. However, the stats are repeated showing the stats for the primary in the backup.

<img width="1513" alt="Screen Shot 2023-08-06 at 13 42 13" src="https://github.com/benphelps/homepage/assets/10275737/aa9bdacf-198d-40dc-9436-44990c56d8f0">

### Steps to reproduce

1. Have 2 PiHoles running in distinct boxes
2. Add them to the dashboard
3. Check it :)

### homepage version

v0.6.28

### Installation method

Docker

### Configuration

```yaml
- Server Management:
    - PiHole:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pi-hole.png
        href: http://192.168.50.140:9080/admin
        description: DNS - Primary
        widget:
            type: pihole
            url: http://192.168.50.140:9080
    - PiHole:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pi-hole.png
        href: http://192.168.50.14:9080/admin
        description: DNS - Backup
        widget:
            type: pihole
            url: http://192.168.50.14:9080
```

### Troubleshooting

1. Widget rules are followed
2. Docker can reach no problem
```
docker exec homepage ping 192.168.50.14:9080.
PING 192.168.50.14:9080 (192.168.50.14): 56 data bytes
64 bytes from 192.168.50.14: seq=0 ttl=63 time=0.358 ms

docker exec homepage ping 192.168.50.140:9080
PING 192.168.50.140:9080 (192.168.50.140): 56 data bytes
64 bytes from 192.168.50.140: seq=0 ttl=64 time=0.052 ms
```
3. API responses for PiHole are distinct

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
