### ISSUE TITLE
Lidarr widget not working

### ISSUE THREAD

**Issue by 2ndwonder** [benphelps/homepage#180]
Lidarr widget is not working for me. Am I missing something? I don't see instructions for Lidarr.

```
    - Lidarr:
        icon: lidarr.png
        href: https://subdomain.domain.nl
        description: Music Managment
        server: docker
        container: lidarr
        widget:
          type: lidarr
          url: https://subdomain.domain.nl
          key: API KEY 
```
**If I uncomment the "key" section, it loads. But with API Error.**

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/24813161/190519546-b711aac1-69e5-4d46-b2a6-1a601961d76c.png">

**with API key included**

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/24813161/190520139-eda6133e-9023-42f4-b1e7-bb6ceb49947b.png">
