### ISSUE TITLE
[Feature Request] Display the title at the top of the page

### ISSUE THREAD

**Issue by proffalken** [benphelps/homepage#181]
**Is your feature request related to a service? Please describe.**

I'm looking to use this for the "tools" site of our Makerspace, and it's fantastic but if I set `title` in the settings then it only seems to change the `<title></title>` tags rather than adding a title to the page at the top.

**Is your feature request related to a problem? Please describe.**

No

**Additional context**

Something like this is what I'm after:
![image](https://user-images.githubusercontent.com/262545/190568992-408e5aee-d7d2-483f-9c6d-7f70cc2bcef2.png)

**Comment by benphelps** [comment]
Absolutely, and weirdly enough this was a widget before, I removed it and don't remember why now.

**Comment by benphelps** [comment]
This has been added, please see: https://github.com/benphelps/homepage/wiki/Information-Widgets#greeting

**Comment by proffalken** [comment]
Amazing, thank you!

**Comment by proffalken** [comment]
@benphelps can you confirm that this configuration in `widgets.yaml` is correct please? Because I'm not seeing it show up:

```yaml
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Information-Widgets

#- resources:
#    cpu: true
#    memory: true
#    disk: /
#
#- search:
#    provider: duckduckgo
#    target: _blank
- greeting:
    text_size: xl
    text: Make Monmouth tools and links
```

![image](https://user-images.githubusercontent.com/262545/190655880-97977835-b040-4a73-a0bb-9ff2d3e503b2.png)
