### ISSUE TITLE
[Bug] Calibre-web Widget

### ISSUE THREAD

**Issue by Nonoss117** [benphelps/homepage#1845]
### Description

Nice job, I like this widget, thanks
But, may be someting wrong with book numbers. In my case, they are the same than authors (50).
See screenshots below

### Steps to reproduce

Install calibre-web-widget

### homepage version

main (fb04972, 21 août 2023)

### Installation method

Docker

### Configuration

```yaml
Same as documentation, settings.yaml

    - Calibre Web:
        icon: calibre-web.png
        #icon: /icons/calibreweb.png
        href: http://192.168.1.100:8084
        server: nas-docker
        container: calibre-web
        description: ebooks
        widget:
          type: calibreweb
          url: http://192.168.1.100:8084
          username: MyUserName
          password: MyPassword
```

### Troubleshooting

Books and authors counts are the same

![image](https://github.com/benphelps/homepage/assets/79055577/73856961-440e-4cd6-b735-67022d15945c)

This is a screen shot of my book numbres, in each series :

![image](https://github.com/benphelps/homepage/assets/79055577/7b621db5-7a3c-49ef-881a-07f152004e58)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
