### ISSUE TITLE
[Bug] Using cardBlur: resizes widgets

### ISSUE THREAD

**Issue by k2gremlin** [benphelps/homepage#1894]
### Description

Adding cardblur seems to have an impact on the search widget at the top of my homepage. 

Without cardblur
![image](https://github.com/benphelps/homepage/assets/10319833/e68d40f8-2c79-43c8-994a-1d656270ae90)

With cardblur
![image](https://github.com/benphelps/homepage/assets/10319833/f2575114-fc70-48d5-908c-6b7d2319a39c)

Was able to reproduce with cardblur: sm and cardblur: md. Didn't try any of the other cardblur settings.

### Steps to reproduce

edit settings.yaml
add "cardblur: sm"
save
refresh home page. 

### homepage version

0.6.29

### Installation method

Docker

### Configuration

```yaml
cardBlur: sm


headerStyle: boxedWidgets
color: slate
background:
  image: /images/image6.jpg
  opacity: 75
quicklaunch:
    searchDescriptions: true
    hideInternetSearch: false
    hideVisitURL: true
target: _self
```

### Container Logs

No logs present when turning cardblur on/off

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
