### ISSUE TITLE
[Bug] Order of fields is not respected

### ISSUE THREAD

**Issue by Shagon94** [benphelps/homepage#1921]
### Description

Homepage does not respect the order of fields for widgets, e.g.:

```yaml
- Plex:
    icon: plex.png
    description: Media server
    container: plex
    href: http://10.10.10.10:32400/web/index.html#
    widget:
        type: plex
        url: http://10.10.10.10:32400
        key: asdf # see https://www.plexopedia.com/plex-media-server/general/plex-token/
        fields: ["movies", "tv", "albums"]
```

however the order is not maintained:

<img width="336" alt="image" src="https://github.com/benphelps/homepage/assets/9140783/1aa6cae1-ede4-4ddd-8a23-72bb2804cde6">

### Steps to reproduce

1. Go to homepage
2. See order of widget fields (albums, movies, tv shows)

### homepage version

v0.6.29 (fc7e73e, Aug 26, 2023)

### Installation method

Unraid

### Configuration

```yaml
# docker inspect ghcr.io/benphelps/homepage:latest | jq | grep 'ghcr.io/benphelps/homepage'
      "ghcr.io/benphelps/homepage:latest"
      "ghcr.io/benphelps/homepage@sha256:40c0a01cf7067c3be71014455ad9fda36ca3cd14c3660034ae3bf34ab0c514cf"
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Troubleshooting

n/a

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
