### ISSUE TITLE
[Bug] Mealie Widget didnt work  

### ISSUE THREAD

**Issue by slofii** [benphelps/homepage#1924]
### Description

The Api-Key for the mealie-widget didnt work. 

This is the config: 
![Screenshot 2023-09-08 083414](https://github.com/benphelps/homepage/assets/55784637/3af18619-2eda-4d7d-bc69-631e44cdb509)

This is the outcoming:
<img width="292" alt="Screenshot 2023-09-08 083047" src="https://github.com/benphelps/homepage/assets/55784637/8d3b7b64-5956-45fd-8cd0-f713528ef704">

### Steps to reproduce

Create an api key on the mealie page.
Click on Settings
Create an api key under "API-Tokens"
Insert API-Key on the homepage-config 

### homepage version

v.0.6.29

### Installation method

Docker

### Configuration

```yaml
- Mealie:
        icon: mealie
        href: http://XXX.XXX.XXX.XXX:9777
        description: Rezeptesammlung
        server: my-docker
        container: mealie
        widget:
          type: mealie
          fields: ["recipes","categories"]
          url: http://XXX.XXX.XXX.XXX:9777
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb25nX3Rva2VuIjp0cnVlLCJpZCI6MSwiZXhwIjoxODUxODM0NzUwfQ.nmCP1PhD5ilwD77-8Sy-BKQaB2oF_yEX2KvVS-qUocc
```

### Troubleshooting

n/a

### Other

mealie-version: v0.5.6

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
