### ISSUE TITLE
[Bug] API Error: Proxmox Backup Server

### ISSUE THREAD

**Issue by huseyinkogo** [benphelps/homepage#1940]
### Description

Hi,

I'm getting the API ERROR for PBS.

Like the url is correct however its always been showing API ERROR: JSON.parse: unexpected character at line 1 column 1 of the JSON data

![Screenshot from 2023-09-09 20-42-24](https://github.com/benphelps/homepage/assets/76049382/4aac5b63-b4b6-4f91-a0c1-337695385270)

### Steps to reproduce

from the services.yaml file

### homepage version

v0.6.29 (fc7e73e, Aug 26, 2023)

### Installation method

Docker

### Configuration

```yaml
- Proxmox Backup Server:
        icon: syncthing.svg
        href: https://10.20.2.3:8007
        ping: https://10.20.2.3:8007
        widget:
          type: proxmoxbackupserver
          url: https://10.20.2.3:8007
          username: api_token_id
          password: api_token_secret
```

### Container Logs

n/a

### Browser Logs

XHRGET
https://homepage.kogo.com/api/services/proxy?type=proxmoxbackupserver&group=Backup/Sync&service=Proxmox+Backup+Server&endpoint=nodes/localhost/status
[HTTP/2 403 Forbidden 541ms]

### Troubleshooting

When i was playing it, i was like let me change the widget url to http from https.
after i was getting the following error:

```
    API Error: Unknown error
    URL: http://10.20.2.3:8007/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1693990706342
    Raw Error:
    {
        "errno": -104,
        "code": "ECONNRESET",
        "syscall": "read"
    }
```
![Screenshot from 2023-09-09 20-45-34](https://github.com/benphelps/homepage/assets/76049382/64813869-361e-4209-8690-3b0dfa91e9a0)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
