### ISSUE TITLE
[Bug] Glances charts have inconsistent start behaviour

### ISSUE THREAD

**Issue by LeviSnoot** [benphelps/homepage#1944]
### Description

![](https://github.com/benphelps/homepage/assets/13402525/e6572dfe-fa7d-46c5-92ee-f15520cd64fb)

In the attached screenshot you can see that the chart for CPU has a line all the way through the widget. In the other two charts, there's just a blank space. I think the charts would be a lot cleaner if they all behaved like the CPU chart. Starting at a null value and then, once the API is able to fetch data, the next data point transitions from that null value.

### Steps to reproduce

1. Add the config below to your `services.yaml` and edit it to point at a glances instance.
2. Deploy homepage and visit your homepage instance.

### homepage version

v0.6.29 (fc7e73e)

### Installation method

Docker

### Configuration

```yaml
- CPU Usage:
        href: http://glances.host.or.ip:port
        target: _self
        widget:
            type: glances
            url: http://glances.host.or.ip:port
            metric: cpu
    - Memory:
        href: http://glances.host.or.ip:port
        target: _self
        widget:
            type: glances
            url: http://glances.host.or.ip:port
            metric: memory
    - Network:
        href: http://glances.host.or.ip:port
        target: _self
        widget:
            type: glances
            url: http://glances.host.or.ip:port
            metric: network:enp0s25
    - Processes:
        href: http://glances.host.or.ip:port
        target: _self
        widget:
            type: glances
            url: http://glances.host.or.ip:port
            metric: process
```

### Troubleshooting

No troubleshooting is needed as this is native behaviour.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
