### ISSUE TITLE
Portainer states its offline

### ISSUE THREAD

**Issue by huzzyz** [benphelps/homepage#196]
I've tried just about everything, recreating the containers, starting from scratch. I have no idea why the status light appears offline. The widget below displays my running containers but above that it stays offline.

    - Portainer:
        icon: portainer.png
        href: http://192.168.1.53:9000
        description: Docker Maintenance
        container: portainer
        widget:
         type: portainer
         url: http://192.168.1.53:9000
         env: 2
         key: REDACTED
<img width="493" alt="Screen Shot 2022-09-17 at 14 39 41" src="https://user-images.githubusercontent.com/69323208/190852683-d38d8f1c-198a-499a-a786-61c4049895e1.png">

**Comment by benphelps** [comment]
You'll need to pass the docker server it's on as well, as defined in your `docker.yaml` file.

**Comment by huzzyz** [comment]
Sorry, done that too.

```
    - Portainer:
        icon: portainer.png
        href: http://192.168.1.53:9000
        description: Docker Maintenance
        container: portainer
        server: my-local-docker
        widget:
         type: portainer
         url: http://192.168.1.53:9000
         env: 2
         key: REDACTED
```
```
my-local-docker:
  socket: /var/run/docker.sock
```

**Comment by benphelps** [comment]
Make sure you're passing the docker socket through to your homepage container, as shown in the wiki: https://github.com/benphelps/homepage/wiki/Docker-Integration#configuration

**Comment by huzzyz** [comment]
Already have.

**Comment by colutti** [comment]
Same thing here.

This is from the services file:

![image](https://user-images.githubusercontent.com/9368892/190855383-aa6955a5-0a6d-492d-93af-c19949f33e8f.png)

From my docker-compose:

![image](https://user-images.githubusercontent.com/9368892/190855423-5a3620e8-7d1d-4105-923c-70d81cbdbd14.png)

My docker.yaml:

![image](https://user-images.githubusercontent.com/9368892/190855442-e1b4370e-7f8c-4d6d-8f32-d1c85868686e.png)

The results:

![image](https://user-images.githubusercontent.com/9368892/190855457-39cc75de-f397-4a22-aa82-0f75a4d4cc56.png)

**Comment by C8opmBM** [comment]
I am having the exact issue on all containers (Status offline)

```
  homepage:
    <<: *internalbase
    image: ghcr.io/benphelps/homepage:latest
    user: 1001:100 # Optional, change to your user and group IDs for permissions
    volumes:
      - /srv/dev-disk-by-label-downloads/mediatools/homepage:/app/config
      - /srv/dev-disk-by-label-downloads/mediatools/homepage/icons:/app/public/icons
      - /srv/dev-disk-by-label-downloads/mediatools/homepage/images:/app/public/images
      - /srv/dev-disk-by-label-Media:/hdd1
      - /srv/dev-disk-by-label-Media2:/hdd2
      - /var/run/docker.sock:/var/run/docker.sock # This passes your local docker socket to the container
    ports:
      - 3000:3000
    container_name: homepage
```

```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Docker-Integration

#my-docker:
#  host: 127.0.0.1
#  port: 2375

#other-docker:
#  socket: /var/run/docker.sock

local:
  socket: /var/run/docker.sock
```

```
- Utilities:
    - Media Portainer:
        icon: portainer.png
        href: http://192.168.1.151:9000/#!/2/docker/dashboard
        server: local
        container: portainer
        description: Container management
        widget:
          type: portainer
          url: http://192.168.1.151:9000
          env: 2
          key: REDACTED
```

![111](https://user-images.githubusercontent.com/60513190/190855773-33df4d2d-71ae-42a1-9aab-7ec60adf2456.png)
