### ISSUE TITLE
[Bug] Minecraft Widgets

### ISSUE THREAD

**Issue by Summer-Tail** [benphelps/homepage#1964]
### Description

Minecraft Widgets How to modify the URL parameters does not take effect. Check in the log that the addresses always requested are 127.0.0.1:25565

### Steps to reproduce

1. Edit Profile
2. Save
3. Refresh Browser

### homepage version

v0.6.28 (63a5622)

### Installation method

Docker

### Configuration

```yaml
- minecraftServer:
       icon: /icons/png/minecraft.png
       description: 我的世界服务器
       #container: minecraft-server
       server: my-server
       widget:
         type: minecraft
         url: 'udp:/172.17.0.8:25575'
```

### Container Logs

![image](https://github.com/benphelps/homepage/assets/46812909/0d17eede-7407-4559-89f2-9b10ed292406)

### Troubleshooting

![image](https://github.com/benphelps/homepage/assets/46812909/19ddb202-b3b1-4e6b-b9d9-b5efe4ebc124)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
