### ISSUE TITLE
glances not show[Bug] 

### ISSUE THREAD

**Issue by GavinIves** [benphelps/homepage#2026]
### Description

I use glances -c 10.123.1.103:61209 on other machines and I can connect and have content.
log shows not support operation
Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.
<img width="342" alt="image" src="https://github.com/benphelps/homepage/assets/38970877/41696461-c88c-4194-8e08-f2ab049f8e71">
<img width="450" alt="image" src="https://github.com/benphelps/homepage/assets/38970877/a6552128-08b5-42cc-bf93-e4c742e0610b">
<img width="897" alt="image" src="https://github.com/benphelps/homepage/assets/38970877/2685e59f-1aba-4a3d-834f-a8fbdd9254fb">

### Steps to reproduce

1

### homepage version

0.6.33

### Installation method

Docker

### Configuration

```yaml
- Production:
        icon: /icons/production.png
        href: 
        description: 应用服务
        ping: true
        widget:
            type: glances
            url: http://10.123.1.103:61209
            metric: cpu
            # chart: false
            

    - Database:
        icon: /icons/database.png
        href: 
        description: 数据库
        ping: true
        widget:
            type: glances
            url: http://10.123.1.104:61209
            metric: info
            # chart: false
```

### Container Logs

[2023-09-19T10:23:19.606Z] error: <glances> HTTP 501 getting data from glances API. Data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 501</p>
        <p>Message: Unsupported method ('GET').</p>
        <p>Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.</p>
    </body>
</html>

### Troubleshooting

<img width="631" alt="image" src="https://github.com/benphelps/homepage/assets/38970877/88e8dfdc-d015-4b42-8591-324f6f3bff17">

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
