### ISSUE TITLE
[Bug] Only three bookmark categories being displayed when using layout settings

### ISSUE THREAD

**Issue by tobiklimkait** [benphelps/homepage#2033]
### Description

When using the layout settings for your services in the settings.yaml, only three bookmark categories are being displayed.

Example layout settings:

```
layout:
  Service_category_one:
    style: row
    columns: 4
  Service_category_two:
    style: row
    columns: 4
```

Example bookmark categories:

```
- News:
    - Newssite1:
        - abbr: NO
          href: http://newssite1.com
    - Newssite2:
        - abbr: NT
          href: http://newssite2.com
- Entertainment:
    - Entertainmentsite1:
        - abbr: EO
          href: https://entertainmentsite1.com/
    - Entertainmentsite2:
        - abbr: ET
          href: https://entertainmentsite2.com/
- Social:
    - Socialsite1:
        - abbr: SO
          href: https://socialsite1.com/
    - Socialsite2:
        - abbr: ST
          href: https://socialsite2.com/
- Development:
    - Develpmentsite1:
        - abbr: DO
          href: https://developmentsite1.com/
    - Developmentsite2:
        - abbr: DT
          href: https://developmentsite2.com/
```

### Steps to reproduce

1. Set layout and bookmarks like described above
2. This will lead to only three bookmark categories being displayed.

### homepage version

v0.6.34

### Installation method

Docker

### Troubleshooting

- Tried to change the settings to "column" layout, which produced the same issue.
- Checked the log of the container, which only says "Listening on port 3000"

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
