### ISSUE TITLE
Kubernetes custom.js / custom.css ROFS read-only file system

### ISSUE THREAD

**Issue by shamoon** [benphelps/homepage#2040]
Okay, just did some digging. The issue is that the Helm Chart mounts a Kubernetes ConfigMap to `/app/config` which means that everything in `/app/config` is read only.

The best solution would be to have custom stuff in a different directory (`/app/config/custom`) or avoid copying to that directory in the first place.

Here is from within the container:

```bash
/app/config # ls -lsah
total 20K
   4.0K drwxrwxrwx    4 root     root        4.0K Sep 20 04:29 .
   8.0K drwxr-xr-x    1 node     node        4.0K Sep 20 04:29 ..
   4.0K drwxr-xr-x    2 root     root        4.0K Sep 20 04:29 ..2023_09_20_04_29_31.1381103690
      0 lrwxrwxrwx    1 root     root          32 Sep 20 04:29 ..data -> ..2023_09_20_04_29_31.1381103690
      0 lrwxrwxrwx    1 root     root          21 Sep 20 04:29 bookmarks.yaml -> ..data/bookmarks.yaml
      0 lrwxrwxrwx    1 root     root          18 Sep 20 04:29 docker.yaml -> ..data/docker.yaml
      0 lrwxrwxrwx    1 root     root          22 Sep 20 04:29 kubernetes.yaml -> ..data/kubernetes.yaml
   4.0K drwxrwxrwx    2 root     root        4.0K Sep 20 07:26 logs
      0 lrwxrwxrwx    1 root     root          20 Sep 20 04:29 services.yaml -> ..data/services.yaml
      0 lrwxrwxrwx    1 root     root          20 Sep 20 04:29 settings.yaml -> ..data/settings.yaml
      0 lrwxrwxrwx    1 root     root          19 Sep 20 04:29 widgets.yaml -> ..data/widgets.yaml
/app/config # touch test
touch: test: Read-only file system
```

_Originally posted by @Skaronator in https://github.com/benphelps/homepage/issues/1998#issuecomment-1728994717_

**Comment by shamoon** [comment]
I've been meaning to ask as I suspected this was a Kubernetes thing. I guess even more specifically the helm chart, which explains why @wisdomdevil has it but the OP of the other thread doesnt (sounds like he doesnt use helm)

So shouldn't the helm chart actually just be updated to reflect this? If I knew enough to open a PR I would, but I was poking around yesterday, presumably its https://github.com/jameswynn/helm-charts/blob/main/charts/homepage/templates/configmap.yaml ? Im also going to ping @jameswynn though I think he's been busy lately

**Comment by wisdomdevil** [comment]
I think the best solution for fix this bug it is add init container, that copy data from configmap, to config directory. After this solution we can modify config file from container (discovery service for ingress), and do changes in configmap for static configuration

**Comment by shamoon** [comment]
Isn't that kinda what I was suggesting? (Like Im actually asking, I dont speak kubernetes)

**Comment by wisdomdevil** [comment]
No, if we do as you suggested, we cant modify settings files, service discovery for ingress modify it?

**Comment by shamoon** [comment]
Sorry, between my lack of kubernetes knowledge and perhaps a language thing I dont get you. But anyway, this isn't something I can solve, I was just looking at the file above ( https://github.com/jameswynn/helm-charts/blob/main/charts/homepage/templates/configmap.yaml ) and it looked like that is how it maps the https://github.com/jameswynn/helm-charts/blob/667f273739923e2ce71f7fb5c6e3070d0c9f3341/charts/homepage/values.yaml#L50 to actual files.

The point is the newly-added `custom.css` and `custom.js` are copied in the docker image the same way as the settings yaml files, so I figured the logic needs to be duplicated for them, Im just not sure how thats done.

**Comment by Skaronator** [comment]
Sooo, homepage will copy the custom.css and custom.js to the config directory when the files doesn't exist? And customs.css and custom.js are empty, correct?

When both are true, then we can simply add them to the config block in the helm chart. That should fix this issue.


(I didn't check the code since I'm on my phone)

**Comment by shamoon** [comment]
yes x2!
- https://github.com/benphelps/homepage/blob/main/src/skeleton/custom.css & https://github.com/benphelps/homepage/blob/main/src/skeleton/custom.js
- https://github.com/benphelps/homepage/blob/2730fef54c390285fc22ea876e78131758a70dbe/src/utils/config/config.js#L20-L28

**Comment by MrMarble** [comment]
This could be easily fixed in the helm chart, just by passing subpaths:
This is my config for example:
```yaml
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: *config
        subPath:
          - path: bookmarks.yaml
            mountPath: /app/config/bookmarks.yaml
          - path: docker.yaml
            mountPath: /app/config/docker.yaml
          - path: kubernetes.yaml
            mountPath: /app/config/kubernetes.yaml
          - path: services.yaml
            mountPath: /app/config/services.yaml
          - path: settings.yaml
            mountPath: /app/config/settings.yaml
          - path: widgets.yaml
            mountPath: /app/config/widgets.yaml
```

This way the rest of the `config` folder can be managed by homepage without errors
