### ISSUE TITLE
[Bug] Authentik widget throws 404 calling API

### ISSUE THREAD

**Issue by thaynes43** [benphelps/homepage#2110]
### Description

Homepage cannot query Authentik with this call:

[2023-10-04T01:30:08.511Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://xxxxxx:9000/api/v3/core/users?page_size=1

That call does not return anything. However http://xxxxxx:9000/api/v3/core/users/ returns a json object with all of the users. 

Homepage shows this:
<img width="186" alt="image" src="https://github.com/benphelps/homepage/assets/4860853/93cdd16f-6a4a-4978-a9cd-5f807ab661bc">

### Steps to reproduce

1. Configure Authentik Widget 
2. Reload homepage
3. Observe error

### homepage version

v0.7.0

### Installation method

Docker

### Configuration

```yaml
- Admin:
    - Authentik:
        href: http://xxxxxx:9000
        icon: authentik.png
        widget:
           key: xxxxxxxxxxxx
           type: authentik
           url: http://xxxxxx:9000
```

### Container Logs

[2023-10-04T01:29:45.396Z] error: <credentialedProxyHandler> HTTP Error 404 calling http://xxxxxxxxxx:9000/api/v3/core/users?page_size=1

### Troubleshooting

Troubleshooting tests are 404'd. Simply configuring authentik shows that an API call is being made that 404s in a browser but a simular call returns a response. 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
