### ISSUE TITLE
[Bug] CPU and Memory stats not displayed for pods in Kubernetes

### ISSUE THREAD

**Issue by dhop90** [benphelps/homepage#2115]
### Description

Currently a homepage service does not display cpu or memory stats for kubernetes pods.  This is both true for services defined in services.yaml and for auto service discovery using ingress annotations:

service.yaml configuration : 
    - SpeedTest:
        icon: speedtest-tracker.png
        description: Test internet upload and download speeds
        href: https://speedtest.<domain>.org
        ping: https://speedtest.<domain>.org
        statusStyle: dot
        namespace: speedtest
        app: speedtest
        podSelector: '' 
        widget:
          type: speedtest
          url: http://speedtest.speedtest.svc.cluster.local 

ingress annotation configuration:
  annotations:
    gethomepage.dev/container: speedtest
    gethomepage.dev/description: Test internet upload and download speeds
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Monitoring
    gethomepage.dev/href: https://speedtest.<domain>.org
    gethomepage.dev/icon: speedtest-tracker.png
    gethomepage.dev/name: SpeedTest
    gethomepage.dev/namespace: speedtest
    gethomepage.dev/app: speedtest
    gethomepage.dev/ping: https://speedtest.<domain>.org
    gethomepage.dev/podSelector: ''
    gethomepage.dev/statusStyle: 'dot'
    gethomepage.dev/weight: '1'
    gethomepage.dev/widget.type: speedtest
    gethomepage.dev/widget.url: http://speedtest.speedtest.svc.cluster.local

![Screenshot 2023-10-04 at 2 32 34 PM](https://github.com/benphelps/homepage/assets/371162/270bb0c9-3623-4d84-907e-7c20d98f851b)
 
left image is for the service defined in services.yaml
- no CPU or memory stats are displayed, instead it reports as being OFFLINE

right image is for the service defined in ingress annotation 
- note the gethomepage.dev/statusStyle: 'dot' does not work when defined in ingress annotation (separate issue)
- note that CPU and memory display zero values
   

### Steps to reproduce

configure service in service.yaml and kubernetes ingress per configuration - 

service.yaml configuration : 
    - SpeedTest:
        icon: speedtest-tracker.png
        description: Test internet upload and download speeds
        href: https://speedtest.<domain>.org
        ping: https://speedtest.<domain>.org
        statusStyle: dot
        namespace: speedtest
        app: speedtest
        podSelector: '' 
        widget:
          type: speedtest
          url: http://speedtest.speedtest.svc.cluster.local 

ingress annotation configuration:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production
    gethomepage.dev/container: speedtest
    gethomepage.dev/description: Test internet upload and download speeds
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/group: Monitoring
    gethomepage.dev/href: https://speedtest.<domain>.org
    gethomepage.dev/icon: speedtest-tracker.png
    gethomepage.dev/name: SpeedTest
    gethomepage.dev/namespace: speedtest
    gethomepage.dev/app: speedtest
    gethomepage.dev/ping: https://speedtest.<domain>.org
    gethomepage.dev/podSelector: ''
    gethomepage.dev/statusStyle: 'dot'
    gethomepage.dev/weight: '1'
    gethomepage.dev/widget.type: speedtest
    gethomepage.dev/widget.url: http://speedtest.speedtest.svc.cluster.local

### homepage version

v0.7.0 (c18caf9, Sep 29, 2023)

### Installation method

Docker

### Configuration

```yaml
Kubernetes cluster using docker

kubernetes.yaml 
---
# sample kubernetes config
#
mode: cluster

kubernetes deployment:
      containers:
        - name: homepage
          image: ghcr.io/benphelps/homepage:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: TZ
              value: America/Chicago
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: homepage
      serviceAccount: homepage
      automountServiceAccountToken: true
      securityContext: {}
      schedulerName: default-scheduler
      enableServiceLinks: true
```

### Container Logs

no log messages outputted 

### Troubleshooting

see steps to reproduce above

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
