### ISSUE TITLE
[Feature Request] Bookmark Icons

### ISSUE THREAD

**Issue by drag0n141** [benphelps/homepage#213]
Hi,

is it possible to add the function that we can set an icon instead of "abbr" for the bookmarks?

**Comment by BancarelValentin** [comment]
I know that work; do you mean material icons ? i haven't tried them but they might work as well

``` yaml
- Commons:
    - Proton mail:
        - icon: proton-mail
          href: https://mail.proton.me/
    - Proton calendar:
        - icon: proton-calendar
          href: https://calendar.proton.me/
    - Proton drive:
        - icon: proton-drive
          href: https://drive.proton.me/
```
