### ISSUE TITLE
[Wiki Enhancement] Docker Socket Proxy

### ISSUE THREAD

**Issue by C8opmBM** [benphelps/homepage#259]
To avoid security holes and to enhance security, additional info could be added on how to proxy docker socket connections.
The guide should include recommandation like
https://github.com/Tecnativa/docker-socket-proxy

Per linuxserver recommandation:

> Security Consideration:
> Mapping the docker.sock, especially in a publicly accessible container is a security liability. Since this mod only needs read-only access to the docker api, the recommended method is to proxy the docker.sock via a solution like [tecnativa/docker-socket-proxy](https://hub.docker.com/r/tecnativa/docker-socket-proxy), limit the access, and set DOCKER_HOST= to point to the proxy address.

LE: I will also give my working example

Here is how I run it  (here we will give permission to see other containers (CONTAINERS=1) and only read permission for api (POST=0)

```
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=0
    networks:
      - media
    restart: unless-stopped

  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    environment:
      - DOCKER_HOST=dockerproxy
    volumes:
      - /.config:/app/config
    ports:
      - 3000:3000
    networks:
      - media
    restart: unless-stopped
```

Then in docker.yml:

```
docker:
  host: dockerproxy
  port: 2375
```

**Comment by benphelps** [comment]
I think this is a better solution for most people than exposing the docker socket.  I'll get the wiki updated.  Thank you for the suggestion.

**Comment by Smiggel** [comment]
Found this issue and tried the example. For some reason I can not get it to work. De docker container fail on:
```
    networks:
      - media
```

I can run it with both containers without the networks. However, I notice then that when I continue the setup, that Homepage says all containers are offline. When I use the default option using the socket example from Homepage itself, it indicates all containers are online. 

For some reason using the proxy blocks something. Any ideas?

I run docker on a RPi4 CM4 with Raspberry PI OS and OpenMediaVault.

**Comment by C8opmBM** [comment]
I'm also on OpenMediaVault and this setup works perfectly on my end. 
You don't need to specify the network, that is my example setup, you should adjust it accordingly, but naturally they need to be on the same network to work. Or at least I believe this so.

**Comment by Smiggel** [comment]
Perhaps the version is the problem? What version are you using for the proxy? And does it have to be the same as the version for the homepage docker?

**Comment by C8opmBM** [comment]
The above snippet is in my yml file and is what I'm currently using. 
So both homepage and dockerproxy are on `:latest` tag

**Comment by Smiggel** [comment]
Still no luck here.

This is my proxy stack:
> ---
> version: "3.3"
> services:
>    dockerproxy:
>      image: ghcr.io/tecnativa/docker-socket-proxy:latest
>      container_name: dockerproxy
>      volumes:
>        - /var/run/docker.sock:/var/run/docker.sock:ro
>      environment:
>        - CONTAINERS=1
>        - POST=0
>        - IMAGES=1
>      restart: unless-stopped

And my homepage stack:

> ---
> version: "3.3"
> services:
>    homepage:
>      container_name: homepage
>      image: ghcr.io/benphelps/homepage:latest
>      environment:
>        - PUID=1000 #optional
>        - PGID=100 #optional
>        - DOCKER_HOST=dockerproxy
>      volumes:
>        - /srv/dev-disk-by-uuid-07b33097-17ec-4d5d-910e-f3e23e7d12e5/Configs/Homepage:/app/config # Make sure your local config directory exists
>        - /srv/dev-disk-by-uuid-07b33097-17ec-4d5d-910e-f3e23e7d12e5:/mnt/ssd:ro
>      ports:
>        - 3000:3000
>      restart: unless-stopped

I have added docker to the config:

> docker:
>   host: dockerproxy
>   port: 2375

I think I am missing something. All docker items have a grey indicator now. :-) Not sure what I am missing now.

**Comment by C8opmBM** [comment]
Are they both on the same network?
Did you enable portainer in OMV?
Check logs in dockerproxy and post them here.

**Comment by Smiggel** [comment]
> Are they both on the same network?
> Did you enable portainer in OMV?
> Check logs in dockerproxy and post them here.

1. Yes. Run all on the same machine.
2. Yes, I have added the stacks in Portainer
3. This is the log output:

> [WARNING] 288/145903 (1) : Can't open server state file '/var/lib/haproxy/server-state': No such file or directory
> Proxy dockerbackend started.
> Proxy dockerfrontend started.
> [NOTICE] 288/145903 (1) : New worker #1 (6) forked

**Comment by C8opmBM** [comment]
Regarding the network, I mean, you need to check that both containers run on the same docker network. Check that in portainer. This is why I specified the network in my config.
If they are on the same network, I do not know the reason why it doesn't work.
All my docker containers are in a single yml file (29 and about 4 use dockerproxy without issues, including homepage).
I'm also running SWAG for reverse proxy, if that should make any difference.

Sorry, maybe ask for more help on their github page.

**Comment by C8opmBM** [comment]
The log is fine, you have the same output as mine

```
10/16/2022 18:14:43
[WARNING] 288/151443 (1) : Can't open server state file '/var/lib/haproxy/server-state': No such file or directory
10/16/2022 18:14:43
Proxy dockerbackend started.
10/16/2022 18:14:43
Proxy dockerfrontend started.
10/16/2022 18:14:43
[NOTICE] 288/151443 (1) : New worker #1 (7) forked
10/16/2022 18:15:53
172.20.0.14:39730 [16/Oct/2022:15:15:53.768] dockerfrontend dockerbackend/dockersocket 0/0/0/37/43 200 71971 - - ---- 19/19/18/18/0 0/0 "GET /containers/json?all=true HTTP/1.1"
10/16/2022 18:15:53
172.20.0.14:39908 [16/Oct/2022:15:15:53.770] dockerfrontend dockerbackend/dockersocket 0/0/0/43/47 200 71971 - - ---- 18/18/17/17/0 0/0 "GET /containers/json?all=true HTTP/1.1"
```

**Comment by Smiggel** [comment]
> Regarding the network, I mean, you need to check that both containers run on the same docker network. Check that in portainer. This is why I specified the network in my config. If they are on the same network, I do not know the reason why it doesn't work. All my docker containers are in a single yml file (29 and about 4 use dockerproxy without issues, including homepage). I'm also running SWAG for reverse proxy, if that should make any difference.
> 
> Sorry, maybe ask for more help on their github page.

Hmmm the same network must be the problem. I don't see docker proxy in the network tab in Portainer. That could explain it.

**Comment by C8opmBM** [comment]
Try the default setup:

```
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - POST=0
    ports:
      - 127.0.0.1:2375:2375
    restart: unless-stopped
```
docker:
  host: 127.0.0.1
  port: 2375
