### ISSUE TITLE
[Bug] Layout option in settings now being ignored

### ISSUE THREAD

**Issue by ysarkain** [benphelps/homepage#265]
**Describe the bug**
Using the layout settings in settings.yaml no longer works to change a service group from vertical to horizontal.

**Expected behavior**
A service group designated as "row" style should display horizontally instead of vertically, in a column.

**Screenshots**
![20220924-000079](https://user-images.githubusercontent.com/14844795/192122234-24f4bb2a-ed0e-4041-a589-0816c9f8004a.png)
![20220924-000078](https://user-images.githubusercontent.com/14844795/192122235-5027b8a4-0e5d-4e70-96ac-dbe1327007e5.png)

**Configuration**
If applicable,
```yaml
# Please provide your service, widget or otherwise related configuration here
layout:
  Administration:
    style: row
    columns: 5
```

**Additional context**
Add any other context about the problem here. This includes things like:

Worked prior to upgrade of unraid docker container.  Not sure was the version number was before, now it displays 3.71.  Using the ghcr.io image.
