### ISSUE TITLE
[Bug] Service request time loading < 2min

### ISSUE THREAD

**Issue by 0n1cOn3** [benphelps/homepage#266]
**Describe the bug**
The request to load the service section take up to 2-3mins.

**Expected behavior**
Generate HTML static files on-the-fly

**Screenshot**
![image](https://user-images.githubusercontent.com/27576311/192123079-bf48dd7b-6bfd-48b2-bd87-a0ac0d4f463f.png)

**Configuration**
```
---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- The Private Cloud:
    - The Private Cloud Music:
        href: https://music.****.org/
        description: Jellyfin Music
        
- Homelab:
    - Adguard:
        href: https://adg.****.ch/
        description: Adguard
        
    - VPS:
        href: https://vps.****.ch/
        description: Proxmox
        
    - Uptime:
        href: https://mon.****.ch/
        description: Uptime Kuma

- hx:
    - Dashboard:
        href: https://****.ch/
        description: Homepage is 😎
```
**Additional context**
Add any other context about the problem here. This includes things like:

- Synology DSM 7.1
- Docker version 20.10.3, build 55f0773
