### ISSUE TITLE
[Bug] Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by ericlokz** [benphelps/homepage#270]
**Describe the bug**
[Bug] Application error: a client-side exception has occurred (see the browser console for more information).

**Screenshots**
![微信截图_20220926003903](https://user-images.githubusercontent.com/30315596/192154862-6d8c32c6-b289-483c-aaa7-aa4256aa0f22.png)

**Configuration**
The newly created container, the configuration is the default value
```

**Comment by ericlokz** [comment]
This error only appears when I'm on a desktop computer, it's normal for mobile devices.
I have the same error on 3 computers,The browser uses chrome, edge, the same situation

**Comment by JazzFisch** [comment]
Can you post your config/logs/homepage.log file as well as your **MASKED** docker.yml and services.yml files?

**Comment by jeremyjohn** [comment]
I have the same issue, I found out it's because it was checking with github for the latest release but github has a rate limit and was returning this error in they request

```
API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
Because of that the nextjs app is crashing completely.

Can we have a setting to disable checking of latest version?

**Comment by bverkron** [comment]
I am running into the same problem. I was able to spin up a Docker container for homepage fine the first time but after I hard to restart it later I now get this error every time and cannot use homepage :(

I tried completely blowing away the container, volume, everything and started from scratch. Still no luck.

**Comment by bverkron** [comment]
Spoke too soon. Worked for a while with `:main` and then I got the same error after a few refreshes while working on the yaml files. Switched to `:nightly` and same thing. Happens on Desktop and Mobile for me. :(

Portainer shows the image is `sha256:124f8f1c73aa6d5b4210d6ce2900c160e4d5749102df92d996aee9ec8784cccc` Not sure if you can correlate that back to your development. Let me know if you need more info.

**Comment by bverkron** [comment]
One more update this only happens when I use widgets. If I comment out all the widget sections it works. If I have even one enable it breaks with that error.

**Comment by benphelps** [comment]
Can you check if the process is being killed by the host system? 

```sh
dmesg -T | egrep -i 'killed process'
```

**Comment by bverkron** [comment]
> Can you check if the process is being killed by the host system?
> 
> ```shell
> dmesg -T | egrep -i 'killed process'
> ```

Output of that command is empty :(

**Comment by bverkron** [comment]
Interestingly the Speedtest widget seems to always work and not cause the crash if it's the only one enabled.

**Comment by bverkron** [comment]
Played around a bit more and the Portainer widget definitely crashes it consistently. I have several others that run fine (Radarr, Sonarr, Oveerseerr, Qbittorrent, etc) but as soon as I enable Portainer it crashes.  This is what the browser console shows for me (Safari)
 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19174503/193471439-555cdd5e-d1a5-47dc-8cf6-98c517219178.png">

and this is Chrome

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/19174503/193471490-174ce953-a32f-44b9-b3d5-f5e25084d36e.png">

Unlike the OP I get this on desktop and mobile. This is my entire config

```
# ---
# # For configuration options and examples, please see:
# # https://github.com/benphelps/homepage/wiki/Services

- Media:
    - Plex:
        icon: plex.png
        href: http://192.168.1.101:32400/web/index.html#!/settings/server/<redacted>/status/server-dashboard
        # description: Request manager
        container: plex
    - Overseerr:
        icon: overseerr.png
        href: http://192.168.1.101:5055/
        # description: Request manager
        container: overseerr
        widget:
            type: overseerr
            url: http://192.168.1.101:5055/
            key: <redacted>
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.1.101:8989
        # description: TV Series manager
        container: sonarr
        # widget:
        #   type: sonarr
        #   url: http://192.168.1.101:8989
        #   key: <redacted>
    - Radarr:
        icon: radarr.png
        href: http://192.168.1.101:7878
        # description: Movie manager
        container: radarr
        # widget:
        #   type: radarr
        #   url: http://192.168.1.101:7878
        #   key: <redacted>
    - Jackett:
        icon: jackett.png
        href: http://192.168.1.101:9117/UI/Dashboard
        container: jackett
    - Qbittorrent:
        icon: qbittorrent.png
        href: http://192.168.1.101:8080
        # description: Download manager
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://192.168.1.101:8080
            username: admin
            password: <redacted>
    - Pick A Movie:
        icon: synology-video-station.png
        href: https://pickamovieforme.com
        # description: Movie selection app

- Platforms:
    - Home Assistant:
        icon: home-assistant.png
        href: <redacted>
        # description: Home automation
    - Semaphore:
        icon: ansible.png
        href: http://192.168.1.101:3003/
        # description: DevOps tasks
        container: semaphore
    # - Jenkins:
    #     icon: jenkins.png
    #     href: http://192.168.1.101:8085
    #     # description: DevOps tasks
    #     container: jenkins
    - Syncthing Master Control:
        icon: syncthing.png
        href: http://192.168.1.101:8384
        container: syncthing
    - Syncthing NAS:
        icon: syncthing.png
        href: https://192.168.1.219:8384

- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: http://192.168.1.101:9009
        # description: Container manager
        container: portainer
        widget:
            type: portainer
            url: http://192.168.1.101:9009
            env: 1
            key: <redacted>
    - Docker Stats:
        icon: docker.png
        href: http://192.168.1.101:5555
        container: docker-container-stats
    - EdgeRouter X:
        icon: router.png
        # icon: unifi.png
        href: https://192.168.1.1
        # description: Network management
    - NAS:
        icon: qnap.png
        href: https://192.168.1.219/cgi-bin/
        # description: Network Attached Storage
    - Speedtest:
        icon: speedtest-tracker.png
        href: http://192.168.1.101:8888
        container: speedtest-tracker
        # widget:
        #     type: speedtest
        #     url: http://192.168.1.101:8888
```
