### ISSUE TITLE
API error on Transmission + qBittorrent

### ISSUE THREAD

**Issue by chuckiton** [benphelps/homepage#271]
Installed + run on bare metal (Debian 11, Rpi 4) using yarn.

config looks as follows:
```
- Torrent Clients:
    - Transmission:
        icon: transmission
        href: http://***:9091/
        description: Transmission
        widget:
            type: transmission
            url: http://****:9091/
            username: ****
            password: ****
    - qBittorrent:
        icon: qbittorrent
        href: http://****:9090/
        description: qBittorrent
        widget:
            type: qbittorrent
            url: http://****:9090/
            username: ***
            password: ***
```

while qBittorrent is giving a 404:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (proxy, line 0)`
there is nothing in the console to show why transmission should be failing. I have whitelisted localhost and the local subnet in qbittorrent (I don't think transmission has this functionality?)
