### ISSUE TITLE
[Widget Request] CloudFlare Tunnel Docker Widget

### ISSUE THREAD

**Issue by PricelessToolkit** [benphelps/homepage#288]
Hi, I would like to say a huge thank you for a very beautiful homepage, and I have a small request It would be very nice if there was a widget that shows the status of the tunnel "Up or Down", External IP, and so on.
In reality, I don’t know what data can be taken from the container.
Thanks

**Comment by huzzyz** [comment]
I don't see any real advantage of seeing the ip but the status seems like a nice idea which can be easily implemented right now.
![Screen Shot 2022-09-28 at 21 29 41](https://user-images.githubusercontent.com/69323208/192849747-21d003b7-93c8-4733-b429-9d6432d6f418.png)

```
- Cloudflared:
        icon: cloudflare.png
        href: https://dash.teams.cloudflare.com/*REDACTED*
        description: cloudflared
        container: cloudflared
```
