### ISSUE TITLE
[Bug] settings.yaml values aren't being used

### ISSUE THREAD

**Issue by andjones132** [benphelps/homepage#294]
**Describe the bug**

I have installed using docker (see docker-compose.ymal below). I cannot get homepage to load my settings. Everything is red, pallet only shows red colors. My services.yaml and widges.yaml are loading fine, but it is ignoring my settings.yaml. I have taken the contaner down and force-recreate, but still is not pickup settings.yaml in my config folder. 

FYI. Not sure if it matters, but I am using and nfs volume for storing my config. I have made sure that chown -R 1000:1000, which is the UID:GID of my my default user and is working fine for all my other containers. It does have access because if I change the services.yaml file it picks up my changes. Also, as you can see from my docker-compose.yaml below that I am useing Traefik as my reverse proxy. 

**Expected behavior**

I would expect that it would load the settings. yaml 

**Screenshots**

![image](https://user-images.githubusercontent.com/40303400/192574085-5dcba60f-7234-488e-9f56-1fbea4363f95.png)

**Configuration**

- docker-compose.yaml:
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
    networks:
      - traefik_net
    # ports:
    #   - 3000:3000
    volumes:
      - /mnt/docker/remote/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    labels:
      traefik.enable: true
      traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.homepage-secure.entrypoints: https
      traefik.http.routers.homepage-secure.rule: Host(`homepage.local.astrophotons.net`)
      traefik.http.routers.homepage-secure.service: homepage
      traefik.http.routers.homepage-secure.tls: true
      traefik.http.routers.homepage.entrypoints: http
      traefik.http.routers.homepage.middlewares: homepage-https-redirect
      traefik.http.routers.homepage.rule: Host(`homepage.local.astrophotons.net`)
      traefik.http.services.homepage.loadbalancer.server.port: 3000
      traefik.docker.network: traefik_net

networks:
  traefik_net:
    external: true
```
- bookmarks.yaml is default
- widgets.yaml is default
- docker.yaml set to with my docker host ubutu server running proxmox

```
my-docker:
  host: 192.168.1.115
  port: 2375

docker:
  socket: /var/run/docker.sock
```

- services.yaml:
```
---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Home Assistant:
    - Home Assistant:
        href: http://192.168.1.50:8123/lovelace/default_view
        description: Home Assistant

- Network:
    - Unifi:
        href: https://unifi.ui.com/dashboard
        description: UDM Pro

- Home Lab:
    - Portainer:
        href: https://portainer.local.astrophotons.net/#!/home
        description: Portainer Traefik Server
```

- settings.yaml:

```
title: Andrew's Homepage
theme: dark
color: grey
```

**Additional context**
Add any other context about the problem here. This includes things like:
 - Service version or API version
 - Docker version:
        Docker version 20.10.18, build b40c2f6
 - Deployment method:
       docker-compose up -d --force-recreate
 - Sample YAML configurations:
       see above
