### ISSUE TITLE
[Feature Request] Custom health checks

### ISSUE THREAD

**Issue by bverkron** [benphelps/homepage#311]
**Is your feature request related to a service? Please describe.**
I love widgets in general and the status icon you get when using the docker integration and specifying the container name but I would also love it if there were a way to do custom health checks (and other things) for services that don't support widgets and don't run in a container.

**Is your feature request related to a problem? Please describe.**
Not really.

**Additional context**
I imagine something similar to the health checks feature available for docker compose files but simplified a little
https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck

Example:
```
healthcheck:
  test: ["curl -s -o /dev/null -w "%{http_code}" http://google.com"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  success: "200"
```

Effectively it could allow you to execute arbitrary shell commands and then look for a specific result that indicates success. You could even have a `failure:` property that would indicate a confirmed failure (rather than being ambiguous based on a lack of a specific result).

This could actually be quite powerful and leverage for lots of different things too if implemented the right way. Lots of potential here :)
