### ISSUE TITLE
[Feature Request] Tubearchivist widget

### ISSUE THREAD

**Issue by thisisawesome1994** [benphelps/homepage#319]
**Is your feature request related to a service? Please describe.**
A clear and concise description of what you would like to see from this service.
Yes, I would like to have a widget for Tubearchivist (from bbilly1)
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I would like it if [...]
No, just a feature request.
**Additional context**
I think my request is clear.

**Comment by ItsNoted** [comment]
I second this! Would be great to see number of subs, total videos etc.

**Comment by shamoon** [comment]
Closed by #471

**Comment by Nonoss117** [comment]
![image](https://user-images.githubusercontent.com/79055577/202771184-b6652a1c-6828-4c2d-825b-fd82eeacb57f.png)

**Comment by ItsNoted** [comment]
> ![image](https://user-images.githubusercontent.com/79055577/202771184-b6652a1c-6828-4c2d-825b-fd82eeacb57f.png)

I tried adding this as a widget and it didn't work. Is it supported on the main branch? If not, How can I get it working? Here is my config in services.yaml.

    - Tube Archivist:
        icon: tube-archivist.png
        href: http://192.168.1.82:8383
        description: Your self hosted YouTube media server
        widget:
          type: tubearchivist
          url: http://192.168.1.82:8383
          key: 1aaec43cca9231e982b9c326e771c4c40e14f413
          fields: ["downloads", "videos", "channels", "playlists"]

**Comment by Nonoss117** [comment]
You can have a look here : https://github.com/benphelps/homepage/pull/471

I'm not pro, but I think you must have an https url for the widget. Just like the example
``` yaml
    - Tube Archivist:
        icon: tube-archivist.png
        href: https://tubearchivist.example.com
        description: Your self hosted YouTube media server
        widget:
          type: tubearchivist
          url: https://tubearchivist.example.com
          key: <apikey>
          fields: ["downloads", "videos", "channels", "playlists"]
```
That's the case for me.
`http://IP:PORT` doesn't work for me either
