### ISSUE TITLE
[Bug] Prowlarr fields widget property

### ISSUE THREAD

**Issue by Nonoss117** [benphelps/homepage#320]
**Describe the bug**

I must doing something wrong, but I'm unable to configure Prowlarr fields widget propoery
As soon as I add the line:
```yaml
fields: ["indexers", "grabs", "queries", "fail grabs", "fail queries"]
```
All the fields are unvisible.
I tried adding only one field,
```yaml
fields: ["indexers"]
```
But same behavior, the `indexers` field is not visible

**Configuration**

```yaml
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.1.100:9696/
        server: nas-docker
        container: prowlarr
        description: Gestionnaire d'indexeur/proxy
        widget:
          type: prowlarr
          fields: ["indexers", "grabs", "queries", "fail grabs", "fail queries"]
          url: http://192.168.1.100:9696
          key: 3de***************************************
```

I tried with `latest` and `nightly (a63f71d, 2 oct. 2022)`
Nothing in the logs files
