### ISSUE TITLE
[Bug] Radarr widget returns "API Error" unclear why

### ISSUE THREAD

**Issue by bverkron** [benphelps/homepage#324]
**Describe the bug**
The Radarr widget briefly shows the 3 placeholder boxes for Wanted, Queued, Movies, then immediately flips to "API Error"

**Expected behavior**
Shows the Wanted, Queued, Movies information much like Sonarr does.

**Screenshots**
<img width="401" alt="image" src="https://user-images.githubusercontent.com/19174503/193468453-9bd3a5a2-68a8-433c-b7cf-7eb315cf5732.png">

**Configuration**
If applicable,
```yaml
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.1.101:8989
        # description: TV Series manager
        container: sonarr
        widget:
          type: sonarr
          url: http://192.168.1.101:8989
          key: <redacted>
    - Radarr:
        icon: radarr.png
        href: http://192.168.1.101:7878/
        # description: Movie manager
        container: radarr
        widget:
          type: radarr
          url: http://192.168.1.101:7878/
          key: <redacted>
```

**Additional context**
I have triple checked the API Key and re-copy/pasted it multiple times. I also know the key works because Overseerr uses it successfully with Radarr to send requests and pull content.

homepage: `nightly (a63f71d, Oct 1, 2022)`

Radarr:
```
Version: 4.2.4.6635
Package Version: 4.2.4.6635-ls153 by [linuxserver.io](https://linuxserver.io/)
```
Docker: `Docker version 20.10.18, build b40c2f6`
Deployment method: docker compose (via Portainer)
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:main
    container_name: homepage
    ports:
      - 80:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver      
    volumes:
      - /home/master/homepage/mount_app_config:/app/config # Make sure your local config directory exists
      - /media/ext_storage:/ext_storage      
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```

I think the `error: undefined` entries are from something the Radarr issue. They _seem_ to stop when I disable the Radarr widget
```
[2022-10-02T17:43:59.237Z] error: undefined
[2022-10-02T17:43:59.437Z] error: (node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[2022-10-02T17:44:04.345Z] error: undefined
[2022-10-02T17:44:19.397Z] error: undefined
[2022-10-02T17:44:32.327Z] error: undefined
[2022-10-02T17:44:35.992Z] error: undefined
[2022-10-02T17:44:38.237Z] error: undefined
```

There are no logs entries on the Radarr side. I wiped those logs before refreshing, thus I don't think homepage is even sending an API request to radarr. Either that or Radarr is accepting an serving a valid response and homepage is not handling it properly. If Radarr was receiving the request from homepage and there was a problem it should be in the Radarr logs, I imagine.
