### ISSUE TITLE
[Bug] Docker Status expansion shows nothing

### ISSUE THREAD

**Issue by Rufmord** [benphelps/homepage#334]
**Describe the bug**
The docker status integration of services does not work anymore. In the `config/logs/homepage.log` there is logged nothing. The console of the browser only shows:
```
GET https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/whiteboard.png (this is a 404 Not Found error)
unreachable code after return statement
```

**Expected behavior**
The box should expand and show some information about the container, like read and writes.

**Screenshots**
If clicking on the green dot nothing happens.
![grafik](https://user-images.githubusercontent.com/60900426/193919933-ae735837-a295-433e-ad0e-f7890efc5b34.png)

**Configuration**
The docker container of homepage has the docker sock as volume.
```yaml
- /var/run/docker.sock:/var/run/docker.sock
```
The services.yaml looks like this:
```yaml
- Services:
    - Authentik:
       icon: authentik
       href: https://authentik.domain.tld
       description: Auth
       container: authentik_server
       widget:
         type: authentik
         url: http://authentik_server
         key: api_token
```

**Additional context**
 - Service version or API version: v0.4.0 (de4ce73, Oct 1, 2022)
 - Docker version: 20.10.17
 - Deployment method: docker compose

**Comment by JazzFisch** [comment]
You are missing the `server` property in your YAML.  It should look like:
```yaml
- Services:
    - Authentik:
       icon: authentik
       href: https://authentik.domain.tld
       description: Auth
       server: my-local-docker
       container: authentik_server
       widget:
         type: authentik
         url: http://authentik_server
         key: api_token
```

**Comment by Rufmord** [comment]
It worked a week ago without the `server` attribute. Now when I add this, the container is shown as offline with a grey dot and the expanded box shows also that the service is offline.
![grafik](https://user-images.githubusercontent.com/60900426/193934559-b4bb886f-e99e-4402-a87b-2ef5f4192e90.png)
I checked with `docker ps`, it is online. What am I missing?

**Comment by xenogear74** [comment]
What does your docker yaml look like?

**Comment by Rufmord** [comment]
It looks like this. There are labels for traefik, but these are irrelevant I think.
```yaml
  authentik_server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik_server
    restart: unless-stopped
    command: server
    networks:
      - my-net
    volumes:
      - some/dir:/dir
    environment:
      - ENVIROMENT_VARS
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    networks:
      - my-net
    volumes:
      - some/dir/homepage/config:/app/config
      - some/dir/icons/pn/png:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
```
