### ISSUE TITLE
Storage info widget shows wrong capacity

### ISSUE THREAD

**Issue by wazzirr** [benphelps/homepage#337]
**Describe the bug**
Storage info widget shows only about 100GB capacity, mounted drive has more than 7 TiB. I don't know if it's a bug, or I'm doing something wrong

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/114355224/194012007-b7d4bf83-4150-4b78-9d84-ff2b922696d0.png)
![Screenshot_2](https://user-images.githubusercontent.com/114355224/194012395-5fc2fccd-f6f2-4c64-b667-b70a8097cb6c.png)
![Screenshot_3](https://user-images.githubusercontent.com/114355224/194012405-5ce5ded1-c40c-44d7-ba31-19b38ffd733e.png)

**Configuration widgets.yaml**
```
- resources:
    label: System
    cpu: true
    memory: true

- resources:
    label: Storage
    disk:
      - /
      - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add/DATA

- search:
    provider: duckduckgo
    focus: true
    target: _blank

- openweathermap:
    label: Teplice
    latitude: 50.644459
    longitude: 13.835284
    units: metric
    apiKey: <apikey>
    cache: 5
```
**Docker-compose**
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    network_mode: "bridge"
    ports:
      - 3000:3000
    volumes:
      - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add/DATA/docker/homepage:/app/config
      - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add/DATA/docker/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add/DATA
```

**Comment by benphelps** [comment]
That's probably due to the mount path, try something like this.

```yaml
volumes:
  - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add/DATA:/data
```
and
```yaml
- resources:
    label: Storage
    disk:
      - /
      - /data
```

**Comment by trythatagain** [comment]
It looks as though you're using OMV, same as me. I think you've got the drives and folders mixed up.
In your docker compose file, - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add/DATA is a folder and not a drive. So I'd suggest for that drive use - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add :/DATA


```
- resources:
    label: Storage
    disk:
      - /
      - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add/DATA
```
For the above I suggest something like below, I have 5 different drives showing and it works well.
```
#Show drives and free space
- resources:
    expanded: true
    label:  Storage
    disk: / # Root drive
    disk: /DATA # Data drive
```

**Comment by wazzirr** [comment]
> That's probably due to the mount path, try something like this.
> 
> ```yaml
> volumes:
>   - /srv/dev-disk-by-uuid-08ff201f-3496-4131-9034-d26847434add/DATA:/data
> ```
> 
> and
> 
> ```yaml
> - resources:
>     label: Storage
>     disk:
>       - /
>       - /data
> ```

That worked, thanks :)
![Screenshot_1](https://user-images.githubusercontent.com/114355224/194123771-79f28438-782e-4767-ba44-b5dbcab811b2.png)
btw. it would be good, if the total capacity was displayed too.. sth like free space/total space, or free space above the line and total space under the line :)

**Comment by Nonoss117** [comment]
May be this help:
in `widgets.yaml` file
add:
```yaml
    expanded: true
```

Example:
```yaml
- resources:
    label: Array Disks
    expanded: true
    disk:
        - /disk1
        - /disk2
        - /disk3
```
![image](https://user-images.githubusercontent.com/79055577/194136533-c4238c82-4d67-41a4-b3c8-18bf26d33ac2.png)
