### ISSUE TITLE
[Bug] Missingweather...

### ISSUE THREAD

**Issue by juanmanuelbc** [benphelps/homepage#338]
**Describe the bug**
Weather widget (configured with a "provider" and its API key) is missing...

**Expected behavior**
Weather widget working correctly...

**Screenshots**
![imatge](https://user-images.githubusercontent.com/13131391/194036911-1c8f3053-5ff7-4b2c-bdc4-3db0dc5f345c.png)

**Configuration**
```yaml
providers:
    weatherapi: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

- weather:
    label: xxxxx
    latitude: xx.xxxxx
    longitude: x.xxxxx
    units: metric
    provider: weatherapi
    cache: 5
```

**Additional context**
 - Service version or API version: v0.4.4 (88c7743, 5 oct 2022)
 - Docker version: 20.10.3, build 55f0773
 - Deployment method: docker run
