### ISSUE TITLE
[Bug] New service tile when Docker integration is enabled

### ISSUE THREAD

**Issue by Buddinski88** [benphelps/homepage#365]
**Describe the bug**
I have configured the Docker integration according to the instructions (docker-compose and docker.yml). The status of the containers is displayed correctly, but I get a new tile (see highlighted in red) whose origin I do not understand.

**Expected behavior**
The status of the container is displayed correctly, but no new tile is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/50332516/194810384-65ca5463-e2c7-4c93-b8dd-5fcae14491be.png)

**Configuration**
docker-compose
```yaml
version: '3.3'
services:
    homepage:
        image: ghcr.io/benphelps/homepage:latest
        container_name: homepage
        ports:
            - 3000:3000
        volumes:
            - /home/buddy/homepage/config:/app/config
            - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```
config/docker.yml
```yaml
local:
#  host: 192.168.178.7
#  port: 2375
  socket: /var/run/docker.sock
```
part of config/services.yml 
```yaml
- Management:
    - Portainer:
        icon: portainer.png
        href: https://portainer.mylocalurl.de
        description: Container Management
        server: local
        container: portainer
        widget:
          type: portainer
          url: https://portainer.mylocalurl.de
          env: 2
          key: ptr_*****
```

**Additional context**
 - Homepage version v0.4.9 (94a518f, Oct 8, 2022)
 - Docker version 20.10.16, build aa7e414
 - docker-compose version 1.29.2, build 5becea4c
