### ISSUE TITLE
[Bug] - Missign widget type: unifi

### ISSUE THREAD

**Issue by scorpio2k2** [benphelps/homepage#368]
**Describe the bug**
After I configured the unifi as described on wiki I get "Missign widget type: unifi" mesage in the widget. 

**Expected behavior**
To work as described in wiki. 

**Configuration**
If applicable,
```yaml
    - Unifi Dream Machine SE:
        icon: unifi.png
        href: http://192.168.1.1
        description: Unifi
        widget:
          type: unifi
          url: https://192.168.1.1:443
```

**Additional context**
Using unifi dream machine SE.
