### ISSUE TITLE
[Bug] Traefik widget api error

### ISSUE THREAD

**Issue by Buddinski88** [benphelps/homepage#376]
**Describe the bug**
I would like to use the widget for traefik, but unfortunately I get an `API Error`.

**Expected behavior**
The widget displays the possible data that was requested via the API.

**Screenshots**
![image](https://user-images.githubusercontent.com/50332516/195261938-ea7e633a-8f3f-4633-b29f-fb288720377a.png)

**Configuration**
services.yml
```yaml
    - Traefik:
        icon: traefik.png
        href: https://traefik.local.myurl.de
        description: Network Proxy Manager
        widget:
          type: traefik
          url: https://traefik.local.myurl.de
```

**Additional context**
Traefik version 2.8.4 (Traefik is protected via user/pw, after the login there is still the issue)
Homepage version nightly (2bdd9ea, Oct 12, 2022)
Docker version 20.10.16, build aa7e414
docker-compose version 1.29.2, build 5becea4c
