### ISSUE TITLE
[Feature Request] Open tab in same window

### ISSUE THREAD

**Issue by Facinorous-420** [benphelps/homepage#385]
Link to original issue:
https://github.com/benphelps/homepage/issues/314

        You can change this, https://github.com/benphelps/homepage/wiki/Settings#link-target

_Originally posted by @benphelps in https://github.com/benphelps/homepage/issues/314#issuecomment-1264436943_
      

I appreciate the link! I saw this previously, but I could not seem to figure out how to make this work for only a specific bookmark/service which lead me to create this issue. I am sorry, I should have been more specific that I was talking about individual bookmarks/services rather than them all globally.

An example which would be cool to be able to use per-service/bookmark would be something like this:

```
- Apps:
    - Grafana:
        href: https://example.com/
        icon: grafana
        description: System statistics and graphs
        server: docker2
        target: _self
```

rather than adding the `target` in settings which applies it to every link.
