### ISSUE TITLE
[Bug] npm widget provides an error

### ISSUE THREAD

**Issue by OpieO1** [benphelps/homepage#387]
**Describe the bug**
When configuring my service.yml for my npm mapping, I get the following error displayed inside homepage:

`TypeError: o.filter is not a function

    at s (http://192.168.2.6:3000/_next/static/chunks/1026.2bd2e3174a8ad99c.js:1:882)
    at h (http://192.168.2.6:3000/_next/static/chunks/4931-ff1596ae4f86f149.js:1:14837)
    at n (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:2657)
    at G (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:7161)
    at div
    at li
    at Z (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:7796)
    at ul
    at C (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:10463)
    at div
    at I (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:10750)
    at div
    at div
    at K (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:18783)
    at n (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:2657)
    at http://192.168.2.6:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:82739
    at V (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:16842)
    at div
    at div
    at Y (http://192.168.2.6:3000/_next/static/chunks/pages/index-c92dc59c38eb6258.js:1:20975)
    at a (http://192.168.2.6:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:73306)
    at s (http://192.168.2.6:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:73863)
    at u (http://192.168.2.6:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:72738)
    at http://192.168.2.6:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:82739
    at http://192.168.2.6:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:72188
    at F (http://192.168.2.6:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:7872)
    at n (http://192.168.2.6:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:67948)
    at r (http://192.168.2.6:3000/_next/static/chunks/main-d2b206db40ae9853.js:1:6948)
    at Y (http://192.168.2.6:3000/_next/static/chunks/main-d2b206db40ae9853.js:1:9190)
    at ie (http://192.168.2.6:3000/_next/static/chunks/main-d2b206db40ae9853.js:1:11830)`

**Screenshots**
Screenshot attached
![npmerror](https://user-images.githubusercontent.com/88811484/195748947-99092260-7d9b-4509-8530-e0ab4dbeef5c.png)

**Configuration**
```yaml
# My configuration is as followed
- Network:
    - NPM:
        icon: nginxproxymanager.png
        href: http://npm.mydomain.net
        description: Easy to manage reverse proxy.
        server: my-remote-docker
        container: nginx-proxy-manager_app_1
        widget:
            type: npm 
            url: http://npm.mydomain.net
            username: user@example.com
            password: [redacted]

```

**Additional context**
Add any other context about the problem here. This includes things like:
 - Homepage version: v0.4.9 (94a518f, Oct 8, 2022)
 - Docker version 20.10.3

 - Deployment method - docker composer/portainer
