### ISSUE TITLE
Services Widget

### ISSUE THREAD

**Issue by trackermb** [benphelps/homepage#41]
Hi having an issue with services widgets.  When I test locally on 192. address I can hit sonar, Speedtest and rutorrent for example.

I was planning to use the local ip and port as I have authelia and is would then bypass it.  

```
- Media Services:
    - ruTorrent:
       icon: rutorrent.png
       href: https://rutorrent.mydomain.com
       description: Torrent Client
       container: rutorrent
       widget:
          type: rutorrent
          url: http://192.168.1.10:8080
          username: false # optional, false if not used
          password: false # optional, false if not used
    - Sonarr:
       icon: sonarr.png
       href: https://sonarr.mydomain.com
       description: Series management
       container: sonarr
       widget:
          type: sonarr
          url: http://192.168.1.10:8989
          key: <api key>
    - Radarr:
       icon: radarr.png
       href: https://radarr.mydomain.com
       description: Movie manager
       container: radarr
```
But when I access it via domain address rutorrent pulls fine but sonarr and Speedtest just show api error 

Any ideas why it can't access local ip when accessed in this way.
