### ISSUE TITLE
[Bug] update from latest version in docker no latest 

### ISSUE THREAD

**Issue by therus000** [benphelps/homepage#410]
**I'm using docker to deploy the app**
when i try to upload the latest image and up the container 
this image I use:
ghcr.io/benphelps/homepage:latest

after up the app i got notification that i not  got the latest version 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48754322/196664110-b31a9892-56a5-4210-aaee-e0ddf4084522.png)

![image](https://user-images.githubusercontent.com/48754322/196664519-9508d554-cdcc-41eb-b036-660018fa2ec9.png)

**Configuration**

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3033:3000
    volumes:
      - homepage-data:/app/config # Make sure your local config directory exists
      - homepage-app:/app # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped 
volumes:
  homepage-data:
    driver: local
  homepage-app:
    driver: local
```
