### ISSUE TITLE
Portainer Widget HTTPS

### ISSUE THREAD

**Issue by Samurai1201** [benphelps/homepage#417]
**Describe the bug**
Portainer Widget doesnt work as intended, either due to https, or not accepting my env input

**Expected behavior**
Portainer should display as a widget

**Additional context**
- Happens with both "latest" image
- Docker version 20.10.19
- Deployment method: Docker-compose/portainer stack

Config lines:
```
- Portainer:
            icon: /icons/portainer.png
            description: Docker verwalten
            href: https:// -IP- :9443
            widget:
              type: portainer
              url: https:// -IP- :9443
              env: 2
              key: - Redacted -
```

Error message:

```
Something went wrong.
TypeError: l.filter is not a function

c@http://172.28.110.158:3000/_next/static/chunks/8019.fdf32b58caf74612.js:1:880
5589/y/h<@http://172.28.110.158:3000/_next/static/chunks/4931-ff1596ae4f86f149.js:1:14837
n@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:2657
G@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:7391
div
li
Z@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:8521
ul
C@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:11086
div
I@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:11373
div
div
K@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:19712
n@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:2657
6747/G<@http://172.28.110.158:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:82737
V@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:17771
div
div
Y@http://172.28.110.158:3000/_next/static/chunks/pages/index-30b83ae3c35e861e.js:1:21904
a@http://172.28.110.158:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:73304
s@http://172.28.110.158:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:73861
u@http://172.28.110.158:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:72736
6747/G<@http://172.28.110.158:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:82737
6207/t.default<@http://172.28.110.158:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:72186
F@http://172.28.110.158:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:7870
n@http://172.28.110.158:3000/_next/static/chunks/pages/_app-fc77031352f30888.js:1:67946
r@http://172.28.110.158:3000/_next/static/chunks/main-d2b206db40ae9853.js:1:6949
Y@http://172.28.110.158:3000/_next/static/chunks/main-d2b206db40ae9853.js:1:9188
ie@http://172.28.110.158:3000/_next/static/chunks/main-d2b206db40ae9853.js:1:11828
```
