### ISSUE TITLE
[Bug] Unable to use Widget features with applications on Tailscale VPN Network

### ISSUE THREAD

**Issue by dandocmando** [benphelps/homepage#424]
**Describe the bug**
I am using tailscale to access my radarr and other containers, I am unable to enable the widget menu and the api obviously isn't able to access my vpn network

**Expected behavior**
I would like some way to use the widget feature with applications on my tailscale network. I normally am able to use docker internal DNS and avoid this issue, if that was able to be implemented that would fix it, that would bypass your proxy server though. Cheers

**Configuration**
    - Radarr:
        icon: radarr.png
        href: http://tailscaleNetwork:7878
        description: Radarr
        server: docker
        container: radarr
        widget:
            type: radarr
            url: http://tailscaleNetwork:7878
            key: apihere
```

**Additional context**
Latest versions

**Comment by shamoon** [comment]
I agree accessing things via docker network would be cool, this is a feature request more than a bug I think

**Comment by shamoon** [comment]
So that should work, thats how I do it, maybe you need a traefik router for internal requests, e.g.:

```yaml
      # Internal
      - traefik.http.routers.traefik-internal.rule=Host(`traefik`)
      - traefik.http.routers.traefik-internal.service=api@internal
      - traefik.http.routers.traefik-internal.middlewares=chain-no-auth
      - traefik.http.routers.traefik-internal.entrypoints=websecure
      - traefik.http.routers.traefik-internal.tls=true
      - traefik.http.routers.traefik-internal.priority=99
```

then in homepage I set the traefik url as `https://traefik:443`

**Comment by SethranKada** [comment]
Thanks for making an issue for this, I've been having the same problem and I thought I'd just setup everything wrong. nice to know it's just not been implemented yet. Are there any workarounds? I don't use authelia or traefik so I don't think you're solution would work for me.

**Comment by shamoon** [comment]
Just to clarify, if homepage and the container are on the same _user-created_ network, http://containername:port should work, theres no issue there. Im not clear if OP has the same or a different issue. To check, you can `exec` into the homepage container and try to ping another container that way e.g. `ping containername`

**Comment by SethranKada** [comment]
I've got homepage and all my other containers on the same host machine, except pi-hole. The only widget I've got working so far is for pi-hole, once I realized that I would need to use it's non-tailscale ip address. Everything else is broken. I tried to exec into my homepage docker and ping the other containers, but that didn't work either. 
results:
`sudo docker exec homepage ping http://overseerr.domain.net`
`ping: bad address 'overseerr.domain.net'`

`sudo docker exec homepage ping http://ip.address`
`ping: bad port '//ip.address/'`
^ it didn't print 'http:' for some reason

`sudo docker exec homepage ping http://ip.address:port`
`ping: bad address 'http://ip.address:port/`
^ it did here

`sudo docker exec homepage ping http://plex:32400/`
`ping: bad address 'http://plex:32400/'`

`sudo docker exec homepage ping plex`
`ping: bad address 'plex'`

So as far as I can tell, it just can't connect between docker stuff. What do I need to change to fix this?

**Comment by shamoon** [comment]
Its not about same host machine, they need to be on the same _user-created_ docker network, sorry I thought I included a link to the docs https://docs.docker.com/config/containers/container-networking/

If you cant ping a container that way then homepage cant reach it that way, so yea you need to sort that out. `ping` by the way, doesnt take a port or a protocol (http://), you just ping a server, but yes when configured correctly, `ping plex` should work

**Comment by SethranKada** [comment]
Thanks for the explanation, I'll get that sorted out before I continue any further.

**Comment by JazzFisch** [comment]
Here is a very chopped up version of my docker-compose.yml file that gives an example to what shamoon is talking about:
```yaml
version: "3.8"

########################### NETWORKS
networks:
  traefik-internal:
    name: traefik-internal
    driver: bridge
    ipam:
      config:
        - subnet: "10.11.12.1/24"
          gateway: "10.11.12.1"


########################### SERVICES
# All services / apps go below this line
services:
  # Homepage - Unified Frontend
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    networks:
      traefik-internal:
        aliases:
          - homepage.docker.internal
          - homepage

  # Radarr - Movie management
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    networks:
      traefik-internal:
        aliases:
          - radarr.docker.internal
          - radarr
```
