### ISSUE TITLE
[Bug] Double widgets display same data

### ISSUE THREAD

**Issue by xNVrAojkVY** [benphelps/homepage#426]
**Describe the bug**
If you use two Pi-Hole instances, both widgets will display the same data points.
If I remove the Pi the widget is pulling from from the config, it switches to the other.  
Also happens with qbittorrent and I guess with every other double widget aswell. 

**Expected behavior**
Show the real data for each Pi-Hole.

**Screenshots**
![1](https://user-images.githubusercontent.com/116388587/197280308-1328d7cd-22ed-4578-97d0-4fef1b65e4d6.png)

**Configuration**

---
- Network:
    - PiHole:
        icon: pihole.png
        href: http://192.168.50.101/admin/
        widget:
          type: pihole
          fields: ["queries", "blocked"]
          url: http://192.168.50.101

    - PiHole:
        icon: pihole.png
        href: http://192.168.50.102/admin/
        widget:
          type: pihole
          fields: ["queries", "blocked"]
          url: http://192.168.50.102

**Additional context**
Im using the newest docker build. 

Thanks. :)

**Comment by JazzFisch** [comment]
You need to use different names for the widget.  So, you need: `- Pihole:` and something like `- Pihole2:`

```yaml
- Network:
    - PiHole:
        icon: pihole.png
        href: http://192.168.50.101/admin/
        widget:
            type: pihole
            fields: ["queries", "blocked"]
            url: http://192.168.50.101/

      - PiHole2:
        icon: pihole.png
        href: http://192.168.50.102/admin/
        widget:
            type: pihole
            fields: ["queries", "blocked"]
            url: http://192.168.50.102/
```
