### ISSUE TITLE
[Bug] Jackett API Error

### ISSUE THREAD

**Issue by henryxrl** [benphelps/homepage#437]
I somehow just can't make the Jackett widget work. The webpage shows this,

![image](https://user-images.githubusercontent.com/7662954/197426672-fdf4d5a3-df44-4861-ab7d-dd6358f3a69f.png)

 In the `services.yaml` file, I have,

```
- Jackett:
        icon: jackett
        href: http://192.168.50.110:9117
        description: Resource indexer
        server: local
        container: jackett
        widget:
                type: jackett
                url: http://192.168.50.110:9117
```

This URL does work. Also, there is NO error message shown in the console when the webpage load. Any help is appreciated! Thanks in advance!!
