### ISSUE TITLE
[Bug] Service widgets throw 403 and (system) Widgets throw 404

### ISSUE THREAD

**Issue by JohnnyDeeee** [benphelps/homepage#440]
**Describe the bug**
All my Service widgets throw 403 errors even though I correctly filled in the `key`s.
My (system) Widgets (disks) throws 404 errors, but only on custom disks.

**Expected behavior**
Both widgets should work with this configuration (assuming this configuration is indeed correct)

**Screenshots**
(`sonarr.development-hub.io` is a local DNS record in my PiHole instance.)

![image](https://user-images.githubusercontent.com/9005496/197558512-a1a1c36f-8082-4d72-8c5b-9adf28a6e84f.png)

![image](https://user-images.githubusercontent.com/9005496/197558634-786a31a1-94aa-4920-a471-4060a534bc00.png)

![image](https://user-images.githubusercontent.com/9005496/197558686-e8a1a1ec-3668-472a-8cf0-a58608e75c5f.png)

![image](https://user-images.githubusercontent.com/9005496/197559230-529b1670-0a6c-4f60-be56-6b6a9f39eae5.png)

**Configuration**
_widgets.yaml_
```yaml
- resources:
      cpu: true
      memory: true
      expanded: true
      disk:
          - /
          - /media/Elements
```

_services.yaml_
```yaml
    - Sonarr:
        href: https://sonarr.development-hub.io
        icon: sonarr
        container: sonarr
        server: nuc-docker
        widget:
            type: sonarr
            url: https://sonarr.development-hub.io
            key: REDACTED
```

**Additional context**
This is the docker image i'm using 
![image](https://user-images.githubusercontent.com/9005496/197560293-fd92ad10-8135-4c08-be2f-eae29a204588.png)

This is the docker version
```
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        100c70180f
 Built:             Thu Sep 22 06:21:41 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       a89b842
  Built:            Thu Sep 22 06:22:13 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I'm using Traefik as a reverse proxy with self signed certificates. I suspect Traefik has to do something with this but i'm not sure where the problem lies..
