### ISSUE TITLE
Openweathermap not working

### ISSUE THREAD

**Issue by Invento3D** [benphelps/homepage#456]
Hi, in the top right corner where the weather should be showing, I only get an exclamation mark including the text "API Error".
My config:

**settings.yaml:**
```
- openweathermap:
    label: XXX #optional
    latitude: XXX
    longitude: XXX
    units: metric # or imperial
    provider: openweathermap
    cache: 5 # Time in minutes to cache API responses, to stay within limits
```

**widgets.yaml:**
```
providers:
  openweathermap: XXX
```

I removed the private values above.
