### ISSUE TITLE
[Bug] Proxmox widget not displaying any values

### ISSUE THREAD

**Issue by Invento3D** [benphelps/homepage#457]
### Description

The proxmox widget is not displaying any info (see attached screenshot).
API credentials are correct. Otherwise I would get an "API Error" in Dashboard instead of the view you see in the screenshot.
I'm using Proxmox 7.2-7.

![grafik](https://user-images.githubusercontent.com/27298166/198279073-3dcfe993-df1d-43db-a33c-b77ef174dd49.png)

### Steps to reproduce

-

### homepage version

v0.4.18

### Installation method

Docker

### Configuration

```yaml
- Proxmox:
       icon: proxmox.png
       href: https://XXX
       widget:
          type: proxmox
          url: https://XXX
          username: XXX
          password: XXX
          fields: ["vms", "lxc", "cpu", "mem"]
```
```


### Other

_No response_
