### ISSUE TITLE
[Bug] Speedtest-tracker widget: Not working?

### ISSUE THREAD

**Issue by Invento3D** [benphelps/homepage#458]
### Description

Hi, I can't get the speedtest-tracker widget working.
See below a screenshot: Nothing is displayed. But the speedtest-tracker docker container is up and running, and reachable through the specified url.

![grafik](https://user-images.githubusercontent.com/27298166/198288195-8223f7ed-3f93-4748-8899-8c294bca648a.png)

![grafik](https://user-images.githubusercontent.com/27298166/198288534-bc3f4443-372e-4fc5-bcc5-a929768a04b6.png)

### Steps to reproduce

Use speedtest-tracker with docker and the default compose file from the github page

### homepage version

v0.4.18

### Installation method

Docker

### Configuration

```yaml
services.yaml:

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best
    - Speedtest:
      icon: speedtest-tracker.png
      href: http://XXXX:8765
      widget:
        type: speedtest
        url: http://XXXX:8765
        fields: ["download", "upload", "ping"]
```
```


### Other

_No response_
