### ISSUE TITLE
[Bug] Server Memory Represented as Percentage in Glances Widget but in Gb using Resource Widget

### ISSUE THREAD

**Issue by CKraft11** [benphelps/homepage#472]
### Description

When two machines are connected where one is local using the resources widget and once is remote using the glances widget they both look identical except for the fact that they both represent memory differently.

### Steps to reproduce

Connect machine using resources widget, connect machine using glances widget.

### homepage version

v0.4.18

### Installation method

Docker

### Configuration

```yaml
Workable solution I came up with was adding them both using glances but it is kind of pointless to add the second instance otherwise.

- glances:
    url: http://10.0.0.42:61208
    label: Radon

- glances:
    url: http://10.0.0.41:61208
    label: Xenon
```

### Other

I am also having a issue with my Dockerized Unifi Controller with the Unifi widget but this seems resolved and set to release soon
