### ISSUE TITLE
[Feature Request] Run container as supplied UID : GID

### ISSUE THREAD

**Issue by schklom** [benphelps/homepage#488]
### Description

Allow to run without root privileges.

### Other

 ```yaml
services:
  homepage:
    image: ghcr.io/benphelps/homepage
    container_name: homepage
    volumes:
      - ${DOCKER}/homepage/config:/app/config
      - ${DOCKER}/homepage/images:/app/public/images
    ports:
      - 3000:3000
    user: 1001:1001
```
causes warnings such as
```bash
[2022-11-04T21:01:51.627Z] warn: Failed to update prerender cache for /en [Error: EACCES: permission denied, open '/app/.next/server/pages/en.html'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/.next/server/pages/en.html'
}
```

I think adding
```dockerfile
USER: 1001:1001
```
in the Dockerfile should do the trick. Ideally at the beginning, or near the end if it does not work.

**Comment by JazzFisch** [comment]
This has been talked about to some degree in #95.

**Comment by JigSawFr** [comment]
Works as expected with docker socket proxy :)

**Comment by MrOnak** [comment]
Maybe I got lucky but adding PUID / PGID as environment parameters in docker-compose.yaml works for me. 

```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:main
    container_name: homepage
    environment:
      - PUID=1002
      - PGID=100
    networks:
```
