### ISSUE TITLE
[Bug] Jellyfin widget: TypeError

### ISSUE THREAD

**Issue by ditek** [benphelps/homepage#493]
### Description

The Jellyfin widget seems to crash with a TypeError displaying the bellow call stack:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/10835824/200149886-58e5a9ad-43e4-4e72-aa0c-37b3c04356e6.png">

I don't think it's an issue accessing the API, as that usually just shows "API Error".

### Steps to reproduce

1. Add the jellyfin widget in `services.yaml`.
```yaml
- Multimedia:
    - Jellyfin:
        href: http://192.168.0.142:8096
        icon: jellyfin
        container: jellyfin
        widget:
            type: jellyfin
            url: http://192.168.0.142:8096
            key: xxx
```

2. Reload Homepage.

### homepage version

v0.4.18 (4ea2798, Oct 15, 2022)

### Installation method

Docker
