### ISSUE TITLE
[Bug] memory stat rounding too imprecise

### ISSUE THREAD

**Issue by vladaurosh** [benphelps/homepage#497]
### Description

I am running Homepage (not in docker) on Asus Tinker Board (armv7) and dietpi OS, looks pretty good but resources widget is showing wrong value for free memory (total is good but it's showing same value for free).
![image](https://user-images.githubusercontent.com/47857324/200196863-e365a753-432f-478f-9e10-16be2ac185db.png)

### Steps to reproduce

Add resources widget
- resources:
    label: System
    cpu: true
    memory: true
    expanded: true

### homepage version

v0.4.18

### Installation method

Source

### Configuration

```yaml
- resources:
    label: System
    cpu: true
    memory: true
    expanded: true
```
