### ISSUE TITLE
[Bug] Pyload Widget

### ISSUE THREAD

**Issue by Nonoss117** [benphelps/homepage#517]
### Description

I use pyload-ng docker.

I get an API error with Pyload widget. 
![image](https://user-images.githubusercontent.com/79055577/201116940-71406642-2313-4e1c-8922-e8a4f55c59cf.png)

I created a user with "LIST" permissions (I also tried with an admin user)

my `services.yaml`:
``` yaml
    - Pyload-ng:
        icon: pyload.png
        href: http://192.168.1.100:8100/
        server: nas-docker
        container: pyload-ng
        description: Téléchargements
        widget:
            type: pyload
            fields: ["speed", "active", "queue", "total"]
            url: http://192.168.1.100:8100
            username: monitor
            password: My.password
```
My log file :
[homepage-main.log](https://github.com/benphelps/homepage/files/9981663/homepage-main.log)

Is there something wrong with my parameters ?
Or the widget is only ok for pyload and not for pyload-ng ?

### Steps to reproduce

same configuration, with docker `pyload-ng`

### homepage version

main (eff2f1a, 10 nov. 2022)

### Installation method

Docker

### Configuration

```yaml
Unraid + linuxserver/docker-pyload-ng
```
