### ISSUE TITLE
[Bug] Error while installing with Docker

### ISSUE THREAD

**Issue by cfstcyr** [benphelps/homepage#519]
### Description

I've tried to install it on a raspberry pi with the docker command line and docker compose, but the result is the same. I get
```
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ead7514
```
and then the container stops.

This is the docker compose I use (yes the directory exists and it has a service.yaml file) :
```yml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 13076:3000
    volumes:
      - /var/config/homepage:/app/config # Make sure your local config directory exists
```

### Steps to reproduce

1. Compose the project.
2. See result.

### homepage version

latest

### Installation method

Docker

**Comment by shamoon** [comment]
Many users use this on RPis, cant help but wonder if theres something up with your system. What RPi / os are you running?

**Comment by Mbarmem** [comment]
Seems like you are missing volume mount for docker integration. Refer to the documentation [here](https://gethomepage.dev/en/installation/docker/).

```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```
