### ISSUE TITLE
Jellyfin: TypeError: c.filter is not a function

### ISSUE THREAD

**Issue by wjbridge** [benphelps/homepage#52]
Updated to the new `v0.2.0`. Getting this error with my jellyfin widget

Navigate URL: `{URL}/api/services/proxy?type=jellyfin&group=Media&service=Jellyfin&endpoint=Sessions`
```
{"error":"Unkown proxy service type"}
```

```
framework-b3ca2e9a9574e304.js:1 TypeError: c.filter is not a function
  at g (index-52903fa49e6384e8.js:1:2056)
  at Eo (framework-b3ca2e9a9574e304.js:1:63191)
  at Pu (framework-b3ca2e9a9574e304.js:1:74879)
  at xi (framework-b3ca2e9a9574e304.js:1:121314)
  at bs (framework-b3ca2e9a9574e304.js:1:109367)
  at gs (framework-b3ca2e9a9574e304.js:1:109295)
  at vs (framework-b3ca2e9a9574e304.js:1:109158)
  at as (framework-b3ca2e9a9574e304.js:1:105938)
  at ls (framework-b3ca2e9a9574e304.js:1:104489)
  at S (framework-b3ca2e9a9574e304.js:1:138448)
```

YAML Config:
```
- Jellyfin:
  icon: jellyfin.png # Icon, see: https://github.com/walkxcode/dashboard-icons or public/icons
  href: REDACTED
  description: Media Server
  server: &docker groot-docker
  container: jellyfin
  widget:
    type: jellyfin
    url: REDACTED
    key: REDACTED
```
