### ISSUE TITLE
[Bug] Time format not correct for locale

### ISSUE THREAD

**Issue by lsaadeh** [benphelps/homepage#520]
### Description

![image](https://user-images.githubusercontent.com/43462320/201585538-fb8d402e-e052-4fda-b1ea-8ab3b9e9a8b7.png)

Australia/Sydney should be day/month/year

### Steps to reproduce

be me in sydney australia using date/time :)

### homepage version

v0.4.18 (4ea2798, Oct 16, 2022)

### Installation method

Docker

**Comment by shamoon** [comment]
You'll want to set the language, e.g. `language: en-AU`

**Comment by HenrysCat** [comment]
How does one get this to work?
I have tried:

- datetime:
    text_size: md
    format:
      language: en-GB
      dateStyle: short
      timeStyle: short
      hour12: false

But still: 11/27/22

**Comment by shamoon** [comment]
It’s set at the top level in settings, not the widget see https://gethomepage.dev/en/configs/settings/

**Comment by gavinmcfall** [comment]
Reopening this. 
in my settings.yaml I have the following:

```
language: en-nz
``` 
In my widgets.yaml I have:
```
- resources:
    cpu: true
    memory: true
    disk: /

- datetime:
    text_size: x1
    locale: nz
    format:
        dateStyle: medium
        timeStyle: medium
        hour12: true

- search:
    provider: google
    target: _blank
```

and my data time still looks like this:
![2023-11-17 11_37_43-Harbourside](https://github.com/gethomepage/homepage/assets/131718663/36135c82-9030-41f9-966b-b864e326833e)
