### ISSUE TITLE
Custom Search Provider Errors [Bug] 

### ISSUE THREAD

**Issue by angryviking** [benphelps/homepage#524]
### Description

When provisioning a custom search provider, I get redirected to an undefined URL, with "Application error: a client side exception has occurred"

URL bar after searching for "test" using a custom provider:
![image](https://user-images.githubusercontent.com/28925820/202446498-bce51c52-db5e-494a-bd68-0d620f829a88.png)

The predefined providers like Google seem to work fine.

Some of the custom search providers I have tried in my settings file:
```
- search:
    provider: custom
    url: https://google.com/search?q=
    target: _blank
    
- search:
    provider: custom
    url: https://search.brave.com/search?q=
    target: _blank

- search:
    provider: custom
    url: https://themoviedb.org/search?query=
    target: _blank
```

These URLs all work fine from the browser and the homepage container can ping the domains.
```
# docker exec homepage ping themoviedb.org
PING themoviedb.org (108.156.83.71): 56 data bytes
64 bytes from 108.156.83.71: seq=0 ttl=247 time=9.828 ms
64 bytes from 108.156.83.71: seq=1 ttl=247 time=9.913 ms
64 bytes from 108.156.83.71: seq=2 ttl=247 time=9.859 ms
^C
# docker exec homepage ping search.brave.com
PING search.brave.com (13.226.52.94): 56 data bytes
64 bytes from 13.226.52.94: seq=0 ttl=245 time=9.994 ms
64 bytes from 13.226.52.94: seq=1 ttl=245 time=10.609 ms
^C
```

The custom search used to work, but that could have been in an earlier version of homepage.

Also, as an enhancement, it would be nice to be able to change the text in the search bar from "Search..." to something custom like the provider name. That way if I have multiple search bars (like adding themoviedb search to just search for movies) I would know which provider that I am using.

### Steps to reproduce

1. Add a custom search provider in the `widgets.yaml` file, like
```
- search:
    provider: custom
    url: https://google.com/search?q=
    target: _blank
```

2. Go to the local homepage in the browser

3. Try to search; example for "test" and click the search icon
![image](https://user-images.githubusercontent.com/28925820/202449333-08526d01-b076-462b-9076-aa0d1f860a08.png)

### homepage version

v0.4.18 (4ea2798, Oct 15, 2022)

### Installation method

Docker
