### ISSUE TITLE
[Bug]Adguard widget not loading data correctly 

### ISSUE THREAD

**Issue by nzkller** [benphelps/homepage#527]
### Description

Homepage version: v0.4.18 (4ea2798, Oct 15, 2022)

Docker version: 20.10.21, build baeda1f

Docker Compose version: v2.3.0

AdGuard version: v0.107.18

AdGuard widget not loading correctly. See picture below.

![Screenshot 2022-11-18 at 1 36 19 AM](https://user-images.githubusercontent.com/18606875/202637682-b4bd4ecb-9c5f-4796-b58d-03474d3273a9.png)

Configuration checked!

Does not work even if you specify the fields line or not.

Username is not the default "admin" and the password has special characters.

### Steps to reproduce

Configure adguard like below in services.yaml

    - AdGuard:
        icon: https://imgs.search.brave.com/1_cq4UV35AE9fGqhReKvyH30WLWhjUQLo2vrXaxbVvs/rs:fit:512:512:1/g:ce/aHR0cHM6Ly9jZG4u/aWNvbi1pY29ucy5j/b20vaWNvbnMyLzI2/OTkvUE5HLzUxMi9h/ZGd1YXJkX2xvZ29f/aWNvbl8xNjc5MDUu/cG5n
        href: http://1.1.1.1
        description: AdGuard Home
        widget:
          type: adguard
          url: http://1.1.1.1
          #fields: ["queries", "blocked", "filtered", "latency"]
          username: USERNAME
          password: PASSWORD

### homepage version

v0.4.18 (4ea2798, Oct 15, 2022)

### Installation method

Docker

### Configuration

```yaml
- AdGuard:
        icon: https://imgs.search.brave.com/1_cq4UV35AE9fGqhReKvyH30WLWhjUQLo2vrXaxbVvs/rs:fit:512:512:1/g:ce/aHR0cHM6Ly9jZG4u/aWNvbi1pY29ucy5j/b20vaWNvbnMyLzI2/OTkvUE5HLzUxMi9h/ZGd1YXJkX2xvZ29f/aWNvbl8xNjc5MDUu/cG5n
        href: http://1.1.1.1
        description: AdGuard Home
        widget:
          type: adguard
          url: http://1.1.1.1
          #fields: ["queries", "blocked", "filtered", "latency"]
          username: USERNAME
          password: PASSWORD
```

### Other

Homepage version: v0.4.18 (4ea2798, Oct 15, 2022)

Docker version: 20.10.21, build baeda1f

Docker Compose version: v2.3.0

AdGuard version: v0.107.18
