### ISSUE TITLE
[Bug] Can't use RuTorrent widget with HTTPS on Port 443

### ISSUE THREAD

**Issue by Turnos** [benphelps/homepage#538]
### Description

It's not possible to use the RuTorrent widget with RuTorrent configured for SSL on Port 443.

If you configure the widget url like this: 'https://myserver:443/rutorrent' the resulting request will look like this 'https://myserver:80/rutorrent/plugins/httprpc/action.php'.
The same behaviour applies if you leave out the Port in your url ('https://myserver/rutorrent"). 

This is the corresponding error in the log file:
`[2022-11-19T20:15:50.102Z] error: request to https://myserver:80/rutorrent/plugins/httprpc/action.php failed, reason: write EPROTO 78FB07C97D140000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:`

I did some research, in 'src/widgets/rutorrent/widget.js' the URL object is created from the widget url.
The port of the URL object will be '' if you provide the default port for the specified protocol, this applies to this case (443 is default port for HTTPS). And obviously if you don't provide any port, the URL.port will be '' as well ([for reference](https://developer.mozilla.org/en-US/docs/Web/API/URL/port)).
The RuTorrent Object from RuTorrent-Promise is defaulting to Port 80, if you configure it with 'port='' '.

### Steps to reproduce

1. Configure your ruTorrent widget Url ("https://myserver:443/rutorrent").
2. Reload Homepage
3. API Error occurs.

### homepage version

v0.4.18 (4ea2798)

### Installation method

Unraid

### Configuration

```yaml
services.yaml

- Downloader/Indexer:
    - ruTorrent:
        href: https://myserver/rutorrent/
        icon: rutorrent.png
        widget:
            type: rutorrent
            url: https://myserver:443/rutorrent
            username: user
            password: password
```
