### ISSUE TITLE
[Bug] Base URL does not work as intended

### ISSUE THREAD

**Issue by chikei** [benphelps/homepage#539]
### Description

So I got the impression from https://github.com/benphelps/homepage/discussions/150#discussioncomment-3641463 that `base` in settings.yaml can be used to setup a path prefixed reverse proxy routing.
But browsers seem happily ignore the path part of `<base>` tag when resource path is started with `/`.

The `<base>` header is set
<img width="334" alt="Screenshot 2022-11-20 231525" src="https://user-images.githubusercontent.com/84867/202910265-e55342b2-eb21-47bb-92be-48e26703349a.png">

but browser still fetch js from root
<img width="703" alt="Screenshot 2022-11-20 231553" src="https://user-images.githubusercontent.com/84867/202910240-8f5a90b7-79f4-4b84-8598-a337cd05c126.png">

### Steps to reproduce

1. setup path prefixed reverse proxy and base in settings.yaml
2. go to homepage

### homepage version

docker latest

### Installation method

Docker

### Configuration

settings.yaml:
```yaml
base: http://diskstation:8080/homepage/
```

docker-compose:

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /homepage_path:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=PathPrefix(`/homepage`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.homepage-strip.stripprefix.prefixes=/homepage"
      - "traefik.http.routers.homepage.middlewares=homepage-strip"
```
