### ISSUE TITLE
[Bug] Speedtest not working

### ISSUE THREAD

**Issue by JijaProGamer** [benphelps/homepage#540]
### Description

Speedtest says "API Error"
This may be a bug with speedtest-cli making a recent change that breaks itself when you dont use "speedtest --secure"

### Steps to reproduce

Create a speedtest widget - it will error

### homepage version

v0.4.18

### Installation method

Docker

**Comment by Nonoss117** [comment]
I installed this docker container :[https://hub.docker.com/r/henrywhitaker3/speedtest-tracker/](https://hub.docker.com/r/henrywhitaker3/speedtest-tracker/)

This is my settings.yaml:
```yaml
    - Speedtest-Tracker:
        icon: speedtest-tracker.png
        href: http://192.168.1.100:6095
        server: nas-docker
        container: speedtest-tracker
        description: Monitoring débit Internet
        widget:
          type: speedtest
          fields: ["download", "upload", "ping"]
          url: http://192.168.1.100:6095
```
![image](https://user-images.githubusercontent.com/79055577/202917728-5ab030e4-6196-44ec-8dc2-4de1913c38ea.png)
