### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hansies** [benphelps/homepage#541]
### Description

I'm having 2 docker installations on different servers (192.168.2.100 and 192.168.2.100), both with portainer installed. My primary servers portainer also has access to my secondary servers docker.

I want both portainers availability in my Homepage which is working. I also want the widget for both portainers to be active so can I can see the containers status.

For some reason, the widget for my secondary server keeps reporting the stats from my primary server.

![image](https://user-images.githubusercontent.com/35967578/203049780-da9781a1-fad1-41d6-b140-7186438b28c2.png)

While my secondary server certainly has more containers:

![image](https://user-images.githubusercontent.com/35967578/203050197-d0227a10-dcae-4303-885d-32d28c1ea054.png)

This is my config:
```
- Management:
    - Portainer:
        icon: portainer.png
        href: https://192.168.2.100:9443
        description: NAS - Ubuntu-01
        server: docker-ubuntu-01
        container: portainer
        widget:
          type: portainer
          url: https://192.168.2.100:9443
          env: 2
          key: ###


    - Portainer:
        icon: portainer.png
        href: https://192.168.2.101:9443
        description: Mediaserver - Ubuntu-02
        server: docker-ubuntu-02
        container: portainer
        widget:
          type: portainer
          url: https://192.168.2.101:9443
          env: 2
          key: ###

```

Also when I try the following config (to get the secondary docker information via the primary portainer, I have no success.

```
- Management:
    - Portainer:
        icon: portainer.png
        href: https://192.168.2.100:9443
        description: NAS - Ubuntu-01
        server: docker-ubuntu-01
        container: portainer
        widget:
          type: portainer
          url: https://192.168.2.100:9443
          env: 2
          key: ###


    - Portainer:
        icon: portainer.png
        href: https://192.168.2.101:9443
        description: Mediaserver - Ubuntu-02
        server: docker-ubuntu-02
        container: portainer
        widget:
          type: portainer
          url: https://192.168.2.100:9443
          env: 5 #environment number for my secondary server in my primary portainer)
          key: ###

```

I'm sure there are people monitoring multiple dockers in Homepage and I'm wondering if they have problems or not.

### Steps to reproduce

Create 2 docker instances on different servers.
Create some containers on both. To test, make sure the number of containers are not equal on both servers.
Setup portainer on both.
Create services and widget for both in Homepage.
Check if the numbers are equal.

### homepage version

v0.4.18

### Installation method

Docker

### Configuration

```yaml
- Management:
    - Portainer:
        icon: portainer.png
        href: https://192.168.2.100:9443
        description: NAS - Ubuntu-01
        server: docker-ubuntu-01
        container: portainer
        widget:
          type: portainer
          url: https://192.168.2.100:9443
          env: 2
          key: ###


    - Portainer:
        icon: portainer.png
        href: https://192.168.2.101:9443
        description: Mediaserver - Ubuntu-02
        server: docker-ubuntu-02
        container: portainer
        widget:
          type: portainer
          url: https://192.168.2.101:9443
          env: 2
          key: ###

```
```


### Other

Docker version 20.10.21

**Comment by shamoon** [comment]
You need to give them different names

**Comment by JazzFisch** [comment]
E.g.:

```yaml
- Management:
    - Portainer NAS:
        icon: portainer.png
        href: https://192.168.2.100:9443
        description: NAS - Ubuntu-01
        server: docker-ubuntu-01
        container: portainer
        widget:
          type: portainer
          url: https://192.168.2.100:9443
          env: 2
          key: ###


    - Portainer Mediaserver:
        icon: portainer.png
        href: https://192.168.2.101:9443
        description: Mediaserver - Ubuntu-02
        server: docker-ubuntu-02
        container: portainer
        widget:
          type: portainer
          url: https://192.168.2.101:9443
          env: 2
          key: ###
```
