### ISSUE TITLE
[Bug] Latest nightly build completely messed my layout

### ISSUE THREAD

**Issue by Magelo** [benphelps/homepage#542]
### Description

Categories order is a complete mess. In my services.yaml, I have (with default layout) :
- Dockers
- Networking
- NAS & Printers
They appeared at the top on 3 side by side columns.

Followed by (with style:row / columns:3) :
- Servers
- Services
- Applications

They are now shown in this order :
- Applications (row/3) 
- Dockers (1 large column)
- Services (row/3)
- Networking (1 large column)
- Servers (row/3)
- NAS & Printers (1 large column)

Bookmars section is fine.

Also, Bazarr is now showing "API Error information.", Jellyseer was at first showing this error too, but now Bazarr is the only one with this API error.

### Steps to reproduce

A page refresh or using the regenerate page has the same effect.

### homepage version

nightly (0c0bbe9, Nov 20, 2022)

### Installation method

Docker

**Comment by shamoon** [comment]
You now need to specify the groups in the `layout` block in settings if you want to set the order of the groups. If you have some groups in services only they will come after the ones specified in layout. e.g. do this:

```yaml
layout:
  Auto-Discovered1:
  Configured1:
  Configured2:
  Auto-Discovered2:
  Configured3:
    style: row
    columns: 3
```
