### ISSUE TITLE
[Bug] Ping not showing response when API gets data. How to troubleshoot deeper

### ISSUE THREAD

**Issue by corvock** [benphelps/homepage#572]
### Description

I have set up Radarr as a service. The widget works as expected. When i added ping: to the definition, it always returns 401 in the box where other services return a time in ms. If that is the http code there is no auth on it that would block internal requests. 

curl -L -k <radarr url> returns html content. 

I am unsure what the next steps to troubleshoot this should be.

![image](https://user-images.githubusercontent.com/10361553/204407865-3d6c73eb-887b-4069-b9e9-947f43208e4d.png)

### Steps to reproduce

open homepage with radarr configured to ping, i get a number in red which is unexpected when the machine is accessible by api for the widget

### homepage version

0.5.2

### Installation method

Source

### Configuration

```yaml
- Radarr:
        icon: radarr.png
        href: https://url
        ping: http://IP:7878
        description: Movies
        widget:
          type: radarr
          url: http://IP:7878
          key: <redacted>
```

### Other

My proxmox hosts do the same thing with different numbers in red. They're not on the same subnet, so added issues. Looking to find out how to replicate what "ping" does on the command line to troubleshoot them or get an error that can show more info.
