### ISSUE TITLE
[Bug] Jellyfin API Error ECONNREFUSED

### ISSUE THREAD

**Issue by Judman** [benphelps/homepage#580]
### Description

Hello,

I am setting up my Homepage, but I cannot get the Jellyfin widget to connect and function. Hopefully someone can point my in the right direction.

Homepage and Jellyfin are running on Unraid, but am not trying to use the docker socket method of connection (I don't think).

### Steps to reproduce

1. nano services.yaml
2. Insert Jellyfin config
3. Save and exit
4. API Error Information

### homepage version

v0.5.2

### Installation method

Unraid

### Configuration

```yaml
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Media Group:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.1.30:8096/
        description: Movies & TV Shows
        container: jellyfin
        widget:
            type: jellyfin
            url: http://192.168.1.30:8086
            key: b96aee27208543538f7ad8b268e5ceb9

    - Radarr:
        icon: radarr.png
        href: http://192.168.1.30:7878/
        container: radarr
        widget:
            type: radarr
            url: http://192.168.1.30:7878
            key: <api key>

    - Sonarr:
        icon: sonarr.png
        href: http://192.168.1.30:8989/
        container: sonarr
        widget:
            type: sonarr
            url: http://192.168.1.30:8989
            key: <api key>

    - Jackett:
        icon: jackett.png
        href: http://192.168.1.30:9117/UI/Dashboard
        container: jackett
        widget:
            type: jackett
            url: http://192.168.1.30:9117

    - Qbittorrent:
        icon: qbittorrent.png
        href: http://192.168.1.30:8081
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://192.168.1.30:8081
           # username: admin
           # password: <pass>


- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
```

### Container Logs
```
Listening on port 3000
[2022-11-28T04:35:07.744Z] error: <httpProxy> Error calling http://192.168.1.30/emby/Sessions...
[2022-11-28T04:35:07.747Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.1.30:8086
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.30',
    port: 8086
  }
]
[2022-11-28T04:35:07.800Z] debug: <qbittorrentProxyHandler> qBittorrent is rejecting the request, logging in.
[2022-11-28T04:36:14.140Z] error: <httpProxy> Error calling http://192.168.1.30/emby/Sessions...
[2022-11-28T04:36:14.141Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.1.30:8086
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.30',
    port: 8086
  }
]
[2022-11-28T04:36:42.400Z] error: <httpProxy> Error calling http://192.168.1.30/emby/Sessions...
[2022-11-28T04:36:42.401Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.1.30:8086
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.30',
    port: 8086
  }
]
[2022-11-28T04:36:43.424Z] error: <httpProxy> Error calling http://192.168.1.30/emby/Sessions...
[2022-11-28T04:36:43.424Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.1.30:8086
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.30',
    port: 8086
  }
]
Listening on port 3000
```
### Browser Logs
```
XHRGEThttp://192.168.1.30:3001/api/services/proxy?type=jellyfin&group=Media+Group&service=Jellyfin&endpoint=Sessions&query={"refreshInterval":5000}
[HTTP/1.1 500 Internal Server Error 18ms]

	
GET
	
scheme
	http
host
	192.168.1.30:3001
filename
	/api/services/proxy
type
	jellyfin
group
	Media Group
service
	Jellyfin
endpoint
	Sessions
query
	{"refreshInterval":5000}
Address
	192.168.1.30:3001
Status
500
Internal Server Error
VersionHTTP/1.1
Transferred603 B (368 B size)
Referrer Policystrict-origin-when-cross-origin

    	
    Connection
    	keep-alive
    Content-Length
    	368
    Content-Type
    	application/json; charset=utf-8
    Date
    	Tue, 29 Nov 2022 14:15:58 GMT
    ETag
    	"jhdmugvqdoa8"
    Keep-Alive
    	timeout=5
    Vary
    	Accept-Encoding
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	jwt_auth=eyJhbGciOiJIUzI1NiJ9.eyJVaWQiOiJjMGI4M2YzZS02YjNmLTQ4MmYtYjI4Mi0wZDc1YjQxZWE1YzAiLCJVc2VybmFtZSI6ImFkbWlud29sZiIsIlBhc3N3b3JkIjoiJDJiJDEwJElCYll3UmZJNWJoVEV0eUJsNFBQcy5QTXBFeTBvbzdnanZzWUkyZlkxSVRYdnNpQzJzUVVxIiwiSXNBZG1pbiI6ZmFsc2V9.mCSig3khLjlwPz0-gcwZos__6xLzQR5zLEaOVSuPzpc; Jackett=CfDJ8J1C4ok0vvhKpUsFFABYcXhGk5VBOM0PqebIbKJEzmA8bVXeA5zzCu7rkbPcJSCSoIGhYuQmQWnFtw0lAjaX7C_0lE8GCJBexsXF9zEbgLJpUYQyBJEM4mP7Ik2cOMv_XsbfbLmNJbS9MJY-q8-S94VTTDLJDkV_PMefXVVV4q2BEsdk5Gilvw65L3gkn1xxoHaJy4WKmtzb7r7G7V-Q…%5B%5D%2C%5C%22deletePaths%5C%22%3A%5B%5D%7D%22%2C%22lastUpdated%22%3A0%2C%22nextpage%22%3A0%2C%22prevpage%22%3A0%2C%22currentpage%22%3A1%2C%22searchFlag%22%3Atrue%2C%22searchActive%22%3Atrue%2C%22previousAppsSection%22%3A%22%22%2C%22searchInProgress%22%3Afalse%2C%22deprecated%22%3Afalse%2C%22actions%22%3Afalse%2C%22sidebarapppath%22%3A%22%2Ftmp%2Fcommunity.applications%2FtempFiles%2Ftemplates-community-apps%2FIBRACORPsRepository%2Fbenphelps-homepage-latest.xml%22%2C%22sidebarappname%22%3A%22homepage%22%7D
    DNT
    	1
    Host
    	192.168.1.30:3001
    Referer
    	http://192.168.1.30:3001/
    Sec-GPC
    	1
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
```
### Other

**Jellyfin version 10.8.1**

**Unraid version 6.11.1**

**Docker version 20.10.18**
```
root@Tower:/mnt/user/appdata/homepage# docker exec homepage ping 192.168.1.30
PING 192.168.1.30 (192.168.1.30): 56 data bytes
64 bytes from 192.168.1.30: seq=0 ttl=64 time=0.037 ms
64 bytes from 192.168.1.30: seq=1 ttl=64 time=0.038 ms
64 bytes from 192.168.1.30: seq=2 ttl=64 time=0.032 ms
64 bytes from 192.168.1.30: seq=3 ttl=64 time=0.034 ms
64 bytes from 192.168.1.30: seq=4 ttl=64 time=0.034 ms
64 bytes from 192.168.1.30: seq=5 ttl=64 time=0.043 ms
64 bytes from 192.168.1.30: seq=6 ttl=64 time=0.036 ms
^C
root@Tower:/mnt/user/appdata/homepage# docker exec homepage ping 192.168.1.30:8086
PING 192.168.1.30:8086 (192.168.1.30): 56 data bytes
64 bytes from 192.168.1.30: seq=0 ttl=64 time=0.041 ms
64 bytes from 192.168.1.30: seq=1 ttl=64 time=0.040 ms
64 bytes from 192.168.1.30: seq=2 ttl=64 time=0.035 ms
64 bytes from 192.168.1.30: seq=3 ttl=64 time=0.048 ms
64 bytes from 192.168.1.30: seq=4 ttl=64 time=0.035 ms
64 bytes from 192.168.1.30: seq=5 ttl=64 time=0.038 ms
```
```
root@Tower:/mnt/user/appdata/homepage# curl -L -k 'http://192.168.1.30:8086/emby/Sessions?api_key=b96aee27208543538f7ad8b268e5ceb9'
curl: (7) Failed to connect to 192.168.1.30 port 8086 after 0 ms: Connection refused
```
