### ISSUE TITLE
[Bug] nginx proxy manager

### ISSUE THREAD

**Issue by GertJanH** [benphelps/homepage#591]
### Description

since the last major update 0.4 > 0.5 I have 2 errors with my widget

the first error "Token has expired."
this can be fixed by restarting the container, then it will work again for about 24 hours.

the 2nd error is "internal error"
and what i can see is that which cannot reach the api url error 500

![npm1](https://user-images.githubusercontent.com/22355768/204807237-77495894-a3f3-4056-b9c2-db8cf3d4cb94.jpg)
![npm2](https://user-images.githubusercontent.com/22355768/204807241-ab2e8392-1fdd-4f68-b566-bfb6748f6440.jpg)

### Steps to reproduce

for problem one restart te container.

### homepage version

v0.5.2 (04fbf31, 28 nov. 2022)

### Installation method

Docker

### Configuration

```yaml
- Home Lab:
    - Proxy Manager:
        href: https://proxy.url/login
        icon: nginxproxymanager.png
        server: Brix
        container: proxy_manager
        widget:
          type: npm
          url: http://192.168.1.220:81
          username: home@page.local
          password: p@ssW0rd

- VPS:
    - Proxy Manager:
        href: https://proxy.url.nl/login
        icon: nginxproxymanager.png
        server: VPS
        container: nginxproxymanager-app-1
        description: Proxy Manager VPS
        widget:
          type: npm
          url: http://proxy.url.nl
          username: mail@domain.nl
          password: p@ssW0rd
```

### Container Logs

Listening on port 3000
[2022-11-29T10:52:32.318Z] error: (node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
