### ISSUE TITLE
[Feature Request] Allow variables in config file

### ISSUE THREAD

**Issue by modem7** [benphelps/homepage#60]
Would it be possible to allow variables in the config files?

E.g.

```
- Media:
    - Sonarr:
        href: http://192.168.0.254:8989
        #description: Homepage is awesome
        server: myserver
        container: Sonarr
        widget:
          type: sonarr
          url: http://192.168.0.254:8989 # no slash at the end
          key: $SONARRKEY
```

Then in the compose file, we can do something like:
```
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: Homepage
    environment:
      - SONARRKEY=xNYcIvYlbEiBXiIXJo3HDw32
    ports:
      - 8045:3000
    volumes:
      - $USERDIR/Homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```

(note: key used was randomly generated for this request)
