### ISSUE TITLE
[Feature Request] Docker labels for services

### ISSUE THREAD

**Issue by modem7** [benphelps/homepage#61]
Would it be possible to use compose file labels to define the Docker services side of things?

E.g. 

```
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: Homepage
    labels: 
      ## Homepage Dashboard
      - homepage.name=Netboot.XYZ
      - homepage.category=System
      - homepage.url=192.168.0.6:3000
      - homepage.icon=https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/netboot.png
    ports:
      - 8045:3000
    volumes:
      - $USERDIR/Homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
```

URL should be optional, as the URL should be able to be grabbed from the Docker socket link.

I have a similar setup with the Flame dashboard, which gives the following (with Traefik integration):
![image](https://user-images.githubusercontent.com/4349962/188479083-19adc926-5f71-40b3-a29e-79fbab47c0ab.png)

This would reduce the amount of dependency on external config files, and allow for auto-updating of services when they are added/remove/modified.

**Comment by benphelps** [comment]
So I've made some progress on this, and it seems to be working :)

As an example, here are the labels for my Emby docker compose entry:

```yaml
emby:
  labels:
    - traefik.enable=true
    - traefik.http.routers.emby.rule=Host(`emby.media.home`)
    - traefik.http.routers.emby.entrypoints=web
    - homepage.group=Media
    - homepage.name=Emby
    - homepage.icon=emby.png
    - homepage.href=http://emby.media.home
    - homepage.description=Media server
    - homepage.widget.type=emby
    - homepage.widget.url=http://emby.media.home
    - homepage.widget.key=myembyapikeywashere
```

This essentially defines a `services.yaml` entry equivalent to:

```yaml
- Media:
    - Emby:
        icon: emby.png
        href:
        description: Media server
        server: phelpsrv-b
        container: emby
        widget:
          type: emby
          url: http://emby.media.home
          key: myembyapikeywashere
```

But... and theres always a but.

This needs to work alongside entries in `services.yaml`, and with that, you lose support for strictly defined ordering.  You're basically leaving this up to the Docker API and the order that it sends back the containers.  The current logic is to place discovered entries above the hard configured entries.  But ordering between discovered entries in the same group comes down to the Docker APIs response.

Adding support for configured positions _could_ be done, but would require even more refactoring, so if it is done, it'll be done at a later time.

**Comment by modem7** [comment]
Hell yea! Great job!

Tbf, at least for me, but I know I don't speak for the larger userbase, the automated ordering (maybe a way to do it alphabetically would be the simplest choice, rather than some custom solution), can certainly be done at a later date, and wouldn't/couldn't be considered critical by any means.

**Comment by benphelps** [comment]
Just pushed the changes, I wanted to do a `latest` release before this bigger change to allow for some end-user testing before releasing it.

You can check out the commit here: d66326b41d8598156b9a015edbd9d529678eae48

**Comment by Just5KY** [comment]
@benphelps 
I followed that you did, but it didn't work for me.
Pulled the latest image.

```yml
version: "3.8"
services:
#--------------------------------------------------------------------------------------------# 
#                                 Dozzle - Real-time Docker Log Viewer                       #
#--------------------------------------------------------------------------------------------#
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      - homepage.group=Admin
      - homepage.name=Dozzle
      - homepage.icon=dozzle.png
      - homepage.href=http://192.168.0.151:9999

#--------------------------------------------------------------------------------------------#
#                                 File Browser                                               #
#--------------------------------------------------------------------------------------------#
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
    # to be modified depending on your needs
      - '/:/srv'
      - $DOCKERDIR/filebrowser/filebrowser.db:/database.db
    ports:
      - '5045:80'
    environment:
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Filebrowser
      - homepage.icon=dozzle.png
      - homepage.href=http://192.168.0.151:9999

#--------------------------------------------------------------------------------------------#
#                                 homepage                                                   #
#--------------------------------------------------------------------------------------------#
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - $DOCKERDIR/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```

Homepage logs

```log
Listening on port 3000
(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
services.yaml was copied to the config folder
bookmarks.yaml was copied to the config folder
widgets.yaml was copied to the config folder
settings.yaml was copied to the config folder
[Error: ENOENT: no such file or directory, open '/app/config/settings.yaml'] {
  errno: -2,
  syscall: 'open',
  path: '/app/config/settings.yaml'
}
TypeError: res.hasHeader is not a function
    at Object.setRevalidateHeaders (/app/node_modules/.pnpm/next@12.2.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/send-payload/revalidate-headers.js:8:37)
    at Object.sendRenderResult (/app/node_modules/.pnpm/next@12.2.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/send-payload/index.js:43:33)
Listening on port 3000
(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Listening on port 3000
(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

![image](https://user-images.githubusercontent.com/71321862/189461970-043aa9a1-02cd-4e90-90ef-b40d029aaf9d.png)

**Comment by Just5KY** [comment]
Made some changes and the error from the logs disappeared but still no update on the Homepage.

- Deleted all the config files.
- removed the image label.

`docker.yaml`
```yaml
my-local-docker:
  socket: /var/run/docker.sock
  
my-remote-docker:
  host: 127.0.0.1
  port: 2375
```
`services.yaml`
```yaml
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
```
`Docker Logs`
```log
Listening on port 3000
(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
services.yaml was copied to the config folder
bookmarks.yaml was copied to the config folder
widgets.yaml was copied to the config folder
```

`docker-compose.yml`
```yaml
#--------------------------------------------------------------------------------------------# 
#                                 Dozzle - Real-time Docker Log Viewer                       #
#--------------------------------------------------------------------------------------------#
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      - "homepage.group=Admin"
      - "homepage.name=Dozzle"
#      - homepage.icon=dozzle.png
      - "homepage.href=http://192.168.0.151:9999"
      - "homepage.description=Docker Logs"

#--------------------------------------------------------------------------------------------#
#                                 File Browser                                               #
#--------------------------------------------------------------------------------------------#
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
    # to be modified depending on your needs
      - '/:/srv'
      - $DOCKERDIR/filebrowser/filebrowser.db:/database.db
    ports:
      - '5045:80'
    environment:
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    labels:
      - "homepage.group=Admin"
      - "homepage.name=Filebrowser"
#      -" homepage.icon=dozzle.png"
      - "homepage.href=http://192.168.0.151:9999"
      - "homepage.description=File Browser"
#--------------------------------------------------------------------------------------------#
#                                 homepage                                                   #
#--------------------------------------------------------------------------------------------#
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - $DOCKERDIR/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```
