### ISSUE TITLE
[Bug] Unifi Widget UDM Special Edition Issue

### ISSUE THREAD

**Issue by r0arkin** [benphelps/homepage#612]
### Description

When I tried to set up the Unifi Controller widget, I always get a 404 for the API call no matter if I try no port just using https, 8443 or 443. I know people have gotten the UDM Pro working but this might be a different URL path for the UDM SE. Please let me know what curls you'd like or anyway I can help to troubleshoot further.

### Steps to reproduce

1. Validate that the username and password work locally on my GW IP.
2. Add Unifi Controller widget to services.yaml
3. Write the changes
4. Refresh homepage and I receive the 404
<img width="374" alt="Screenshot 2022-12-03 at 3 08 36 PM" src="https://user-images.githubusercontent.com/46236585/205465916-aa4205a0-4f5a-42c9-b92c-7996023564b8.png">

### homepage version

v0.5.3 (df5ff48, Nov 30, 2022)

### Installation method

Docker

### Configuration

```yaml
- Unifi Controller:
        icon: /icons/unifi.png
        href: https://unifi.ui.com/dashboard
        widget:
          type: unifi
          url: https://10.10.10.1
          username: <user>
          password: <password>
```

### Container Logs

[2022-12-03T23:08:26.264Z] error: <unifiProxyHandler> HTTP 404 getting data from Unifi endpoint https://10.10.10.1/api/stat/sites. Data: Not Found
