### ISSUE TITLE
[Bug] Multiple Adguard Widget

### ISSUE THREAD

**Issue by cfouche3005** [benphelps/homepage#613]
### Description

When using multiple adguard widgets, all adguard widget displate the same information than the first widget

![image](https://user-images.githubusercontent.com/51720655/205466664-9182eb8c-10da-482a-ae8b-cf4b48f42fb1.png)

The error is normal ( I volontarly used a wrong adguard adress to test but the second adress is normaly working)

![image](https://user-images.githubusercontent.com/51720655/205467185-48d3bdf8-79ce-4990-ad0d-c85c7bdfdd60.png)

The problem also apeared when using a valid url for the first widget and another valid url for the second widget, stats still duplicate.  

(The url point to two different adguard instances)

### Steps to reproduce

Create two aguard widgets with different url for the api.

### homepage version

v0.5.3 (df5ff48, 30 nov. 2022)

### Installation method

Docker

### Configuration

```yaml
---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- DNS:
    - AdGuard-Home:
        icon: adguard-home.png
        href: https://dns-m-lotus.redated.com/
        description: "Master : Lotus"
        server: serv-lotus
        container: adguard-home
        widget:
          type: adguard
          url: http://serv-lotus.redated.com:8053
          username: REDACTED
          password: REDACTED

    - AdGuard-Home:
        icon: adguard-home.png
        href: https://dns-r-monitor.redated.com/
        description: "Replica : Monitor"
        server: serv-monitor
        container: adguard-home
        widget:
          type: adguard
          url: http://serv-monitor.redated.com:8053
          username: REDACTED
          password: REDACTED
```
