### ISSUE TITLE
[Bug] Enabling 'ping' functionality for NZBGet and/or QBittorrent causes errors in the logs

### ISSUE THREAD

**Issue by suckerfish** [benphelps/homepage#645]
### Description

Errors in logs when either NZBGet or Qbittorrent have the 'ping' function enabled. 15+ other services are working fine with ping and do not generate errors in the logs.

The services on Homepage show up as expected and the ping does appear to work, as I get a ms response time listed.

Error I see in the logs is attached. 

![image](https://user-images.githubusercontent.com/33015972/206552856-308e80e5-ceaf-483c-a751-9afc64990e4c.png)

### Steps to reproduce

Add ping functionality for nzbget or qbittorrent then check logs.

### homepage version

v0.5.4 (f89093a, Dec 5, 2022)

### Installation method

Unraid

### Configuration

```yaml
- Downloaders:
    - NZBget:
       	href: http://192.168.1.200:6789
       	description: NZBget
        ping: http://192.168.1.200:6789
       	icon: nzbget.png
```

### Container Logs

[2022-12-08T19:43:14.714Z] error: <httpProxy> Error calling http://192.168.1.200/...
[2022-12-08T19:43:14.716Z] error: <httpProxy> [
  500,
  Error: socket hang up
      at connResetException (node:internal/errors:711:14)
      at Socket.socketOnEnd (node:_http_client:518:23)
      at Socket.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  }
]

### Other

Commenting out the ping functionality will stop the errors in the logs.
