### ISSUE TITLE
[Bug] Nginx Proxy Manager - Widget gets API error if I have 2 separate NPM targets

### ISSUE THREAD

**Issue by suckerfish** [benphelps/homepage#649]
### Description

I have two NPM instances at two different locations (separate VPS, external addresses, using FQDN).

With the widget enabled, I get an API error on one of them. **If I restart the container, it will typically swap and the other one will give me the API error and the previous one will start working. If I remove one of them and just use a single instance, it never breaks, and will always work**. So it appears as though having two (or more?) at a time causes issues of some sort.
![Screen Shot 2022-12-08 at 8 01 55 PM](https://user-images.githubusercontent.com/33015972/206623611-835b03ce-decc-4618-818e-382d939ce16a.png)

No container log entries that I can see due to this. See screenshot attached. 

### Steps to reproduce

Have two or more NPM instances at the same time with widgets enabled. 

### homepage version

v0.5.4 (f89093a, Dec 5, 2022)

### Installation method

Unraid

### Configuration

```yaml
- Utilities:
    - VPS NPM:
       	href: https://vps.mydomain.com
       	description: VPS NPM
       	ping: https://vps.mydomain.com
       	icon: nginxproxymanager.png
       	widget:
          type: npm
          url: https://vps.mydomain.com
          username: myusername
          password: mypass
    - Ampere NPM:
        href: https://ampere.myotherdomain.com
        description: Ampere NPM
        ping: https://ampere.myotherdomain.com
        icon: nginxproxymanager.png
        widget:
          type: npm
          url: https://ampere.myotherdomain.com
          username: myuser
          password: mypass
```

### Container Logs

no entries in logs for this
