### ISSUE TITLE
[Bug] Transmission Widget Error

### ISSUE THREAD

**Issue by lunaskyy** [benphelps/homepage#659]
### Description

Transmission Widget is report "API Error Information"

```
API Error: Error getting data from Transmission
URL: http://10.x.x.x:9091/transmission/rpc
Response Data:
401: Unauthorized</h1><p>Unauthorized User. 1 unsuccessful login attempts.
```

The username and password provided are correct, and work using the standard WebUI, Transmission is running as a docker container on the same host

### Steps to reproduce

1. Create Transmission Tile
2. Enable Widget - providing url and user/pass

### homepage version

v0.5.4 (f89093a)

### Installation method

Docker

### Configuration

```yaml
### Homepage config
- Transmission:
    icon: transmission
    href: http://10.x.x.x:9091 # actual ip is here
    description: Torrent Client
    widget:
      type: transmission
      url: http://10.x.x.x:9091 # actual ip is here
      user: *wewe*
      pass: *securityiscool* # actual pass is here`

### Transmission RPC Config
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "*sneepsnorp*",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "luna",
    "rpc-whitelist": "",
    "rpc-whitelist-enabled": false,`
```
