### ISSUE TITLE
[Feature Request] Fixed order of docker defined services?

### ISSUE THREAD

**Issue by RichyHBM** [benphelps/homepage#673]
### Description

Currently, it seems services that are defined via docker are ordered in the reverse order to how they were spun up, i.e. the last service you brought up via docker will be first on the list. This creates some confusion as services on the home page can sometimes jump around.

Would be great if we could define a sorting method for docker services, this could even be as simple as a new field in the docker.yaml file like:

```
my-docker:
    host: homepage-socket-proxy
    port: 2375
    order: alphabetical
```
