### ISSUE TITLE
[Feature Request] Secrets Support

### ISSUE THREAD

**Issue by clbx** [benphelps/homepage#680]
### Description

Some way to properly store secrets so they're not sitting in plain text in configuration files.

This can be done in several ways of varying quality
- Environment Variables
- Loading from dedicated secrets configuraion
- Secrets management support (i.e. Vault)
- Kubernetes Secrets

### Other

I've noticed a few other people using homepage in kubernetes and being able to use the secrets outside of the config would be a big improvement so they are not stored in the same files when pushed to a repository.

**Comment by Jleagle** [comment]
+1

My server config is open source so presumed i would be able to do something like:

```
    - Tautulli:
        href: https://tautulli.xx.com/
        container: tautulli
        widget:
          type: tautulli
          url: http://localhost:8181
          key: ${TAUTULLI_KEY}
```
