### ISSUE TITLE
Issue with yaml indentation

### ISSUE THREAD

**Issue by ptoulouse** [benphelps/homepage#681]
### Description

As far as I was able to test, services.yaml does not work when indenting by 2 spaces. It works with 4 spaces.

As far as I am aware of, this goes against yaml structure where the number of spaces should not matter as long as the indentation is consistent.

### Steps to reproduce

Create a yaml file with indent level of 2 spaces: does not work.
Create a yaml file with indent level of 4 spaces; works.

### homepage version

v0.5.4

### Installation method

Docker

**Comment by shamoon** [comment]
It does work with 2, or 5, which is what mine currently is

**Comment by shamoon** [comment]
Oh I see, widgets dont

**Comment by shamoon** [comment]
I think the bigger question here is, does it matter? the yaml parsing comes directly from https://github.com/nodeca/js-yaml

**Comment by shamoon** [comment]
Ha, ok yea I can confirm it works with e.g.

```
- Home Management & Info:
  - Unifi:
     icon: unifi.png
     description: Unifi Console Management
     href: https://unifi.ui.com
     widget:
       type: unifi
       url: https://10.0.1.1
       username: username
       password: pass
```

**Comment by ptoulouse** [comment]
Here is my test with indent level =2:

```
- Medias:
  - Plex:
    icon: plex.png
    href: https://plex.example.com/
    description: Plex
    server: docker-mtl
    container: plex
```
![image](https://user-images.githubusercontent.com/51246205/207925638-5c9b40c0-93cc-4f2e-9078-4c3714e38d6d.png)

What is not working:

- No status
- No icon
- No description
- Does nothing when clicking on Plex

Test 2, with indent level=4:
```
- Medias:
    - Plex:
        icon: plex.png
        href: https://plex.ptoulouse.ca/
        description: Plex
        server: docker-mtl
        container: plex
```
![image](https://user-images.githubusercontent.com/51246205/207926765-1e35c379-0012-401a-88c1-83483f9fb1bc.png)

It is working as expected.

So not working with indet-level 2. Why?
