### ISSUE TITLE
[Bug] ruTorrent API error (XMLRPC?)

### ISSUE THREAD

**Issue by fredrikscode** [benphelps/homepage#682]
### Description

Upon adding ruTorrent as a service I receive an API error. Link works fine to click on but homepage is unable to pull in any data. I believe this could be because rTorrent 0.9.7+ has a built-in daemon mode disabling the user interface, so you can only control it via XMLRPC.

### Steps to reproduce

1. Add service to homepage with specified configuration
2. Use rTorrent 0.9.8/ruTorrent 3.10
3. Notice the API error on homepage

### homepage version

v0.5.4 (f89093a, Dec 5, 2022)

### Installation method

Docker

### Configuration

```yaml
- Download clients:
    - ruTorrent:
        href: https://rutorrent.my.domain
        icon: rutorrent
        widget:
          type: rutorrent
          url: https://rutorrent.my.domain
```

- Reverse proxy pointing the URL configured in the homepage service to the ruTorrent container. No authentication.
- [CrazyMax's docker image for rTorrent+ruTorrent](https://github.com/crazy-max/docker-rtorrent-rutorrent)
```


### Container Logs

`error: undefined`

### Browser Logs

`API Error: Unexpected token 'I', "Internal S"... is not valid JSON`

### Other

- Docker version 20.10.21, build baeda1f
- rTorrent 0.9.8
- ruTorrent 3.10
