### ISSUE TITLE
[Feature Request] Homeassistant

### ISSUE THREAD

**Issue by IIIdefconIII** [benphelps/homepage#683]
### Description

I would like to have some button how i control my lights e.d if possible

**Comment by stevietv** [comment]
I'd love for home asssitant to be able to pass in specific template code and get an output. For example on heimdall I let my homeassistant show the current temperarature of my climate control.

**Comment by Macleykun** [comment]
I've been thinking of what useful information could be shown.
Like stevietv says, i think having the ability to read the value of any entity would be great! Things like:
Number of HACS updates
Temperature of a given thermostat
If something is on/off
Last moment someone was at the door
etc.

Other things that aren't exactly from one entity:
Amount of unresponsive sensors
Amount of sensors/integrations
Pending restart?

I hope something like this would be possible, just reading is enough in my eyes :)

**Comment by Macleykun** [comment]
Adding a bit more info to this issue.
here i show some examples with curl:
```
# Test
curl \
  -H "Authorization: Bearer tokenstring" \
  -H "Content-Type: application/json" \
  https://domain.HA/api/

# Amount of unavailable entities
curl \
  -H "Authorization: Bearer tokenstring" \
  -H "Content-Type: application/json" \
  https://domain.HA/api/states | grep -o unavailable | wc -l

Output:
2

# get amount of update from hacs entity
curl \
  -H "Authorization: Bearer tokenstring" \
  -H "Content-Type: application/json" \
  https://domain.HA/api/states/sensor.hacs

Output:
{"entity_id":"sensor.hacs","state":"0","attributes":{"repositories":[],"unit_of_measurement":"pending update(s)","icon":"hacs:hacs","friendly_name":"hacs"},"last_changed":"2023-03-06T21:40:45.516702+00:00","last_updated":"2023-03-06T21:40:45.516702+00:00","context":{"id":"01GTWDXAAC1P4PRKACBKJNT30M","parent_id":null,"user_id":null}}

Handy output:
"friendly_name":"hacs"
"unit_of_measurement":"pending update(s)"
"state":"0"

# thermostat entity current temp
curl \
  -H "Authorization: Bearer tokenstring" \
  -H "Content-Type: application/json" \
  https://domain.HA/api/states/climate.tstat_2c595c_lyric_t6_thermostat

Output:
{"entity_id":"climate.tstat_2c595c_lyric_t6_thermostat","state":"heat","attributes":{"hvac_modes":["off","heat"],"min_temp":5,"max_temp":35,"current_temperature":20,"temperature":20,"hvac_action":"idle","friendly_name":"Tstat-2C595C Lyric T6 Thermostat","supported_features":1},"last_changed":"2023-03-06T21:40:37.399563+00:00","last_updated":"2023-03-08T16:39:47.416580+00:00","context":{"id":"01GV11FNER98HV99J813AGYVJK","parent_id":null,"user_id":null}}

  /api/states/<entity_id> (get only state from one entity)

Handy output:
"friendly_name":"Tstat-2C595C Lyric T6 Thermostat"
"current_temperature":20


# Amount of entities
curl   \
  -H "Authorization: Bearer tokenstring" \
  -H "Content-Type: application/json" \
  https://domain.HA/api/states | grep -o entity_id | wc -l

Output: 65
```
Docs: https://developers.home-assistant.io/docs/api/rest/

and lastly, how it could look like:
![image](https://user-images.githubusercontent.com/26381427/223795248-a46b27a6-7b04-4812-903e-6822e42a29bf.png)

Interms of configuration in the yaml file:
```
widget:
    type: homeassistant
    url: http://prowlarr.host.or.ip
    key: apikeyapikeyapikeyapikeyapikey
    panels:
      - name: entity
        override_name: my_entity
        value_name: x
      - name: entity2
```

I hope this helps.

**Comment by juzim** [comment]
Hi!

Is anyone actively working on this? Otherwise I'll give it a shot

**Comment by Macleykun** [comment]
> Hi!
> 
> Is anyone actively working on this? Otherwise I'll give it a shot

nope! But i do thank you for trying to give this a shot!

**Comment by hen-ter** [comment]
Hi,

don't know if someone is actually working on this now, but I've been playing around the past few days and here's what I got
- any number of state or template queries can be configured
- state values default to `"{state} {attributes.unit_of_measurement}"` but can be overwritten
- state labels default to `"{attributes.friendly_name}"` but can be overwritten

I'm fairly new to Home Assistant but I think that should cover the output side of things.

What do you think?

```yaml
        widget:
          type: homeassistant
          url: http://hass.local:8123
          key: access_token
          queries:
            - state: sensor.total_power
            - state: sensor.total_energy_today
              label: energy today
            - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
              label: switches on
            - state: weather.forecast_home
              label: wind speed
              value: "{attributes.wind_speed} {attributes.wind_speed_unit}"
```

![image](https://user-images.githubusercontent.com/43324482/230161244-c8102c7a-e576-440d-95fd-bbfbc0646d2b.png)
