### ISSUE TITLE
[Bug] Broken docker integration

### ISSUE THREAD

**Issue by theBluffit** [benphelps/homepage#691]
### Description

Currently all container indicators are displaying "unkown" and when clicking on it and on "API Error Information" it just shows `API Error: Unknown error`

![grafik](https://user-images.githubusercontent.com/23724545/208264279-dddcc8ae-24c5-4360-9492-5f97d900c6d3.png)

### Steps to reproduce

1. Add service with container info in services.yaml
2. Open homepage

### homepage version

v0.5.5 (d16fd0c)

### Installation method

Docker

### Configuration

Relevant snippet from service.yml:

```yaml
- Jellyfin:
    icon: jellyfin
    href: http://jellyfin.intra.net
    description: Media Server
    server: local
    container: jellyfin
```

### Container Logs

```
[2022-12-17T20:07:10.329Z] error: (node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Browser Logs

Console output:

![grafik](https://user-images.githubusercontent.com/23724545/208264484-233c00e9-d5ca-4ff7-8aeb-c34d84b37ac5.png)

### Other

Docker integration works fine on v0.5.0

I can ping the services and I can successfully check the api as described in [troubleshooting](https://gethomepage.dev/en/more/troubleshooting/#service-widget-errors)
