### ISSUE TITLE
[Bug] PiHole API Broke in Latest FTL 5.20 Release

### ISSUE THREAD

**Issue by CorneliousJD** [benphelps/homepage#723]
### Description

As of 5.20 FTL (part of Pihole) the API doesn't seem to work in Homepage anymore

https://github.com/pi-hole/FTL/releases/v5.20

![image](https://user-images.githubusercontent.com/724777/209391743-dc320833-13bc-481b-bc75-797c7747d488.png)

### Steps to reproduce

Install PiHole with 5.20 FTL and setup the widget for stats.

### homepage version

0.5.5

### Installation method

Docker

### Configuration

```yaml
- Pi-Hole (Primary):
        description: Docker Container    
        href: http://10.0.0.20/admin/
        ping: http://10.0.0.20
        icon: pihole
        server: Docker
        container: PiHole
        widget: 
            type: pihole
            url: http://10.0.0.20
            key: redacted
    - Pi-Hole (Backup):
        description: Raspberry Pi Zero W
        href: http://10.0.0.21/admin/
        ping: http://10.0.0.21
        icon: pihole
        widget: 
            type: pihole
            url: http://10.0.0.21
            key: redacted
```

### Container Logs

Nothing relevant logged.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
