### ISSUE TITLE
homebridge widget

### ISSUE THREAD

**Issue by fate8383** [benphelps/homepage#734]
### Description

widget gives error
API Error: The string did not match the expected pattern.
hombridge is not docker just local install and no child bridges

### Steps to reproduce

update service yaml and see error on homepage

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
- Homebridge:
        href: https://x:x/
        ping: https://x:x/
        icon: homebridge.png
        widget:
            type: homebridge
            url: https://x:x/
            username: x
            password: x
```

### Container Logs

no error in the docker logs
I changed url end to /

before / I got this error
Error getting data from Homebridge: 403.  Data: {"statusCode":403,"message":"Forbidden resource","error":"Forbidden"}

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
