### ISSUE TITLE
Local icons not loading. getting 404

### ISSUE THREAD

**Issue by ShlomiPorush** [benphelps/homepage#75]
Hi, i did as the [docs](https://github.com/benphelps/homepage/wiki/Services#icons), mounted the folder icons into `/app/public/icons` uploaded some icons the then set it in service. 
but the icon is not loading 

docker-compose.yml
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
```

services.yaml
```
- My First Group:
    - Portainer:
        icon: /icons/portainer.svg
        href: "URL"
        description: Portainer
        server: docker
        container: Portainer
```
Here is the result
![image](https://user-images.githubusercontent.com/5992161/189293557-b331567e-c52a-45db-a23e-b77b55ceaeae.png)

console error the third line
![image](https://user-images.githubusercontent.com/5992161/189293413-604ef3bd-fa4e-4a31-81a8-440a5d166175.png)
