### ISSUE TITLE
[Bug] MikroTik; Data not found 

### ISSUE THREAD

**Issue by dnikoloski** [benphelps/homepage#757]
### Description

Set up the widget as recommended in the documentation

![image](https://user-images.githubusercontent.com/119594993/210193182-3372b515-5c54-410f-bce3-d35541d5ab63.png)

### Steps to reproduce

1. Set up widget in services.yaml
2.  Allowed PI ip to access router

### homepage version

v0.5.9 (f6b1304, Dec 31, 2022)

### Installation method

Docker

### Configuration

```yaml
- Network:
    - MikroTik:
        icon: mikrotik.png
        href: http://10.0.1.1
        description: hAP ac^2
        widget:
            type: mikrotik
            url: http://10.0.1.1
            username: ****
            password: ****
```
```


### Container Logs

_No response_

### Browser Logs

_No response_

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
