### ISSUE TITLE
[Bug] Date & Time are moving the page layout when set to long

### ISSUE THREAD

**Issue by ozdeadmeat** [benphelps/homepage#764]
### Description

The Date Time Is moving the search bar when the seconds tick. It is minor but really annoying. I think this could be fixed by offering the ability to have the date on one line and the time on another line. The ability to change the text size of either of those (date or time) would also be handy. But long story short, the date & time move the search bar or whatever they are next to when the time is set to long.

![image](https://user-images.githubusercontent.com/11052863/210228979-724c65cf-9dd7-48ed-83f6-879b6bac38b4.png)

![image](https://user-images.githubusercontent.com/11052863/210229007-ea664115-f705-4f5a-88b8-1c41ffa9b9cb.png)

### Steps to reproduce
Use the config below

### homepage version

v0.5.9

### Installation method

Docker

### Configuration

```yaml
**Settings.yaml**
`language: en-AU
layout:
  Downloaders:
    style: row
    columns: 2
  Media Managers:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 2
  Docker Managers:
    style: row
    columns: 2`

**widgets.yaml**
`---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

#- resources:
#    cpu: true
#    memory: true
#    disk: /

- datetime:
    text_size: sm
    format:
      dateStyle: long
      timeStyle: long
      hour12: false

- search:
    provider: google
    focus: true # Optional, will set focus to the search bar on page load
    target: _blank

- openmeteo:
    label: Canberra # optional
    latitude: -35.282001
    longitude: 149.128998
    timezone: Australia/Sydney # optional
    units: metric # or imperial
    cache: 10 # Time in minutes to cache API responses, to stay within limits`
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
