### ISSUE TITLE
[Feature Request] Use abbreviation in bookmarks as a fallback if the icon is not found

### ISSUE THREAD

**Issue by Jose134** [benphelps/homepage#814]
### Description

Right now, if you specify both the icon and abbr properties for a bookmark, if the icon isn't found it displays a "logo" text (which, from what I've seen in dev tools it's the alt for the img tag). I suggest using the abbr property, if specified, as the alt text instead since right now it seems like homepage is ignoring it.

### Other

Example from my own homepage:

![imagen](https://user-images.githubusercontent.com/12801876/212394322-428ccb85-5bf0-4de3-a03c-d9fe17ef1c7d.png)

in bookmarks.yaml:
```
- "":
    - Osu:
        - abbr: OSU
          icon: osu.png
          href: https://osu.ppy.sh/
```
