### ISSUE TITLE
[Bug] Second Disk Not Found

### ISSUE THREAD

**Issue by john-okeefe** [benphelps/homepage#836]
### Description

When trying to display a widget for my second disk resource it has an API Error with 404 Not Found.

My widgets.yaml
```
- resources:
    cpu: true
    memory: true
    disk: /
- resources:
    disk: /media/media

- search:
    provider: duckduckgo
    target: _blank
```
As you can see I have a second disk mounted at /media/media
```
Filesystem      Size  Used Avail Use% Mounted on
dev              16G     0   16G   0% /dev
run              16G  3.2M   16G   1% /run
/dev/sdb2       211G   97G  104G  49% /
tmpfs            16G  332K   16G   1% /dev/shm
tmpfs            16G   47M   16G   1% /tmp
/dev/sda5       917G  687G  184G  79% /media/media
/dev/sdb1       300M  432K  299M   1% /boot/efi
tmpfs           3.2G   28K  3.2G   1% /run/user/1000
```
This is what the browser shows:
![image](https://user-images.githubusercontent.com/5943635/212984394-6a6cb58f-dfd0-48c7-8253-3f28a3cb8366.png)

I have also tried this both with the http://192.168... url and a custom https://home.server.com url. Same issue.
Docker image is running as root and regular ```disk: /``` works.

### Steps to reproduce

1. Add second disk to yaml file.
2. See API Error

### homepage version

v0.5.10 (e1799f1, Jan 7, 2023)

### Installation method

Docker

### Configuration

```yaml
- resources:
    cpu: true
    memory: true
    disk: /
- resources:
    disk: /media/media

- search:
    provider: duckduckgo
    target: _blank
```

### Browser Logs

`
<html><body>
<span class="message-body-wrapper"><span class="message-flex-body"><span class="message-body devtools-monospace"><span class="method">GET</span><span class="url" title="http://192.168.50.7:3000/api/widgets/resources?type=disk&amp;target=/media/media">http://192.168.50.7:3000/api/widgets/resources?type=disk&amp;target=/media/media</span><a class="status"><span class="status-info">[HTTP/1.1 <span class="status-code" data-code="404" title="Learn More">404</span> Not Found 6ms]</span></a></span> </span><div class="network-info network-monitor"><div class="devtools-sidebar-tabs"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item panel-with-code is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div></div></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><div id="headers-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="headers-tab"><div class="tab-panel panel-with-code"><div class="headers-panel-container"><div class="devtools-toolbar devtools-input-toolbar"><div class="devtools-searchbox"><input class="devtools-filterinput" placeholder="Filter Headers" type="search" value=""></div></div><div class="panel-container"><div class="headers-overview"><div class="url-preview"><div class="properties-view"><div class="tree-container">

  |  
-- | --
GET | http://192.168.50.7:3000/api/widgets/resources?type=disk&target=/media/media

</span>
</body>
</html>
`

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I use two disks without issue, as do many. Im not sure if this is the issue, but wonder if your yaml should look like

```
- resources:
    cpu: true
    memory: true
    disk: 
        - /
        - /media/media
```

Have you tried a different name, recreating the container?

**Comment by john-okeefe** [comment]
I have restructured my widgets.yaml to look like:

```
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: 
      - /
      - /media/media

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: md
    format:
        dateStyle: short
        timeStyle: short
        hour12: true

- openweathermap:
    units: imperial
    apiKey: <apiKey>
    cache: 5
```
I have tried destroying and restarting the docker container. Still isn't fixed and now it seems to be ignoring my settings.yaml file. Not sure why.

**Comment by shamoon** [comment]
And what does your compose file look like?

**Comment by slsnow** [comment]
I don't want to hijack the issue, but I believe I'm dealing with the same issue. Mine is happening on an 11T software raid mounted at "/data". I'm wondering if the size is the problem, it being a Raid, or something else. 

```
- resources:
    label: Lightning
    cpu: true
    memory: true
    expanded: true
    disk:
      - /data
      - /
```
df output:
```
/dev/mapper/system-root  108G   52G   50G  51% /
/dev/mapper/data-data     11T  6.9T  4.1T  64% /data
```
Of note, the order doesn't matter for me, it fails for "data" whether you put it first or second.

![image](https://user-images.githubusercontent.com/66100515/213812635-f35cc9a9-463a-4ef9-819d-c9c116c4e295.png)


The disk mounted at "/" works just fine though, as does the memory and cpu. Since the disk mounted at "/" works, that leads me to believe it's not a problem with the docker volume, or permissions.

**Comment by slsnow** [comment]
Again not trying to hijack anything, so we can focus on the reporter's issue (I'm not in a hurry). Just curious if his is a raid or not, and what the disk size should be showing.

**Comment by shamoon** [comment]
Odd. The 404 makes me think the failure is https://github.com/benphelps/homepage/blob/main/src/pages/api/widgets/resources.js#L18 but Im not aware of why that would fail and would be interesting to know if https://github.com/SunilWang/node-os-utils `drive.info()` works after that or not. I suppose if it correctly fails when the drive doesnt exist and succeeds eg. in this case one could argue the initial check with `existsSync` isnt needed.

Obviously, I cant recreate this so I cant test...

**Comment by john-okeefe** [comment]
@shamoon Sorry about that. Docker file below.
```
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=970
      - TZ=America/New_York
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
```

I'm hoping/thinking I just did something wrong with the Dockerfile because I cloned the repository and launched a dev environment and it worked just fine.

@slsnow I have an SSD as / and a HDD as /media/media. No raid, or NAS storage or anything like that. All local.
