### ISSUE TITLE
[Bug] .6 Ignoring Settings.yaml and docker statuses broken

### ISSUE THREAD

**Issue by KillahB33** [benphelps/homepage#848]
### Description

Settings.yaml seems to be ignored, I just set everything up today. Was working great, then just loaded it up now and I guess watchtower updated and it appears to have undone everything I setup in settings. Layout is back to default and so is the background with all those settings.

### Steps to reproduce

I guess upgrade container to .6 from .5.11(I think that's the one before it)

### homepage version

.6

### Installation method

Docker

### Configuration

```yaml
title: My Home Lab

layout:
  Service Management:
    style: row
    columns: 3
  Media:
    style: row
    columns: 3
  Utilities:
    style: row
    columns: 3

background: "https://i.nofate.me/xTIlua140vIpaAky.png"
backgroundOpacity: 0.5

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
```

### Container Logs

Listening on port 3000
[2023-01-19T22:07:58.545Z] info: kubernetes.yaml was copied to the config folder
Listening on port 3000

### Browser Logs

Getting 500 from all the docker status stuff.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
