### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cubagithub** [benphelps/homepage#859]
### Description

My Portainer widget is configured according to https://gethomepage.dev/en/services/portainer/ and I only see Allowed fields: `["running", "stopped", "total"]`. 
In this post https://www.reddit.com/r/selfhosted/comments/wx8knv/ive_created_a_new_selfhosted_dashboard/ by phelpsben his screenshot shows CPU MEM RX TX fields - how can I configure these please?

### Steps to reproduce

1. configure portainer service according to https://gethomepage.dev/en/services/portainer/
2. observe no CPU/memory resource fields available

### homepage version

v0.5.10 (e1799f1, Jan 8, 2023)

### Installation method

Docker

### Configuration

```yaml
- Portainer:
        icon:   portainer.png  
        href: http://192.168.0.99:9000
        description: Container management
        widget:
            type: portainer
            fields: ["running", "stopped", "cpu", "mem"]
            url: http://192.168.0.99:9000
            env: 2
            key:
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
