### ISSUE TITLE
[Bug] Portainer Widget - defining url value with a trailing forward-slash causes rendering to fail

### ISSUE THREAD

**Issue by Beguiled** [benphelps/homepage#869]
### Description

The Portainer Widget does not render properly when a user defines the widget's `url` value with a trailing forward-slash. Other widgets (such as pihole) do not have this problem.

Here is a configuration example where the issue becomes present:
```yaml
- Portainer (rpi0):
    description: Container Management
    href: http://192.168.1.50:9000/#!/2/docker/stacks
    ping: http://192.168.1.50:9000/
    icon: portainer.png
    widget:
      type: portainer
      url: http://192.168.1.50:9000/
      env: 2
      key: <redacted>
```

Example screenshot:
![image](https://user-images.githubusercontent.com/7060159/214119106-f3d70732-5757-4a3a-91b1-81634bffd14b.png)

Configuration example when the forward-slash is removed:
```yaml
- Portainer (rpi0):
    description: Container Management
    href: http://192.167.1.50:9000/#!/2/docker/stacks
    ping: http://192.168.1.50:9000/
    icon: portainer.png
    widget:
      type: portainer
      url: http://192.168.1.50:9000
      env: 2
      key: <redacted>
```

Example screenshot:
![image](https://user-images.githubusercontent.com/7060159/214119527-48820a51-8f54-4555-8f74-d74d89fc5316.png)

### Steps to reproduce

1. Open services.yaml
2. Define a service (ex: Portainer)
3. Add a widget to the service, following the [portainer widget documentation](https://gethomepage.dev/en/services/portainer/)
4. When defining the `url` value, include a trailing forward-slash and save your changes.

### homepage version

v0.6.3 (c74b467, Jan 22, 2023)

### Installation method

Docker

### Configuration

```yaml
- Portainer (rpi0):
    description: Container Management
    href: http://192.168.1.50:9000/#!/2/docker/stacks
    ping: http://192.168.1.50:9000/
    icon: portainer.png
    widget:
      type: portainer
      url: http://192.168.1.50:9000/
      env: 2
      key: <redacted>
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
