### ISSUE TITLE
Tautulli - Service Showing "NaN Bitrate"

### ISSUE THREAD

**Issue by CameronMacG** [benphelps/homepage#87]
Hello,

I have recently deployed 'Homepage' within my home environment and I'm loving it so far!

I am however having an issue with the Tautulli Service Widget. The page recognizes that the container is up, but wont show any "Playing", "Transcoding" data and "Bitrate" is showing as 'NaN Bitrate'.

My Plex instance is not containerized. This is its own dedicated VM due to how my storage is set up within my personal environment, however the Tautulli instance is dockerized and this works fine as it can communicate with the Plex server itself.

Below is an excerpt from my "services.yaml";

```
- Media Monitoring:
    - Tautulli:
        icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/tautulli.png
        href: https://<REDACTED>
        description: Media Library
        server: https://<REDACTED>
        container: tautulli
        widget:
            type: tautulli
            url: https://<REDACTED>
            key: SOMEAPIKEYHERE
```

Just for clarity as well, my Plex instance does sit behind NGINX Proxy Mgr with a self-signed cert. Tatulli can see the local IP and WAN IP for the Plex server too.

Many thanks for your help in advance!
