### ISSUE TITLE
API Error Information [Bug] 

### ISSUE THREAD

**Issue by IIIdefconIII** [benphelps/homepage#882]
### Description

As of three days im getting the API Error Information feed back from my services.
Tried on several browser, chrome, edge, firefox

It works for a minute and after a minute it showing it like the picture.
I double checked the API keys and they are valid, also the containers are up and running. Trying to completely redownload the docker container homepage.

Can anyone assist me to get this false negatives fixed?
Directly after rafresh:
![image](https://user-images.githubusercontent.com/9917659/214690577-d56f0115-61ce-4974-8ab2-30068a09ba7a.png)

After like 30 second till a minutre.
![image](https://user-images.githubusercontent.com/9917659/214690295-1f480a67-9a1d-46e0-8a88-73a00cec36e5.png)

### Steps to reproduce

1. go to the homepage page
2. Refresh and at seems fine for like 30 second till a minute
3. After that time is over it chancges to the after picture i uploaded above.

### homepage version

v0.6.3 (c74b467.jan 22m 2023)

### Installation method

Docker

### Configuration

```yaml
- Bazarr:
        icon:  bazarr.png
        href: https://bazarr.domain.info
        description: Subtitle Managment (domain) (.5:6767)
        server: my-docker
        container: bazarr
        widget:
          type: bazarr
          url: http://10.3.1.5:6767
          key: apikey

      - NZBGet:
        icon: nzbget.png
        href: https://nzbget.domain.info/
        description: Download Client (domain) (.5:6789)
        container: nzbget
        server: my-docker
        widget:
          type: nzbget
          url: http://10.3.1.5:6789
          username: username
          password: password

    - Overseerr:
        icon: overseerr.png
        href: https://overseerr.domain.info
        description: Media Request (domain) (.5:5055)
        server: my-docker
        container: overseerr
        widget:
          type: overseerr
          url: http://10.3.1.5:5055
          key: apikey

    - Prowlarr: 
        icon: prowlarr.png
        href: https://prowlarr.domain.info
        description: Plex Monitoring (domain) (.5:9696)
        container: prowlarr
        server: my-docker
        widget:
          type: prowlarr
          url: http://10.3.1.5:9696
          key: apikey

    - qBittorrent: 
        icon: qbittorrent.png
        href: https://qbittorrent.domain.info
        description: Torrent Download (domain) (.5:8168)
        container: qbittorrent
        server: my-docker
        widget:
          type: qbittorrent
          url: http://10.3.1.5:8168
          username: usnermae
          password: password
```

### Container Logs

couldnt find erros in the log vieuwing on dozzle

### Other

docker = latest on synology nas, doesnt indicate a version

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
