### ISSUE TITLE
[Bug] NZBGet Service Showing Megabit instead of Megabyte

### ISSUE THREAD

**Issue by themadman0980** [benphelps/homepage#892]
### Description

Hopefully this isn't too complex, but the NZBGet interface is showing values with the incorrect unit label of Megabits (Mb) instead of Megabytes (MB).

<img width="406" alt="Screen Shot 2023-01-29 at 12 24 35 pm" src="https://user-images.githubusercontent.com/107305060/215298983-5d678a6c-d0d2-4db9-a3ca-d59e6a3701ff.png">
<img width="296" alt="Screen Shot 2023-01-29 at 12 24 40 pm" src="https://user-images.githubusercontent.com/107305060/215298984-51d8541b-1832-460f-bd4a-5f92d25cd9f7.png">

### Steps to reproduce

1. Add NZBGet service to Homepage
2. Check Homepage web UI

### homepage version

v0.6.2 (cdbdb86, Jan 21, 2023)

### Installation method

Docker

### Configuration

```yaml
- NZBGet:
        icon: nzbget.png
        href: [my_url_here]
        ping: http://192.168.1.11:6789
        description: Usenet Downloads
        widget:
          type: nzbget
          url: http://192.168.1.11:6789
          username: admin
          password: [my_password_here]
```

### Other

When checking the [NZBGet API status endpoint](https://nzbget.net/api/status), the following entry suggests the result is in Bytes, not Bits:
"DownloadRate (int) - Current download speed, in Bytes per Second."

This is more of a suggestion, but could it perhaps be simpler to display the number with MB instead of Megabytes when this is corrected? Just a bit more concise.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
