### ISSUE TITLE
Feature Request: Jellyfin Integration

### ISSUE THREAD

**Issue by sixshooterz** [benphelps/homepage#9]
Similar to the Emby support currently existing, Jellyfin support would be phenomenal!

**Comment by phillipsjamesg** [comment]
I tested this out with my setup. Emby and Jellyfin share the same API since Jellyfin is a fork of Emby. It worked just fine for me.
```
    - Jellyfin: # Service Title
        icon: jellyfin.png # Icon, see: https://github.com/walkxcode/dashboard-icons or public/icons
        href: http://jellyfin.home/ # Link to the service
        description: Media server # Description of the service
        server: my-docker # Docker server the service is running on
        container: jellyfin # Docker container the service is running on
        widget:
          type: emby
          url: http://jellyfin.home
          key: keykeykeykey
          	```

**Comment by darrylgibbs** [comment]
@phillipsjamesg I'm getting an "Emby API Error" on the dashboard.  Am I inputting the API key incorrectly?

```
- Media: # Services Group Title
    - Jellyfin: # Service Title
        icon: jellyfin.png # Icon, see: https://github.com/walkxcode/dashboard-icons or public/icons
        href: http://10.0.0.5:8096/ # Link to the service
        description: Media server # Description of the service
        server: my-docker # Docker server the service is running on
        container: jellyfin # Docker container the service is running on
        widget:
          type: emby
          url: http://10.0.0.5:8096/
          key: c14e450a1a0141ed8cfb343f4432f2ea # I plan on changing this API key after posting here
```

**Comment by phillipsjamesg** [comment]
@darrylgibbs try removing the trailing / in the url.. i dont have it but you do

**Comment by darrylgibbs** [comment]
@phillipsjamesg that did fix it, thanks!  Weird though cause the standard config example has one.

**Comment by phillipsjamesg** [comment]
@darrylgibbs no clue. i figured it out when i was playing with it. so far i like it though. hopefully more features added soon.

**Comment by darrylgibbs** [comment]
@phillipsjamesg since you seem to know what is going on (lol) is having special characters in an API going to not make it work? My Portainer API has an error too, but it has special characters.  I know that docker-compose.yml files generally don't like having special characters in passwords.

**Comment by phillipsjamesg** [comment]
I added a few notes down below. I run two servers, each server has portainer and then on my main server I connected to the secondary so I can see both on the primary and control it from there. For the `env` portion you find the number in the URL when you look at the dashboard of the environment. `https://x.x.x.x:9443/#!/   NUMBERHERE   /docker/dashboard` For my primary the number is 2, for the secondary it's 6. Again, no trailing / on the URL.

I only know what's going on because I played with it.

```
    - Portainer:
        icon: portainer.png
        href: https://x.x.x.x:9443 # use however you get to the UI
        description: Container management
        server: my-docker
        container: portainer
        widget:
          type: portainer
          url: https://x.x.x.x:9443 # use HTTPS
          env: 2 # find the env ID that you are needing
          key: keykeykey # needs to be from the admin account
```

**Comment by benphelps** [comment]
> I tested this out with my setup. Emby and Jellyfin share the same API since Jellyfin is a fork of Emby. It worked just fine for me.
> 
> ```
>     - Jellyfin: # Service Title
>         icon: jellyfin.png # Icon, see: https://github.com/walkxcode/dashboard-icons or public/icons
>         href: http://jellyfin.home/ # Link to the service
>         description: Media server # Description of the service
>         server: my-docker # Docker server the service is running on
>         container: jellyfin # Docker container the service is running on
>         widget:
>           type: emby
>           url: http://jellyfin.home
>           key: keykeykeykey
> ```

Thats fantastic, I'll make the widget work under both keys then.

**Comment by benphelps** [comment]
> I added a few notes down below. I run two servers, each server has portainer and then on my main server I connected to the secondary so I can see both on the primary and control it from there. For the `env` portion you find the number in the URL when you look at the dashboard of the environment. `https://x.x.x.x:9443/#!/ NUMBERHERE /docker/dashboard` For my primary the number is 2, for the secondary it's 6. Again, no trailing / on the URL.
> 
> I only know what's going on because I played with it.
> 
> ```
>     - Portainer:
>         icon: portainer.png
>         href: https://x.x.x.x:9443 # use however you get to the UI
>         description: Container management
>         server: my-docker
>         container: portainer
>         widget:
>           type: portainer
>           url: https://x.x.x.x:9443 # use HTTPS
>           env: 2 # find the env ID that you are needing
>           key: keykeykey # needs to be from the admin account
> ```

Correct on all parts, I've added more documentation for the service widgets, including Portainer, which you can find here: https://github.com/benphelps/homepage/wiki/Service-Widgets#portainer

**Comment by phillipsjamesg** [comment]
@benphelps Wasn't trying to step on toes. Hope what I figured out helps you out.

**Comment by benphelps** [comment]
> @benphelps Wasn't trying to step on toes. Hope what I figured out helps you out.

Not at all, very much appreciated.

**Comment by phillipsjamesg** [comment]
Keep up with the work. I really like it. I've tried a bunch of different homepages and so for I like this one the best.

**Comment by darrylgibbs** [comment]
Ah man I'm sorry, I didn't even notice there was a wik! Apologies!

Thanks for all the help from everyone!  This is a cracking good dashboard!

**Comment by benphelps** [comment]
This has been added now, 

```yaml
widget:
  type: jellyfin
  url: http://jellyfin.host.or.ip
  key: apikeyapikeyapikeyapikeyapikey
```
