### ISSUE TITLE
[Bug] Custom port mapping does not work. 

### ISSUE THREAD

**Issue by cribbageSTARSHIP** [benphelps/homepage#901]
### Description

I tried deploying this with a custom port and it landed on a screen that said:

Application error: a client-side exception has occurred (see the browser console for more information).

### Steps to reproduce

tried mapping to 15001. reverting back to port 3000 caused it to work again

### homepage version

v0.6.4 (5af01d2, Jan 29, 2023)

### Installation method

Docker

### Configuration

```yaml
version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 15001:3000
    volumes:
      - /boh/configs/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /boh/configs/homepage/images:/app/public/images
      - /boh/configs/homepage/icons:/app/public/icons
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
