### ISSUE TITLE
[Bug] Radarr widget shows other queued items

### ISSUE THREAD

**Issue by snnacks** [benphelps/homepage#907]
### Description

Currently the Radarr widget shows items in the queue that were not added by Radarr. What I find interesting is that Sonarr does not do this and only shows items in queue if added by Sonarr. I am wondering if there is a difference in the API between the two, but thought I would report this as a bug since one application does this and the other does not.
![image](https://user-images.githubusercontent.com/58410628/215865986-045e0b5e-d572-4abe-8be1-090d4554548d.png)
![image](https://user-images.githubusercontent.com/58410628/215866018-d0354d26-0411-4ecd-958f-ed19614286e8.png)

In the 'Activity' tab of both Radarr and Sonarr you can disable "Show Unknown Movie Items", but this only seems to affect viewing in the browser and does not affect the widget.

### Steps to reproduce

1. Enable Radarr widget
2. Have Radarr detect something in queue (add something to the download client either manually or via sonarr, etc.)

### homepage version

v0.6.4

### Installation method

Unraid

### Configuration

```yaml
    - Radarr:
        icon: radarr.png
        href: http://192.168.1.14:7878/
        description: Movie tracking and downloading
        widget:
            type: radarr
            fields: ["wanted", "queued", "movies"]
            url: http://192.168.1.14:7878
            key: api_key_here
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
