### ISSUE TITLE
error  PipeConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)[Bug] 

### ISSUE THREAD

**Issue by ziolupo68** [benphelps/homepage#918]
### Description

Homepage is working but it's not able to understand if other containers are running or not.
Until a couple of weeks ago everything was working fine.
Now I have always "unknown" status and the logg is full of:
error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
02/02/2023 11:51:22   at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)

### Steps to reproduce

1. run container homepage
2. lokk at log

### homepage version

v0.6.5 (c5ac34a, Feb 2, 2023)

### Installation method

Docker

### Configuration

```yaml
homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome    
    ports:
      - 3200:3000
    volumes:
      - /srv/homepage:/app/config # Make sure your local config directory exists
      - /srv/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
```

### Container Logs

`02/02/2023 11:56:09
[2023-02-02T10:56:09.108Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
02/02/2023 11:56:09
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)
02/02/2023 11:56:09
[2023-02-02T10:56:09.109Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
02/02/2023 11:56:09
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)
02/02/2023 11:56:09
[2023-02-02T10:56:09.110Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
02/02/2023 11:56:09
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)
02/02/2023 11:56:09
[2023-02-02T10:56:09.110Z] error: <dockerStatusService> Error: connect EACCES /var/run/docker.sock
02/02/2023 11:56:09
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)
`

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
