### ISSUE TITLE
[Bug] Total in widget portainer 

### ISSUE THREAD

**Issue by jerome6994** [benphelps/homepage#942]
### Description

![image](https://user-images.githubusercontent.com/66921143/216842963-eb5de562-552d-49ab-a602-5751c025aaff.png)

Good evening
First of all thank you for this project which is very nice for a novice like me :)
I just set up the services to carry and I have a slight problem!
On the local I have 12 containers running 0 stopped and 13 in total! it seems that in the total he counts Portainer here but not in the running container.

On the remote (via API, port 2375) I have 10 running 0 stopped and 10 in total (it does not count Portainer here)

### Steps to reproduce

Just my configuration

### homepage version

latest

### Installation method

Docker

### Configuration

```yaml
docker.yaml

docker-test:
   socket: /var/run/docker.sock
   #swarm: true

docker-applications:
   host: IP
   port: 2375


services.yaml

- My First Group:
    - Docker Applications:
        icon: portainer.png
        href: https://IP:9443
        description: Docker Applications
        ping: https://IP:9443/
        server: docker-applications
        container: portainer
        widget:
          type: portainer
          url: https://IP:9443
          env: 2
          key: MY_KEY
    - Docker Test:
        icon: portainer.png
        href: https://IP2:9443
        description: Docker Test
        widget: 
          type: portainer
          url: https://IP2:9443
          env: 2
          key: MY_KEY
        ping: https://IP2:9443/
        server: docker-test
        container: portainer
```

### Container Logs

![image](https://user-images.githubusercontent.com/66921143/216843429-e49a3641-d7be-453c-912f-0351fc16179c.png)

### Browser Logs

nothing

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
