### ISSUE TITLE
[Bug] RuTorrent non-functional

### ISSUE THREAD

**Issue by Griffen8280** [benphelps/homepage#948]
### Description

RuTorrent API error when attempting to communicate.  Information from the log is unhelpful, it only has a single line:

[2023-02-06T15:22:21.887Z] error: undefined

![image](https://user-images.githubusercontent.com/42878642/217017359-d8bc31e5-51e6-49f6-8f2f-374ae1300782.png)

I have verified that the httprpc plugin is present and functional at:    
https://ducati.myseedbox.site/rutorrent/plugins/httprpc/actions.php -> Exists    
Currently I have various *arr apps setup to work with this plugin

### Steps to reproduce

1. Setup the RuTorrent integration w/ widget
2. Go to homepage site
3. See API error

### homepage version

0.6.6

### Installation method

Docker

### Configuration

```yaml
- RuTorrent:
        icon: rutorrent.png
        href: https://ducati.myseedbox.site
        description: Main Seedbox
        widget:
          type: rutorrent
          url: https://ducati.myseedbox.site/rutorrent
          username: <redacted>
          password: <redacted>
```

### Container Logs

[2023-02-06T15:22:21.887Z] error: undefined

### Browser Logs

XHRGEThttp://192.168.1.10:3015/api/services/proxy?type=rutorrent&group=Networking+Utilities&service=RuTorrent&endpoint=undefined
[HTTP/1.1 500 Internal Server Error 1287ms]

	
GET
	http://192.168.1.10:3015/api/services/proxy?type=rutorrent&group=Networking Utilities&service=RuTorrent&endpoint=undefined
Status
500
Internal Server Error
VersionHTTP/1.1
Transferred171 B (21 B size)
Referrer Policystrict-origin-when-cross-origin

XHRGEThttp://192.168.1.10:3015/api/services/proxy?type=rutorrent&group=Networking+Utilities&service=RuTorrent&endpoint=undefined
[HTTP/1.1 500 Internal Server Error 350ms]

### Other

docker version = 20.10.21 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
