### ISSUE TITLE
[Bug] Kubernetes Ingress Annotations with External Apps 

### ISSUE THREAD

**Issue by Aesop7** [benphelps/homepage#957]
### Description

The Ingress annotations only work if there is a corresponding Kubernetes app.  This causes an issue (at least for me) for apps that are hosted outside of the cluster, but utilize Kubernetes Ingresses (e.g. an externally-hosted version of PiHole that uses ingress-nginx for its SSL certificate)

When there is no corresponding k8s app for the Ingress, the service ends up getting rendered like this:

![image](https://user-images.githubusercontent.com/9644862/217161427-1e7a3c6b-3f4c-4ef4-9732-7a206355ca3f.png)

The issue is that small, empty box on the top right:

![image](https://user-images.githubusercontent.com/9644862/217161968-077c664a-4c93-46ef-b7f3-5674567c9c73.png)

I really like being able to use ingress annotations for Homepage, so I tried to adjust the annotations to have it display as a [ping](https://gethomepage.dev/en/configs/services/) instead, but that also failed to work.

Here's a copy of the external service's Kubernetes manifests:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  ports:
    - targetPort: 443
      port: 80
      protocol: TCP
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pihole
subsets:
  - addresses:
    - ip: 10.10.10.9
    ports:
    - name: http
      port: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  annotations:
    kubernetes.io/ingress.class: "internal-nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: PiHole
    gethomepage.dev/description: Ad Blocker and Local DNS
    gethomepage.dev/group: Admin
    gethomepage.dev/ping: "https://pihole.my.network/admin"
    gethomepage.dev/icon: pihole.png
    gethomepage.dev/widget.type: "pihole"
    gethomepage.dev/widget.url: "https://pihole.my.network"
    gethomepage.dev/widget.key: "secretwidgetkey"
spec:
  rules:
  - host: pihole.my.network
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pihole
            port:
              number: 80
```

### Steps to reproduce

1. Spin up Homepage on a Kubernetes cluster
2. Create a Kubernetes manifest for an external service (should include Ingress, Service, and Endpoint)
4.  Add the following Ingress annotations:
```yaml
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: ExternalApp
    gethomepage.dev/description: Testing
    gethomepage.dev/group: TestGroup
    gethomepage.dev/ping: "https://www.google.com"
```

### homepage version

v0.6.6

### Installation method

Other (please describe above)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
@jameswynn let us know if this is something you can look into, would appreciate

**Comment by jameswynn** [comment]
I hadn't considered this configuration. I'll look into it.

**Comment by jameswynn** [comment]
I've verified that my PR will address this issue. It turns out that the external services will work just fine, I just hadn't implemented the "ping" attribute.

**Comment by Aesop7** [comment]
@jameswynn I love the support for Ping!  🎉   However (and this could be that I don't have the latest version of Homepage) - I am still seeing an empty box on ingresses w/o services:

![image](https://user-images.githubusercontent.com/9644862/220197346-a78438d7-0b72-44bb-9634-2c5a1a9158fd.png)

**Comment by jameswynn** [comment]
@Aesop7 I think its trying to find a the service and failing. Perhaps there should be another configuration option to disable it entirely. I'll take a closer look tonight.

**Comment by jameswynn** [comment]
@JazzFisch @Aesop7 What do you think about a new "external" attribute for this particular edge case? I have a configuration like this working for me locally with a fairly simple code change:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptimekuma
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Uptime Kuma
    gethomepage.dev/description: Service Uptime Monitoring
    gethomepage.dev/group: Admin
    gethomepage.dev/url: "https://uptime.k3d.localhost"
    gethomepage.dev/icon: uptime-kuma.png
    gethomepage.dev/external: "true"
```
