### ISSUE TITLE
[Bug] ?  Pihole duplicated error

### ISSUE THREAD

**Issue by jgiddens** [benphelps/homepage#966]
### Description

Hi!  I have two different pihole servers on my network.  I have them configured thusly:
![image](https://user-images.githubusercontent.com/2255444/217568486-f53ae9f9-583d-4d56-8568-5e9873e50a17.png)

(i dont care you can see my api key, its not exposed externally.  Also, its notable that both servers have the same API key, since both servers use the same web admin password and apparently Pihole just hashes that for an api key)

When configured this way I get two entries on my home page that when clicked go to the correct destination but both show the exact same data in the widget:

![image](https://user-images.githubusercontent.com/2255444/217569004-a9d47d8b-3990-4a70-b6c8-a65f835d3bda.png)

Any ideas?

### Steps to reproduce

Open the browser to homepage.  

### homepage version

v0.6.6 (29e0b30, Feb 2, 2023)

### Installation method

Docker

### Configuration

```yaml
- Pihole:
        href: http://10.0.10.50/admin
        description: Main Pihole
        icon: pihole.png 
        widget:
            type: pihole 
            url: http://10.0.10.50
            key: d50afa1c3d4d1a4c9727906360bb98772c0dede6421683f497c162d0f2961cfe 
    - Pihole:
        href: http://10.0.10.52/admin
        description: Secondary Pihole
        icon: pihole.png 
        widget:
            type: pihole 
            url: http://10.0.10.52
            key: d50afa1c3d4d1a4c9727906360bb98772c0dede6421683f497c162d0f2961cfe
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
