### ISSUE TITLE
[Feature Request] Add Qwant search engine

### ISSUE THREAD

**Issue by petitssuisses** [benphelps/homepage#971]
### Description

Could you please add Qwant search engine in the list ?
https://www.qwant.com

Requests have the following form : 
https://www.qwant.com/?q=homepage+selfosted&t=web

Thanks !

**Comment by Lehoooo** [comment]
```
- search:
    provider: custom
    url: https://qwant.com/?q=
    target: _blank
```

in widgets.yaml

read the docs - https://gethomepage.dev/en/widgets/search/
